// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/moderationrule/types.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/moderationrule/types.go -destination=internal/service/moderationrule/mock/mock_service.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	moderationrule "github.com/vpt/blog-backend/internal/repository/moderationrule"
	ruleindex "github.com/vpt/blog-backend/internal/service/moderation/ruleindex"
	moderationrule0 "github.com/vpt/blog-backend/internal/service/moderationrule"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// BatchStatus mocks base method.
func (m *MockService) BatchStatus(ctx context.Context, cmd moderationrule0.BatchStatusCommand) (moderationrule0.Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchStatus", ctx, cmd)
	ret0, _ := ret[0].(moderationrule0.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchStatus indicates an expected call of BatchStatus.
func (mr *MockServiceMockRecorder) BatchStatus(ctx, cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchStatus", reflect.TypeOf((*MockService)(nil).BatchStatus), ctx, cmd)
}

// CancelCandidate mocks base method.
func (m *MockService) CancelCandidate(ctx context.Context, rulesetID, actorID uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelCandidate", ctx, rulesetID, actorID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CancelCandidate indicates an expected call of CancelCandidate.
func (mr *MockServiceMockRecorder) CancelCandidate(ctx, rulesetID, actorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelCandidate", reflect.TypeOf((*MockService)(nil).CancelCandidate), ctx, rulesetID, actorID)
}

// CreateRule mocks base method.
func (m *MockService) CreateRule(ctx context.Context, cmd moderationrule0.CreateRuleCommand) (moderationrule0.Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRule", ctx, cmd)
	ret0, _ := ret[0].(moderationrule0.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRule indicates an expected call of CreateRule.
func (mr *MockServiceMockRecorder) CreateRule(ctx, cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRule", reflect.TypeOf((*MockService)(nil).CreateRule), ctx, cmd)
}

// ListRules mocks base method.
func (m *MockService) ListRules(ctx context.Context, query moderationrule0.ListQuery) (moderationrule.RulePage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRules", ctx, query)
	ret0, _ := ret[0].(moderationrule.RulePage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRules indicates an expected call of ListRules.
func (mr *MockServiceMockRecorder) ListRules(ctx, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRules", reflect.TypeOf((*MockService)(nil).ListRules), ctx, query)
}

// Metadata mocks base method.
func (m *MockService) Metadata(ctx context.Context) (moderationrule0.Metadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Metadata", ctx)
	ret0, _ := ret[0].(moderationrule0.Metadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Metadata indicates an expected call of Metadata.
func (mr *MockServiceMockRecorder) Metadata(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Metadata", reflect.TypeOf((*MockService)(nil).Metadata), ctx)
}

// PublishCandidate mocks base method.
func (m *MockService) PublishCandidate(ctx context.Context, rulesetID, expectedBase, actorID uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishCandidate", ctx, rulesetID, expectedBase, actorID)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishCandidate indicates an expected call of PublishCandidate.
func (mr *MockServiceMockRecorder) PublishCandidate(ctx, rulesetID, expectedBase, actorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishCandidate", reflect.TypeOf((*MockService)(nil).PublishCandidate), ctx, rulesetID, expectedBase, actorID)
}

// ReplaceRule mocks base method.
func (m *MockService) ReplaceRule(ctx context.Context, cmd moderationrule0.ReplaceRuleCommand) (moderationrule0.Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplaceRule", ctx, cmd)
	ret0, _ := ret[0].(moderationrule0.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReplaceRule indicates an expected call of ReplaceRule.
func (mr *MockServiceMockRecorder) ReplaceRule(ctx, cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplaceRule", reflect.TypeOf((*MockService)(nil).ReplaceRule), ctx, cmd)
}

// Status mocks base method.
func (m *MockService) Status(ctx context.Context) (moderationrule0.Status, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Status", ctx)
	ret0, _ := ret[0].(moderationrule0.Status)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Status indicates an expected call of Status.
func (mr *MockServiceMockRecorder) Status(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Status", reflect.TypeOf((*MockService)(nil).Status), ctx)
}

// TestText mocks base method.
func (m *MockService) TestText(ctx context.Context, cmd moderationrule0.TestTextCommand) (moderationrule0.TestResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TestText", ctx, cmd)
	ret0, _ := ret[0].(moderationrule0.TestResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TestText indicates an expected call of TestText.
func (mr *MockServiceMockRecorder) TestText(ctx, cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TestText", reflect.TypeOf((*MockService)(nil).TestText), ctx, cmd)
}

// MockWorker is a mock of Worker interface.
type MockWorker struct {
	ctrl     *gomock.Controller
	recorder *MockWorkerMockRecorder
	isgomock struct{}
}

// MockWorkerMockRecorder is the mock recorder for MockWorker.
type MockWorkerMockRecorder struct {
	mock *MockWorker
}

// NewMockWorker creates a new mock instance.
func NewMockWorker(ctrl *gomock.Controller) *MockWorker {
	mock := &MockWorker{ctrl: ctrl}
	mock.recorder = &MockWorkerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorker) EXPECT() *MockWorkerMockRecorder {
	return m.recorder
}

// ProcessOnce mocks base method.
func (m *MockWorker) ProcessOnce(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessOnce", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProcessOnce indicates an expected call of ProcessOnce.
func (mr *MockWorkerMockRecorder) ProcessOnce(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessOnce", reflect.TypeOf((*MockWorker)(nil).ProcessOnce), ctx)
}

// Run mocks base method.
func (m *MockWorker) Run(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Run", ctx)
}

// Run indicates an expected call of Run.
func (mr *MockWorkerMockRecorder) Run(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockWorker)(nil).Run), ctx)
}

// MockSnapshotReplacer is a mock of SnapshotReplacer interface.
type MockSnapshotReplacer struct {
	ctrl     *gomock.Controller
	recorder *MockSnapshotReplacerMockRecorder
	isgomock struct{}
}

// MockSnapshotReplacerMockRecorder is the mock recorder for MockSnapshotReplacer.
type MockSnapshotReplacerMockRecorder struct {
	mock *MockSnapshotReplacer
}

// NewMockSnapshotReplacer creates a new mock instance.
func NewMockSnapshotReplacer(ctrl *gomock.Controller) *MockSnapshotReplacer {
	mock := &MockSnapshotReplacer{ctrl: ctrl}
	mock.recorder = &MockSnapshotReplacerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSnapshotReplacer) EXPECT() *MockSnapshotReplacerMockRecorder {
	return m.recorder
}

// ReplaceSnapshot mocks base method.
func (m *MockSnapshotReplacer) ReplaceSnapshot(snapshot *ruleindex.Snapshot) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplaceSnapshot", snapshot)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReplaceSnapshot indicates an expected call of ReplaceSnapshot.
func (mr *MockSnapshotReplacerMockRecorder) ReplaceSnapshot(snapshot any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplaceSnapshot", reflect.TypeOf((*MockSnapshotReplacer)(nil).ReplaceSnapshot), snapshot)
}

// MockClassifierProvider is a mock of ClassifierProvider interface.
type MockClassifierProvider struct {
	ctrl     *gomock.Controller
	recorder *MockClassifierProviderMockRecorder
	isgomock struct{}
}

// MockClassifierProviderMockRecorder is the mock recorder for MockClassifierProvider.
type MockClassifierProviderMockRecorder struct {
	mock *MockClassifierProvider
}

// NewMockClassifierProvider creates a new mock instance.
func NewMockClassifierProvider(ctrl *gomock.Controller) *MockClassifierProvider {
	mock := &MockClassifierProvider{ctrl: ctrl}
	mock.recorder = &MockClassifierProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClassifierProvider) EXPECT() *MockClassifierProviderMockRecorder {
	return m.recorder
}

// Classifier mocks base method.
func (m *MockClassifierProvider) Classifier() moderationrule0.SnapshotReplacer {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Classifier")
	ret0, _ := ret[0].(moderationrule0.SnapshotReplacer)
	return ret0
}

// Classifier indicates an expected call of Classifier.
func (mr *MockClassifierProviderMockRecorder) Classifier() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Classifier", reflect.TypeOf((*MockClassifierProvider)(nil).Classifier))
}
