// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/moderationemail/service.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/moderationemail/service.go -destination=internal/service/moderationemail/mock/mock_service.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"
	time "time"

	moderationemail "github.com/vpt/blog-backend/internal/repository/moderationemail"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CreateBatch mocks base method.
func (m *MockRepository) CreateBatch(ctx context.Context, recipient moderationemail.AdminRecipient, limit int, now time.Time) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBatch", ctx, recipient, limit, now)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBatch indicates an expected call of CreateBatch.
func (mr *MockRepositoryMockRecorder) CreateBatch(ctx, recipient, limit, now any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBatch", reflect.TypeOf((*MockRepository)(nil).CreateBatch), ctx, recipient, limit, now)
}

// HasOpenBatch mocks base method.
func (m *MockRepository) HasOpenBatch(ctx context.Context) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasOpenBatch", ctx)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasOpenBatch indicates an expected call of HasOpenBatch.
func (mr *MockRepositoryMockRecorder) HasOpenBatch(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasOpenBatch", reflect.TypeOf((*MockRepository)(nil).HasOpenBatch), ctx)
}

// LastSuccessfulSend mocks base method.
func (m *MockRepository) LastSuccessfulSend(ctx context.Context) (*time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LastSuccessfulSend", ctx)
	ret0, _ := ret[0].(*time.Time)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LastSuccessfulSend indicates an expected call of LastSuccessfulSend.
func (mr *MockRepositoryMockRecorder) LastSuccessfulSend(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LastSuccessfulSend", reflect.TypeOf((*MockRepository)(nil).LastSuccessfulSend), ctx)
}

// OldestPendingTask mocks base method.
func (m *MockRepository) OldestPendingTask(ctx context.Context) (*moderationemail.PendingTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OldestPendingTask", ctx)
	ret0, _ := ret[0].(*moderationemail.PendingTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OldestPendingTask indicates an expected call of OldestPendingTask.
func (mr *MockRepositoryMockRecorder) OldestPendingTask(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OldestPendingTask", reflect.TypeOf((*MockRepository)(nil).OldestPendingTask), ctx)
}

// SkipStaleTasks mocks base method.
func (m *MockRepository) SkipStaleTasks(ctx context.Context, limit int, now time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SkipStaleTasks", ctx, limit, now)
	ret0, _ := ret[0].(error)
	return ret0
}

// SkipStaleTasks indicates an expected call of SkipStaleTasks.
func (mr *MockRepositoryMockRecorder) SkipStaleTasks(ctx, limit, now any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SkipStaleTasks", reflect.TypeOf((*MockRepository)(nil).SkipStaleTasks), ctx, limit, now)
}

// MockDirectory is a mock of Directory interface.
type MockDirectory struct {
	ctrl     *gomock.Controller
	recorder *MockDirectoryMockRecorder
	isgomock struct{}
}

// MockDirectoryMockRecorder is the mock recorder for MockDirectory.
type MockDirectoryMockRecorder struct {
	mock *MockDirectory
}

// NewMockDirectory creates a new mock instance.
func NewMockDirectory(ctrl *gomock.Controller) *MockDirectory {
	mock := &MockDirectory{ctrl: ctrl}
	mock.recorder = &MockDirectoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDirectory) EXPECT() *MockDirectoryMockRecorder {
	return m.recorder
}

// LoadAdminRecipient mocks base method.
func (m *MockDirectory) LoadAdminRecipient(ctx context.Context, userID uint) (moderationemail.AdminRecipient, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadAdminRecipient", ctx, userID)
	ret0, _ := ret[0].(moderationemail.AdminRecipient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadAdminRecipient indicates an expected call of LoadAdminRecipient.
func (mr *MockDirectoryMockRecorder) LoadAdminRecipient(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadAdminRecipient", reflect.TypeOf((*MockDirectory)(nil).LoadAdminRecipient), ctx, userID)
}
