// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vpt/blog-backend/internal/repository/moderationrule (interfaces: ManagementRepository)
//
// Generated by this command:
//
//	mockgen -destination=internal/repository/moderationrule/mock/mock_repository.go -package=mock github.com/vpt/blog-backend/internal/repository/moderationrule ManagementRepository
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	moderationrule "github.com/vpt/blog-backend/internal/repository/moderationrule"
	gomock "go.uber.org/mock/gomock"
)

// MockManagementRepository is a mock of ManagementRepository interface.
type MockManagementRepository struct {
	ctrl     *gomock.Controller
	recorder *MockManagementRepositoryMockRecorder
	isgomock struct{}
}

// MockManagementRepositoryMockRecorder is the mock recorder for MockManagementRepository.
type MockManagementRepositoryMockRecorder struct {
	mock *MockManagementRepository
}

// NewMockManagementRepository creates a new mock instance.
func NewMockManagementRepository(ctrl *gomock.Controller) *MockManagementRepository {
	mock := &MockManagementRepository{ctrl: ctrl}
	mock.recorder = &MockManagementRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockManagementRepository) EXPECT() *MockManagementRepositoryMockRecorder {
	return m.recorder
}

// CurrentRuleset mocks base method.
func (m *MockManagementRepository) CurrentRuleset(ctx context.Context) (moderationrule.RulesetRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CurrentRuleset", ctx)
	ret0, _ := ret[0].(moderationrule.RulesetRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CurrentRuleset indicates an expected call of CurrentRuleset.
func (mr *MockManagementRepositoryMockRecorder) CurrentRuleset(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CurrentRuleset", reflect.TypeOf((*MockManagementRepository)(nil).CurrentRuleset), ctx)
}

// CurrentStatus mocks base method.
func (m *MockManagementRepository) CurrentStatus(ctx context.Context) (moderationrule.StatusRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CurrentStatus", ctx)
	ret0, _ := ret[0].(moderationrule.StatusRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CurrentStatus indicates an expected call of CurrentStatus.
func (mr *MockManagementRepositoryMockRecorder) CurrentStatus(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CurrentStatus", reflect.TypeOf((*MockManagementRepository)(nil).CurrentStatus), ctx)
}

// EnsureSource mocks base method.
func (m *MockManagementRepository) EnsureSource(ctx context.Context, name string) (moderationrule.SourceRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureSource", ctx, name)
	ret0, _ := ret[0].(moderationrule.SourceRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EnsureSource indicates an expected call of EnsureSource.
func (mr *MockManagementRepositoryMockRecorder) EnsureSource(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureSource", reflect.TypeOf((*MockManagementRepository)(nil).EnsureSource), ctx, name)
}

// FindDuplicateHashes mocks base method.
func (m *MockManagementRepository) FindDuplicateHashes(ctx context.Context, currentRulesetID uint64, hashes []moderationrule.DedupeHash) (map[moderationrule.DedupeHash]uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindDuplicateHashes", ctx, currentRulesetID, hashes)
	ret0, _ := ret[0].(map[moderationrule.DedupeHash]uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindDuplicateHashes indicates an expected call of FindDuplicateHashes.
func (mr *MockManagementRepositoryMockRecorder) FindDuplicateHashes(ctx, currentRulesetID, hashes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindDuplicateHashes", reflect.TypeOf((*MockManagementRepository)(nil).FindDuplicateHashes), ctx, currentRulesetID, hashes)
}

// ListRules mocks base method.
func (m *MockManagementRepository) ListRules(ctx context.Context, filter moderationrule.RuleFilter) (moderationrule.RulePage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRules", ctx, filter)
	ret0, _ := ret[0].(moderationrule.RulePage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRules indicates an expected call of ListRules.
func (mr *MockManagementRepositoryMockRecorder) ListRules(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRules", reflect.TypeOf((*MockManagementRepository)(nil).ListRules), ctx, filter)
}

// ListSources mocks base method.
func (m *MockManagementRepository) ListSources(ctx context.Context) ([]moderationrule.SourceRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSources", ctx)
	ret0, _ := ret[0].([]moderationrule.SourceRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSources indicates an expected call of ListSources.
func (mr *MockManagementRepositoryMockRecorder) ListSources(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSources", reflect.TypeOf((*MockManagementRepository)(nil).ListSources), ctx)
}

// StreamRules mocks base method.
func (m *MockManagementRepository) StreamRules(ctx context.Context, version uint64, visit func(moderationrule.RuleRecord) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StreamRules", ctx, version, visit)
	ret0, _ := ret[0].(error)
	return ret0
}

// StreamRules indicates an expected call of StreamRules.
func (mr *MockManagementRepositoryMockRecorder) StreamRules(ctx, version, visit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StreamRules", reflect.TypeOf((*MockManagementRepository)(nil).StreamRules), ctx, version, visit)
}
