// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vpt/blog-backend/internal/repository/moderationrule (interfaces: ManagementRepository)
//
// Generated by this command:
//
//	mockgen -destination=internal/repository/moderationrule/mock/mock_repository.go -package=mock github.com/vpt/blog-backend/internal/repository/moderationrule ManagementRepository
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	moderationrule "github.com/vpt/blog-backend/internal/repository/moderationrule"
	gomock "go.uber.org/mock/gomock"
)

// MockManagementRepository is a mock of ManagementRepository interface.
type MockManagementRepository struct {
	ctrl     *gomock.Controller
	recorder *MockManagementRepositoryMockRecorder
	isgomock struct{}
}

// MockManagementRepositoryMockRecorder is the mock recorder for MockManagementRepository.
type MockManagementRepositoryMockRecorder struct {
	mock *MockManagementRepository
}

// NewMockManagementRepository creates a new mock instance.
func NewMockManagementRepository(ctrl *gomock.Controller) *MockManagementRepository {
	mock := &MockManagementRepository{ctrl: ctrl}
	mock.recorder = &MockManagementRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockManagementRepository) EXPECT() *MockManagementRepositoryMockRecorder {
	return m.recorder
}

// CancelCandidate mocks base method.
func (m *MockManagementRepository) CancelCandidate(ctx context.Context, id, actorID uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelCandidate", ctx, id, actorID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CancelCandidate indicates an expected call of CancelCandidate.
func (mr *MockManagementRepositoryMockRecorder) CancelCandidate(ctx, id, actorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelCandidate", reflect.TypeOf((*MockManagementRepository)(nil).CancelCandidate), ctx, id, actorID)
}

// ClaimNextRuleset mocks base method.
func (m *MockManagementRepository) ClaimNextRuleset(ctx context.Context, status string) (*moderationrule.CandidateRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClaimNextRuleset", ctx, status)
	ret0, _ := ret[0].(*moderationrule.CandidateRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClaimNextRuleset indicates an expected call of ClaimNextRuleset.
func (mr *MockManagementRepositoryMockRecorder) ClaimNextRuleset(ctx, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClaimNextRuleset", reflect.TypeOf((*MockManagementRepository)(nil).ClaimNextRuleset), ctx, status)
}

// CreateCandidate mocks base method.
func (m *MockManagementRepository) CreateCandidate(ctx context.Context, cmd moderationrule.CreateCandidateCommand) (moderationrule.CandidateRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCandidate", ctx, cmd)
	ret0, _ := ret[0].(moderationrule.CandidateRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCandidate indicates an expected call of CreateCandidate.
func (mr *MockManagementRepositoryMockRecorder) CreateCandidate(ctx, cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCandidate", reflect.TypeOf((*MockManagementRepository)(nil).CreateCandidate), ctx, cmd)
}

// CurrentRuleset mocks base method.
func (m *MockManagementRepository) CurrentRuleset(ctx context.Context) (moderationrule.RulesetRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CurrentRuleset", ctx)
	ret0, _ := ret[0].(moderationrule.RulesetRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CurrentRuleset indicates an expected call of CurrentRuleset.
func (mr *MockManagementRepositoryMockRecorder) CurrentRuleset(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CurrentRuleset", reflect.TypeOf((*MockManagementRepository)(nil).CurrentRuleset), ctx)
}

// CurrentStatus mocks base method.
func (m *MockManagementRepository) CurrentStatus(ctx context.Context) (moderationrule.StatusRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CurrentStatus", ctx)
	ret0, _ := ret[0].(moderationrule.StatusRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CurrentStatus indicates an expected call of CurrentStatus.
func (mr *MockManagementRepositoryMockRecorder) CurrentStatus(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CurrentStatus", reflect.TypeOf((*MockManagementRepository)(nil).CurrentStatus), ctx)
}

// EnsureSource mocks base method.
func (m *MockManagementRepository) EnsureSource(ctx context.Context, name string) (moderationrule.SourceRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureSource", ctx, name)
	ret0, _ := ret[0].(moderationrule.SourceRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EnsureSource indicates an expected call of EnsureSource.
func (mr *MockManagementRepositoryMockRecorder) EnsureSource(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureSource", reflect.TypeOf((*MockManagementRepository)(nil).EnsureSource), ctx, name)
}

// FailRuleset mocks base method.
func (m *MockManagementRepository) FailRuleset(ctx context.Context, id uint64, failureCode string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FailRuleset", ctx, id, failureCode)
	ret0, _ := ret[0].(error)
	return ret0
}

// FailRuleset indicates an expected call of FailRuleset.
func (mr *MockManagementRepositoryMockRecorder) FailRuleset(ctx, id, failureCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FailRuleset", reflect.TypeOf((*MockManagementRepository)(nil).FailRuleset), ctx, id, failureCode)
}

// FindDuplicateHashes mocks base method.
func (m *MockManagementRepository) FindDuplicateHashes(ctx context.Context, currentRulesetID uint64, hashes []moderationrule.DedupeHash) (map[moderationrule.DedupeHash]uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindDuplicateHashes", ctx, currentRulesetID, hashes)
	ret0, _ := ret[0].(map[moderationrule.DedupeHash]uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindDuplicateHashes indicates an expected call of FindDuplicateHashes.
func (mr *MockManagementRepositoryMockRecorder) FindDuplicateHashes(ctx, currentRulesetID, hashes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindDuplicateHashes", reflect.TypeOf((*MockManagementRepository)(nil).FindDuplicateHashes), ctx, currentRulesetID, hashes)
}

// GetCandidate mocks base method.
func (m *MockManagementRepository) GetCandidate(ctx context.Context, id uint64) (moderationrule.CandidateRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCandidate", ctx, id)
	ret0, _ := ret[0].(moderationrule.CandidateRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCandidate indicates an expected call of GetCandidate.
func (mr *MockManagementRepositoryMockRecorder) GetCandidate(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCandidate", reflect.TypeOf((*MockManagementRepository)(nil).GetCandidate), ctx, id)
}

// GetRulesByIDs mocks base method.
func (m *MockManagementRepository) GetRulesByIDs(ctx context.Context, ids []uint64) ([]moderationrule.RuleListRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRulesByIDs", ctx, ids)
	ret0, _ := ret[0].([]moderationrule.RuleListRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRulesByIDs indicates an expected call of GetRulesByIDs.
func (mr *MockManagementRepositoryMockRecorder) GetRulesByIDs(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRulesByIDs", reflect.TypeOf((*MockManagementRepository)(nil).GetRulesByIDs), ctx, ids)
}

// GetRulesetRemovals mocks base method.
func (m *MockManagementRepository) GetRulesetRemovals(ctx context.Context, rulesetID uint64) ([]uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRulesetRemovals", ctx, rulesetID)
	ret0, _ := ret[0].([]uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRulesetRemovals indicates an expected call of GetRulesetRemovals.
func (mr *MockManagementRepositoryMockRecorder) GetRulesetRemovals(ctx, rulesetID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRulesetRemovals", reflect.TypeOf((*MockManagementRepository)(nil).GetRulesetRemovals), ctx, rulesetID)
}

// HasImportForRuleset mocks base method.
func (m *MockManagementRepository) HasImportForRuleset(ctx context.Context, rulesetID uint64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasImportForRuleset", ctx, rulesetID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasImportForRuleset indicates an expected call of HasImportForRuleset.
func (mr *MockManagementRepositoryMockRecorder) HasImportForRuleset(ctx, rulesetID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasImportForRuleset", reflect.TypeOf((*MockManagementRepository)(nil).HasImportForRuleset), ctx, rulesetID)
}

// ListRules mocks base method.
func (m *MockManagementRepository) ListRules(ctx context.Context, filter moderationrule.RuleFilter) (moderationrule.RulePage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRules", ctx, filter)
	ret0, _ := ret[0].(moderationrule.RulePage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRules indicates an expected call of ListRules.
func (mr *MockManagementRepositoryMockRecorder) ListRules(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRules", reflect.TypeOf((*MockManagementRepository)(nil).ListRules), ctx, filter)
}

// ListSources mocks base method.
func (m *MockManagementRepository) ListSources(ctx context.Context) ([]moderationrule.SourceRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSources", ctx)
	ret0, _ := ret[0].([]moderationrule.SourceRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSources indicates an expected call of ListSources.
func (mr *MockManagementRepositoryMockRecorder) ListSources(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSources", reflect.TypeOf((*MockManagementRepository)(nil).ListSources), ctx)
}

// PublishCandidate mocks base method.
func (m *MockManagementRepository) PublishCandidate(ctx context.Context, id, expectedBase uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishCandidate", ctx, id, expectedBase)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishCandidate indicates an expected call of PublishCandidate.
func (mr *MockManagementRepositoryMockRecorder) PublishCandidate(ctx, id, expectedBase any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishCandidate", reflect.TypeOf((*MockManagementRepository)(nil).PublishCandidate), ctx, id, expectedBase)
}

// SaveRulesetBuildResult mocks base method.
func (m *MockManagementRepository) SaveRulesetBuildResult(ctx context.Context, id uint64, result moderationrule.BuildResult) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveRulesetBuildResult", ctx, id, result)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveRulesetBuildResult indicates an expected call of SaveRulesetBuildResult.
func (mr *MockManagementRepositoryMockRecorder) SaveRulesetBuildResult(ctx, id, result any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveRulesetBuildResult", reflect.TypeOf((*MockManagementRepository)(nil).SaveRulesetBuildResult), ctx, id, result)
}

// StreamCandidateRules mocks base method.
func (m *MockManagementRepository) StreamCandidateRules(ctx context.Context, baseVersion, candidateID uint64, visit func(moderationrule.RuleRecord) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StreamCandidateRules", ctx, baseVersion, candidateID, visit)
	ret0, _ := ret[0].(error)
	return ret0
}

// StreamCandidateRules indicates an expected call of StreamCandidateRules.
func (mr *MockManagementRepositoryMockRecorder) StreamCandidateRules(ctx, baseVersion, candidateID, visit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StreamCandidateRules", reflect.TypeOf((*MockManagementRepository)(nil).StreamCandidateRules), ctx, baseVersion, candidateID, visit)
}

// StreamRules mocks base method.
func (m *MockManagementRepository) StreamRules(ctx context.Context, version uint64, visit func(moderationrule.RuleRecord) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StreamRules", ctx, version, visit)
	ret0, _ := ret[0].(error)
	return ret0
}

// StreamRules indicates an expected call of StreamRules.
func (mr *MockManagementRepositoryMockRecorder) StreamRules(ctx, version, visit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StreamRules", reflect.TypeOf((*MockManagementRepository)(nil).StreamRules), ctx, version, visit)
}
