-- 数据库中文注释迁移：补齐现有表与列的中文注释，生产库与开发库共用同一份 SQL。
ALTER TABLE `analytics_daily` COMMENT = '每日站点访问汇总表';
ALTER TABLE `analytics_daily` MODIFY COLUMN `anonymous_pv` bigint NULL DEFAULT NULL COMMENT '匿名用户页面浏览量';
ALTER TABLE `analytics_daily` MODIFY COLUMN `anonymous_uv` bigint NULL DEFAULT NULL COMMENT '匿名用户独立访客数';
ALTER TABLE `analytics_daily` MODIFY COLUMN `avg_duration` bigint NULL DEFAULT NULL COMMENT '平均会话时长秒数';
ALTER TABLE `analytics_daily` MODIFY COLUMN `bounce_rate` double NULL DEFAULT NULL COMMENT '跳出率';
ALTER TABLE `analytics_daily` MODIFY COLUMN `date` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '统计日期';
ALTER TABLE `analytics_daily` MODIFY COLUMN `new_visitors` bigint NULL DEFAULT NULL COMMENT '新访客数';
ALTER TABLE `analytics_daily` MODIFY COLUMN `pv` bigint NULL DEFAULT NULL COMMENT '页面浏览量';
ALTER TABLE `analytics_daily` MODIFY COLUMN `registered_pv` bigint NULL DEFAULT NULL COMMENT '注册用户页面浏览量';
ALTER TABLE `analytics_daily` MODIFY COLUMN `registered_uv` bigint NULL DEFAULT NULL COMMENT '注册用户独立访客数';
ALTER TABLE `analytics_daily` MODIFY COLUMN `sessions` bigint NULL DEFAULT NULL COMMENT '会话数';
ALTER TABLE `analytics_daily` MODIFY COLUMN `uv` bigint NULL DEFAULT NULL COMMENT '独立访客数';
ALTER TABLE `analytics_daily_dim` COMMENT = '每日访问维度汇总表';
ALTER TABLE `analytics_daily_dim` MODIFY COLUMN `date` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '统计日期';
ALTER TABLE `analytics_daily_dim` MODIFY COLUMN `dim_value` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '维度值';
ALTER TABLE `analytics_daily_dim` MODIFY COLUMN `dimension` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '统计维度';
ALTER TABLE `analytics_daily_dim` MODIFY COLUMN `pv` bigint NULL DEFAULT NULL COMMENT '页面浏览量';
ALTER TABLE `analytics_daily_dim` MODIFY COLUMN `uv` bigint NULL DEFAULT NULL COMMENT '独立访客数';
ALTER TABLE `analytics_events` COMMENT = '访问分析原始事件表';
ALTER TABLE `analytics_events` MODIFY COLUMN `bot_reason` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '机器人判定原因';
ALTER TABLE `analytics_events` MODIFY COLUMN `browser` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '浏览器';
ALTER TABLE `analytics_events` MODIFY COLUMN `city` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '城市';
ALTER TABLE `analytics_events` MODIFY COLUMN `country` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '国家';
ALTER TABLE `analytics_events` MODIFY COLUMN `country_code` varchar(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '国家代码';
ALTER TABLE `analytics_events` MODIFY COLUMN `created_at` datetime(3) NULL DEFAULT NULL COMMENT '创建时间';
ALTER TABLE `analytics_events` MODIFY COLUMN `device_type` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '设备类型';
ALTER TABLE `analytics_events` MODIFY COLUMN `event_type` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '事件类型';
ALTER TABLE `analytics_events` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE `analytics_events` MODIFY COLUMN `ip_hash` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT 'IP哈希';
ALTER TABLE `analytics_events` MODIFY COLUMN `is_authenticated` tinyint(1) NULL DEFAULT NULL COMMENT '是否已登录';
ALTER TABLE `analytics_events` MODIFY COLUMN `is_bot` tinyint(1) NULL DEFAULT NULL COMMENT '是否机器人访问';
ALTER TABLE `analytics_events` MODIFY COLUMN `is_new_visitor` tinyint(1) NULL DEFAULT NULL COMMENT '是否新访客';
ALTER TABLE `analytics_events` MODIFY COLUMN `is_suspect` tinyint(1) NULL DEFAULT NULL COMMENT '是否可疑访问';
ALTER TABLE `analytics_events` MODIFY COLUMN `isp` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '网络运营商';
ALTER TABLE `analytics_events` MODIFY COLUMN `os` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '操作系统';
ALTER TABLE `analytics_events` MODIFY COLUMN `path` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '访问路径';
ALTER TABLE `analytics_events` MODIFY COLUMN `referer_host` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '来源域名';
ALTER TABLE `analytics_events` MODIFY COLUMN `referer_type` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '来源类型';
ALTER TABLE `analytics_events` MODIFY COLUMN `region` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '地区';
ALTER TABLE `analytics_events` MODIFY COLUMN `session_id` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '会话ID';
ALTER TABLE `analytics_events` MODIFY COLUMN `suspect_reason` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '可疑访问原因';
ALTER TABLE `analytics_events` MODIFY COLUMN `title` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '页面标题';
ALTER TABLE `analytics_events` MODIFY COLUMN `user_id` bigint unsigned NULL DEFAULT NULL COMMENT '登录用户ID';
ALTER TABLE `analytics_events` MODIFY COLUMN `visitor_id` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '访客ID';
ALTER TABLE `analytics_friend_link_daily` COMMENT = '每日友链来源访问汇总表';
ALTER TABLE `analytics_friend_link_daily` MODIFY COLUMN `date` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '统计日期';
ALTER TABLE `analytics_friend_link_daily` MODIFY COLUMN `friend_link_id` bigint unsigned NOT NULL COMMENT '友链ID';
ALTER TABLE `analytics_friend_link_daily` MODIFY COLUMN `friend_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '友链名称';
ALTER TABLE `analytics_friend_link_daily` MODIFY COLUMN `pv` bigint NULL DEFAULT NULL COMMENT '页面浏览量';
ALTER TABLE `analytics_friend_link_daily` MODIFY COLUMN `sessions` bigint NULL DEFAULT NULL COMMENT '会话数';
ALTER TABLE `analytics_friend_link_daily` MODIFY COLUMN `site` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '友链URL';
ALTER TABLE `analytics_friend_link_daily` MODIFY COLUMN `site_host` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '友链域名';
ALTER TABLE `analytics_friend_link_daily` MODIFY COLUMN `uv` bigint NULL DEFAULT NULL COMMENT '独立访客数';
ALTER TABLE `analytics_page_daily` COMMENT = '每日页面访问汇总表';
ALTER TABLE `analytics_page_daily` MODIFY COLUMN `date` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '统计日期';
ALTER TABLE `analytics_page_daily` MODIFY COLUMN `path` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '访问路径';
ALTER TABLE `analytics_page_daily` MODIFY COLUMN `pv` bigint NULL DEFAULT NULL COMMENT '页面浏览量';
ALTER TABLE `analytics_page_daily` MODIFY COLUMN `title` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '页面标题';
ALTER TABLE `analytics_page_daily` MODIFY COLUMN `uv` bigint NULL DEFAULT NULL COMMENT '独立访客数';
ALTER TABLE `analytics_sessions` COMMENT = '访问分析会话表';
ALTER TABLE `analytics_sessions` MODIFY COLUMN `browser` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '浏览器';
ALTER TABLE `analytics_sessions` MODIFY COLUMN `city` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '城市';
ALTER TABLE `analytics_sessions` MODIFY COLUMN `country` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '国家';
ALTER TABLE `analytics_sessions` MODIFY COLUMN `country_code` varchar(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '国家代码';
ALTER TABLE `analytics_sessions` MODIFY COLUMN `device_type` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '设备类型';
ALTER TABLE `analytics_sessions` MODIFY COLUMN `duration` bigint NULL DEFAULT NULL COMMENT '会话时长秒数';
ALTER TABLE `analytics_sessions` MODIFY COLUMN `entry_path` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '入口路径';
ALTER TABLE `analytics_sessions` MODIFY COLUMN `exit_path` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '退出路径';
ALTER TABLE `analytics_sessions` MODIFY COLUMN `first_seen` datetime(3) NULL DEFAULT NULL COMMENT '首次访问时间';
ALTER TABLE `analytics_sessions` MODIFY COLUMN `is_authenticated` tinyint(1) NULL DEFAULT NULL COMMENT '是否已登录';
ALTER TABLE `analytics_sessions` MODIFY COLUMN `is_bot` tinyint(1) NULL DEFAULT NULL COMMENT '是否机器人访问';
ALTER TABLE `analytics_sessions` MODIFY COLUMN `is_bounce` tinyint(1) NULL DEFAULT NULL COMMENT '是否跳出会话';
ALTER TABLE `analytics_sessions` MODIFY COLUMN `is_suspect` tinyint(1) NULL DEFAULT NULL COMMENT '是否可疑访问';
ALTER TABLE `analytics_sessions` MODIFY COLUMN `isp` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '网络运营商';
ALTER TABLE `analytics_sessions` MODIFY COLUMN `last_seen` datetime(3) NULL DEFAULT NULL COMMENT '最后访问时间';
ALTER TABLE `analytics_sessions` MODIFY COLUMN `os` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '操作系统';
ALTER TABLE `analytics_sessions` MODIFY COLUMN `pv_count` bigint NULL DEFAULT NULL COMMENT '页面浏览次数';
ALTER TABLE `analytics_sessions` MODIFY COLUMN `referer_type` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '来源类型';
ALTER TABLE `analytics_sessions` MODIFY COLUMN `region` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '地区';
ALTER TABLE `analytics_sessions` MODIFY COLUMN `session_id` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '会话ID';
ALTER TABLE `analytics_sessions` MODIFY COLUMN `user_id` bigint unsigned NULL DEFAULT NULL COMMENT '登录用户ID';
ALTER TABLE `analytics_sessions` MODIFY COLUMN `visitor_id` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '访客ID';
ALTER TABLE `article` COMMENT = '文章表';
ALTER TABLE `article` MODIFY COLUMN `comment_status` tinyint NULL DEFAULT 1 COMMENT '评论开关状态';
ALTER TABLE `article` MODIFY COLUMN `content` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '文章正文';
ALTER TABLE `article` MODIFY COLUMN `content_ai_referenced` tinyint(1) NULL DEFAULT 0 COMMENT '正文是否参考AI';
ALTER TABLE `article` MODIFY COLUMN `cover_ai_generated` tinyint(1) NULL DEFAULT 0 COMMENT '封面是否AI生成';
ALTER TABLE `article` MODIFY COLUMN `cover_img_url` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '封面图URL';
ALTER TABLE `article` MODIFY COLUMN `created_at` datetime(3) NULL DEFAULT NULL COMMENT '创建时间';
ALTER TABLE `article` MODIFY COLUMN `deleted_at` datetime(3) NULL DEFAULT NULL COMMENT '软删除时间';
ALTER TABLE `article` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE `article` MODIFY COLUMN `mobile_cover_img_url` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '移动端封面图URL';
ALTER TABLE `article` MODIFY COLUMN `password` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '阅读密码';
ALTER TABLE `article` MODIFY COLUMN `read_count` bigint NULL DEFAULT 0 COMMENT '阅读次数';
ALTER TABLE `article` MODIFY COLUMN `short_content` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '文章摘要';
ALTER TABLE `article` MODIFY COLUMN `status` tinyint NULL DEFAULT 1 COMMENT '文章状态';
ALTER TABLE `article` MODIFY COLUMN `title` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '文章标题';
ALTER TABLE `article` MODIFY COLUMN `updated_at` datetime(3) NULL DEFAULT NULL COMMENT '更新时间';
ALTER TABLE `article` MODIFY COLUMN `user_id` bigint unsigned NOT NULL COMMENT '作者用户ID';
ALTER TABLE `article_ai_model` COMMENT = '文章AI模型披露表';
ALTER TABLE `article_ai_model` MODIFY COLUMN `article_id` bigint unsigned NOT NULL COMMENT '文章ID';
ALTER TABLE `article_ai_model` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE `article_ai_model` MODIFY COLUMN `model_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT 'AI模型名称';
ALTER TABLE `article_ai_model` MODIFY COLUMN `scope` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT 'AI使用场景';
ALTER TABLE `article_ai_model` MODIFY COLUMN `seq` bigint NULL DEFAULT 0 COMMENT '展示排序';
ALTER TABLE `article_category` COMMENT = '文章分类关联表';
ALTER TABLE `article_category` MODIFY COLUMN `article_id` bigint unsigned NOT NULL COMMENT '文章ID';
ALTER TABLE `article_category` MODIFY COLUMN `category_id` bigint unsigned NOT NULL COMMENT '分类ID';
ALTER TABLE `article_category` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE `article_comment` COMMENT = '文章评论表';
ALTER TABLE `article_comment` MODIFY COLUMN `article_id` bigint unsigned NOT NULL COMMENT '文章ID';
ALTER TABLE `article_comment` MODIFY COLUMN `content` varchar(2000) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '评论内容';
ALTER TABLE `article_comment` MODIFY COLUMN `created_at` datetime(3) NULL DEFAULT NULL COMMENT '创建时间';
ALTER TABLE `article_comment` MODIFY COLUMN `deleted_at` datetime(3) NULL DEFAULT NULL COMMENT '软删除时间';
ALTER TABLE `article_comment` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE `article_comment` MODIFY COLUMN `updated_at` datetime(3) NULL DEFAULT NULL COMMENT '更新时间';
ALTER TABLE `article_comment` MODIFY COLUMN `user_id` bigint unsigned NOT NULL COMMENT '评论者用户ID';
ALTER TABLE `article_comment_reply` COMMENT = '文章评论回复表';
ALTER TABLE `article_comment_reply` MODIFY COLUMN `comment_id` bigint unsigned NOT NULL COMMENT '所属文章评论ID';
ALTER TABLE `article_comment_reply` MODIFY COLUMN `content` varchar(2000) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '回复内容';
ALTER TABLE `article_comment_reply` MODIFY COLUMN `created_at` datetime(3) NULL DEFAULT NULL COMMENT '创建时间';
ALTER TABLE `article_comment_reply` MODIFY COLUMN `deleted_at` datetime(3) NULL DEFAULT NULL COMMENT '软删除时间';
ALTER TABLE `article_comment_reply` MODIFY COLUMN `from_user_id` bigint unsigned NOT NULL COMMENT '回复者用户ID';
ALTER TABLE `article_comment_reply` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE `article_comment_reply` MODIFY COLUMN `parent_reply_id` bigint unsigned NULL DEFAULT 0 COMMENT '上级回复ID';
ALTER TABLE `article_comment_reply` MODIFY COLUMN `to_user_id` bigint unsigned NOT NULL COMMENT '被回复者用户ID';
ALTER TABLE `article_comment_reply` MODIFY COLUMN `updated_at` datetime(3) NULL DEFAULT NULL COMMENT '更新时间';
ALTER TABLE `article_music` COMMENT = '文章音乐关联表';
ALTER TABLE `article_music` MODIFY COLUMN `article_id` bigint unsigned NOT NULL COMMENT '文章ID';
ALTER TABLE `article_music` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE `article_music` MODIFY COLUMN `music_id` bigint unsigned NOT NULL COMMENT '音乐ID';
ALTER TABLE `article_recommend` COMMENT = '文章推荐表';
ALTER TABLE `article_recommend` MODIFY COLUMN `article_id` bigint unsigned NOT NULL COMMENT '文章ID';
ALTER TABLE `article_recommend` MODIFY COLUMN `created_at` datetime(3) NULL DEFAULT NULL COMMENT '创建时间';
ALTER TABLE `article_recommend` MODIFY COLUMN `deleted_at` datetime(3) NULL DEFAULT NULL COMMENT '软删除时间';
ALTER TABLE `article_recommend` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE `article_recommend` MODIFY COLUMN `seq` bigint NULL DEFAULT 0 COMMENT '推荐排序';
ALTER TABLE `article_recommend` MODIFY COLUMN `updated_at` datetime(3) NULL DEFAULT NULL COMMENT '更新时间';
ALTER TABLE `article_tag` COMMENT = '文章标签关联表';
ALTER TABLE `article_tag` MODIFY COLUMN `article_id` bigint unsigned NOT NULL COMMENT '文章ID';
ALTER TABLE `article_tag` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE `article_tag` MODIFY COLUMN `seq` bigint NOT NULL COMMENT '展示排序';
ALTER TABLE `article_tag` MODIFY COLUMN `tag_id` bigint unsigned NOT NULL COMMENT '标签ID';
ALTER TABLE `category` COMMENT = '分类表';
ALTER TABLE `category` MODIFY COLUMN `cover_img_url` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '分类封面图URL';
ALTER TABLE `category` MODIFY COLUMN `created_at` datetime(3) NULL DEFAULT NULL COMMENT '创建时间';
ALTER TABLE `category` MODIFY COLUMN `deleted_at` datetime(3) NULL DEFAULT NULL COMMENT '软删除时间';
ALTER TABLE `category` MODIFY COLUMN `description` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '分类描述';
ALTER TABLE `category` MODIFY COLUMN `icon` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '分类图标URL';
ALTER TABLE `category` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE `category` MODIFY COLUMN `name` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '分类名称';
ALTER TABLE `category` MODIFY COLUMN `parent_id` bigint unsigned NULL DEFAULT NULL COMMENT '父分类ID';
ALTER TABLE `category` MODIFY COLUMN `seq` bigint NULL DEFAULT 0 COMMENT '展示排序';
ALTER TABLE `category` MODIFY COLUMN `updated_at` datetime(3) NULL DEFAULT NULL COMMENT '更新时间';
ALTER TABLE `category` MODIFY COLUMN `url` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '分类路由别名';
ALTER TABLE `email_quota_policy` COMMENT = '邮件用途额度策略表';
ALTER TABLE `email_quota_policy` MODIFY COLUMN `daily_limit` bigint NOT NULL DEFAULT 0 COMMENT '每日上限';
ALTER TABLE `email_quota_policy` MODIFY COLUMN `enabled` tinyint NOT NULL DEFAULT 1 COMMENT '是否启用';
ALTER TABLE `email_quota_policy` MODIFY COLUMN `max_per_hour` bigint NOT NULL DEFAULT 0 COMMENT '每小时上限';
ALTER TABLE `email_quota_policy` MODIFY COLUMN `max_per_minute` bigint NOT NULL DEFAULT 0 COMMENT '每分钟上限';
ALTER TABLE `email_quota_policy` MODIFY COLUMN `priority` bigint NOT NULL DEFAULT 0 COMMENT '全局优先级';
ALTER TABLE `email_quota_policy` MODIFY COLUMN `purpose` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '邮件用途';
ALTER TABLE `email_quota_policy` MODIFY COLUMN `reserved_min` bigint NOT NULL DEFAULT 0 COMMENT '每日保底份额';
ALTER TABLE `email_quota_usage` COMMENT = '邮件额度使用量表';
ALTER TABLE `email_quota_usage` MODIFY COLUMN `purpose` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '邮件用途';
ALTER TABLE `email_quota_usage` MODIFY COLUMN `quota_date` date NOT NULL COMMENT '统计日期';
ALTER TABLE `email_quota_usage` MODIFY COLUMN `scope_id` bigint unsigned NOT NULL DEFAULT 0 COMMENT '限额对象ID';
ALTER TABLE `email_quota_usage` MODIFY COLUMN `scope_type` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '限额维度';
ALTER TABLE `email_quota_usage` MODIFY COLUMN `used_count` bigint NOT NULL DEFAULT 0 COMMENT '已用数量';
ALTER TABLE `email_quota_usage` MODIFY COLUMN `window_start` datetime(3) NOT NULL COMMENT '统计窗口开始时间';
ALTER TABLE `email_quota_usage` MODIFY COLUMN `window_type` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '统计窗口类型';
ALTER TABLE `email_role_quota_policy` COMMENT = '邮件角色额度策略表';
ALTER TABLE `email_role_quota_policy` MODIFY COLUMN `daily_limit` bigint NOT NULL DEFAULT 0 COMMENT '每日上限';
ALTER TABLE `email_role_quota_policy` MODIFY COLUMN `enabled` tinyint NOT NULL DEFAULT 1 COMMENT '是否启用';
ALTER TABLE `email_role_quota_policy` MODIFY COLUMN `max_per_hour` bigint NOT NULL DEFAULT 0 COMMENT '每小时上限';
ALTER TABLE `email_role_quota_policy` MODIFY COLUMN `role` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '角色标识';
ALTER TABLE `email_role_quota_policy` MODIFY COLUMN `scope_type` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '限额维度';
ALTER TABLE `email_send_log` COMMENT = '邮件发送日志表';
ALTER TABLE `email_send_log` MODIFY COLUMN `batch_id` bigint unsigned NULL DEFAULT NULL COMMENT '通知邮件批次ID';
ALTER TABLE `email_send_log` MODIFY COLUMN `created_at` datetime(3) NULL DEFAULT NULL COMMENT '创建时间';
ALTER TABLE `email_send_log` MODIFY COLUMN `error` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '发送错误';
ALTER TABLE `email_send_log` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE `email_send_log` MODIFY COLUMN `message_id` varchar(120) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '邮件Message-ID';
ALTER TABLE `email_send_log` MODIFY COLUMN `provider` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '邮件供应商';
ALTER TABLE `email_send_log` MODIFY COLUMN `purpose` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '邮件用途';
ALTER TABLE `email_send_log` MODIFY COLUMN `status` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '发送结果';
ALTER TABLE `email_send_log` MODIFY COLUMN `to_email` varchar(155) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '收件邮箱';
ALTER TABLE `friend_link` COMMENT = '友链表';
ALTER TABLE `friend_link` MODIFY COLUMN `avatar_url` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '网站头像或Logo';
ALTER TABLE `friend_link` MODIFY COLUMN `created_at` datetime(3) NULL DEFAULT NULL COMMENT '创建时间';
ALTER TABLE `friend_link` MODIFY COLUMN `deleted_at` datetime(3) NULL DEFAULT NULL COMMENT '软删除时间';
ALTER TABLE `friend_link` MODIFY COLUMN `description` varchar(150) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '网站描述';
ALTER TABLE `friend_link` MODIFY COLUMN `email` varchar(155) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '站长邮箱';
ALTER TABLE `friend_link` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE `friend_link` MODIFY COLUMN `name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '网站名称';
ALTER TABLE `friend_link` MODIFY COLUMN `phone` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '联系电话';
ALTER TABLE `friend_link` MODIFY COLUMN `seq` bigint NULL DEFAULT 0 COMMENT '展示排序';
ALTER TABLE `friend_link` MODIFY COLUMN `site` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '网站URL';
ALTER TABLE `friend_link` MODIFY COLUMN `status` tinyint NULL DEFAULT 1 COMMENT '友链状态';
ALTER TABLE `friend_link` MODIFY COLUMN `updated_at` datetime(3) NULL DEFAULT NULL COMMENT '更新时间';
ALTER TABLE `guestbook` COMMENT = '留言表';
ALTER TABLE `guestbook` MODIFY COLUMN `content` varchar(2000) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '留言内容';
ALTER TABLE `guestbook` MODIFY COLUMN `created_at` datetime(3) NULL DEFAULT NULL COMMENT '创建时间';
ALTER TABLE `guestbook` MODIFY COLUMN `deleted_at` datetime(3) NULL DEFAULT NULL COMMENT '软删除时间';
ALTER TABLE `guestbook` MODIFY COLUMN `from_user_id` bigint unsigned NOT NULL COMMENT '留言者用户ID';
ALTER TABLE `guestbook` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE `guestbook` MODIFY COLUMN `owner_user_id` bigint unsigned NOT NULL COMMENT '被留言用户ID';
ALTER TABLE `guestbook` MODIFY COLUMN `updated_at` datetime(3) NULL DEFAULT NULL COMMENT '更新时间';
ALTER TABLE `guestbook_reply` COMMENT = '留言回复表';
ALTER TABLE `guestbook_reply` MODIFY COLUMN `comment_id` bigint unsigned NOT NULL COMMENT '所属留言ID';
ALTER TABLE `guestbook_reply` MODIFY COLUMN `content` varchar(2000) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '回复内容';
ALTER TABLE `guestbook_reply` MODIFY COLUMN `created_at` datetime(3) NULL DEFAULT NULL COMMENT '创建时间';
ALTER TABLE `guestbook_reply` MODIFY COLUMN `deleted_at` datetime(3) NULL DEFAULT NULL COMMENT '软删除时间';
ALTER TABLE `guestbook_reply` MODIFY COLUMN `from_user_id` bigint unsigned NOT NULL COMMENT '回复者用户ID';
ALTER TABLE `guestbook_reply` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE `guestbook_reply` MODIFY COLUMN `parent_reply_id` bigint unsigned NULL DEFAULT 0 COMMENT '上级回复ID';
ALTER TABLE `guestbook_reply` MODIFY COLUMN `to_user_id` bigint unsigned NOT NULL COMMENT '被回复者用户ID';
ALTER TABLE `guestbook_reply` MODIFY COLUMN `updated_at` datetime(3) NULL DEFAULT NULL COMMENT '更新时间';
ALTER TABLE `moderation_action_log` COMMENT = '审核操作日志表';
ALTER TABLE `moderation_action_log` MODIFY COLUMN `action` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '操作类型';
ALTER TABLE `moderation_action_log` MODIFY COLUMN `actor_user_id` bigint unsigned NULL DEFAULT NULL COMMENT '操作人用户ID';
ALTER TABLE `moderation_action_log` MODIFY COLUMN `created_at` datetime(3) NOT NULL COMMENT '创建时间';
ALTER TABLE `moderation_action_log` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE `moderation_action_log` MODIFY COLUMN `item_id` bigint unsigned NULL DEFAULT NULL COMMENT '审核对象ID';
ALTER TABLE `moderation_action_log` MODIFY COLUMN `metadata_json` json NULL DEFAULT NULL COMMENT '操作扩展信息JSON';
ALTER TABLE `moderation_action_log` MODIFY COLUMN `reason` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '操作原因';
ALTER TABLE `moderation_action_log` MODIFY COLUMN `revision_id` bigint unsigned NULL DEFAULT NULL COMMENT '审核修订ID';
ALTER TABLE `moderation_action_log` MODIFY COLUMN `subject_user_id` bigint unsigned NULL DEFAULT NULL COMMENT '受影响用户ID';
ALTER TABLE `moderation_attempt` COMMENT = '内容审核尝试表';
ALTER TABLE `moderation_attempt` MODIFY COLUMN `content_type` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '业务内容类型';
ALTER TABLE `moderation_attempt` MODIFY COLUMN `created_at` datetime(3) NOT NULL COMMENT '创建时间';
ALTER TABLE `moderation_attempt` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE `moderation_attempt` MODIFY COLUMN `idempotency_key` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '提交幂等键';
ALTER TABLE `moderation_attempt` MODIFY COLUMN `item_id` bigint unsigned NULL DEFAULT NULL COMMENT '审核对象ID';
ALTER TABLE `moderation_attempt` MODIFY COLUMN `rule_match_ids` json NOT NULL COMMENT '命中规则ID列表';
ALTER TABLE `moderation_attempt` MODIFY COLUMN `rule_matches_truncated` tinyint(1) NOT NULL DEFAULT 0 COMMENT '命中规则列表是否被截断';
ALTER TABLE `moderation_attempt` MODIFY COLUMN `ruleset_version` bigint unsigned NOT NULL COMMENT '规则集版本';
ALTER TABLE `moderation_attempt` MODIFY COLUMN `user_id` bigint unsigned NOT NULL COMMENT '提交用户ID';
ALTER TABLE `moderation_control` COMMENT = '审核全局控制表';
ALTER TABLE `moderation_control` MODIFY COLUMN `changed_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '变更时间';
ALTER TABLE `moderation_control` MODIFY COLUMN `created_at` datetime(3) NOT NULL COMMENT '创建时间';
ALTER TABLE `moderation_control` MODIFY COLUMN `id` bigint unsigned NOT NULL COMMENT '主键ID';
ALTER TABLE `moderation_control` MODIFY COLUMN `lock_version` bigint unsigned NOT NULL DEFAULT 1 COMMENT '乐观锁版本';
ALTER TABLE `moderation_control` MODIFY COLUMN `operator_id` bigint unsigned NULL DEFAULT NULL COMMENT '操作人用户ID';
ALTER TABLE `moderation_control` MODIFY COLUMN `publishing_mode` varchar(24) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'open' COMMENT '发布控制模式';
ALTER TABLE `moderation_control` MODIFY COLUMN `reason` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '控制原因';
ALTER TABLE `moderation_control` MODIFY COLUMN `registration_mode` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'open' COMMENT '注册控制模式';
ALTER TABLE `moderation_control` MODIFY COLUMN `updated_at` datetime(3) NOT NULL COMMENT '更新时间';
ALTER TABLE `moderation_image` COMMENT = '审核图片指纹表';
ALTER TABLE `moderation_image` MODIFY COLUMN `approved_at` datetime(3) NULL DEFAULT NULL COMMENT '通过时间';
ALTER TABLE `moderation_image` MODIFY COLUMN `approved_by` bigint unsigned NULL DEFAULT NULL COMMENT '通过审核人用户ID';
ALTER TABLE `moderation_image` MODIFY COLUMN `created_at` datetime(3) NOT NULL COMMENT '创建时间';
ALTER TABLE `moderation_image` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE `moderation_image` MODIFY COLUMN `last_used_at` datetime(3) NOT NULL COMMENT '最后使用时间';
ALTER TABLE `moderation_image` MODIFY COLUMN `md5` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '图片MD5';
ALTER TABLE `moderation_image` MODIFY COLUMN `preview_object_key` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '预览图对象键';
ALTER TABLE `moderation_image` MODIFY COLUMN `sha256` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '图片SHA256';
ALTER TABLE `moderation_image` MODIFY COLUMN `size` bigint unsigned NOT NULL COMMENT '图片大小字节数';
ALTER TABLE `moderation_image` MODIFY COLUMN `status` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '图片审核状态';
ALTER TABLE `moderation_image` MODIFY COLUMN `updated_at` datetime(3) NOT NULL COMMENT '更新时间';
ALTER TABLE `moderation_item` COMMENT = '内容审核对象表';
ALTER TABLE `moderation_item` MODIFY COLUMN `approved_revision_id` bigint unsigned NULL DEFAULT NULL COMMENT '已通过修订ID';
ALTER TABLE `moderation_item` MODIFY COLUMN `author_id` bigint unsigned NOT NULL COMMENT '作者用户ID';
ALTER TABLE `moderation_item` MODIFY COLUMN `content_id` bigint unsigned NOT NULL COMMENT '业务内容ID';
ALTER TABLE `moderation_item` MODIFY COLUMN `content_type` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '业务内容类型';
ALTER TABLE `moderation_item` MODIFY COLUMN `created_at` datetime(3) NOT NULL COMMENT '创建时间';
ALTER TABLE `moderation_item` MODIFY COLUMN `deleted_at` datetime(3) NULL DEFAULT NULL COMMENT '软删除时间';
ALTER TABLE `moderation_item` MODIFY COLUMN `emergency_hidden_at` datetime(3) NULL DEFAULT NULL COMMENT '紧急隐藏时间';
ALTER TABLE `moderation_item` MODIFY COLUMN `emergency_hidden_reason` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '紧急隐藏原因';
ALTER TABLE `moderation_item` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE `moderation_item` MODIFY COLUMN `lifecycle_state` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'active' COMMENT '生命周期状态';
ALTER TABLE `moderation_item` MODIFY COLUMN `lock_version` bigint unsigned NOT NULL DEFAULT 1 COMMENT '乐观锁版本';
ALTER TABLE `moderation_item` MODIFY COLUMN `materialized_revision_id` bigint unsigned NULL DEFAULT NULL COMMENT '当前物化修订ID';
ALTER TABLE `moderation_item` MODIFY COLUMN `pending_revision_id` bigint unsigned NULL DEFAULT NULL COMMENT '待审核修订ID';
ALTER TABLE `moderation_item` MODIFY COLUMN `public_state` varchar(24) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'placeholder' COMMENT '公开展示状态';
ALTER TABLE `moderation_item` MODIFY COLUMN `state_before_emergency` varchar(24) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '紧急隐藏前公开状态';
ALTER TABLE `moderation_item` MODIFY COLUMN `updated_at` datetime(3) NOT NULL COMMENT '更新时间';
ALTER TABLE `moderation_review_email_batch` COMMENT = '审核摘要邮件批次表';
ALTER TABLE `moderation_review_email_batch` MODIFY COLUMN `attempts` int NOT NULL DEFAULT 0 COMMENT '尝试次数';
ALTER TABLE `moderation_review_email_batch` MODIFY COLUMN `created_at` datetime(3) NOT NULL COMMENT '创建时间';
ALTER TABLE `moderation_review_email_batch` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE `moderation_review_email_batch` MODIFY COLUMN `item_count` int NOT NULL DEFAULT 0 COMMENT '包含任务数';
ALTER TABLE `moderation_review_email_batch` MODIFY COLUMN `last_error` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '最近一次发送错误';
ALTER TABLE `moderation_review_email_batch` MODIFY COLUMN `lease_until` datetime(3) NULL DEFAULT NULL COMMENT 'worker租约到期时间';
ALTER TABLE `moderation_review_email_batch` MODIFY COLUMN `locked_by` varchar(80) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '领取批次的worker标识';
ALTER TABLE `moderation_review_email_batch` MODIFY COLUMN `message_id` varchar(120) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '邮件Message-ID';
ALTER TABLE `moderation_review_email_batch` MODIFY COLUMN `next_attempt_at` datetime(3) NOT NULL COMMENT '下次尝试时间';
ALTER TABLE `moderation_review_email_batch` MODIFY COLUMN `recipient_user_id` bigint unsigned NOT NULL COMMENT '接收人用户ID';
ALTER TABLE `moderation_review_email_batch` MODIFY COLUMN `scheduled_at` datetime(3) NOT NULL COMMENT '计划发送时间';
ALTER TABLE `moderation_review_email_batch` MODIFY COLUMN `sent_at` datetime(3) NULL DEFAULT NULL COMMENT '实际发送时间';
ALTER TABLE `moderation_review_email_batch` MODIFY COLUMN `status` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '批次状态';
ALTER TABLE `moderation_review_email_batch` MODIFY COLUMN `subject` varchar(180) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '邮件标题';
ALTER TABLE `moderation_review_email_batch` MODIFY COLUMN `to_email` varchar(155) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '收件邮箱快照';
ALTER TABLE `moderation_review_email_batch` MODIFY COLUMN `updated_at` datetime(3) NOT NULL COMMENT '更新时间';
ALTER TABLE `moderation_review_email_task` COMMENT = '审核摘要邮件任务表';
ALTER TABLE `moderation_review_email_task` MODIFY COLUMN `available_at` datetime(3) NOT NULL COMMENT '最早可处理时间';
ALTER TABLE `moderation_review_email_task` MODIFY COLUMN `batch_id` bigint unsigned NULL DEFAULT NULL COMMENT '归属审核摘要邮件批次ID';
ALTER TABLE `moderation_review_email_task` MODIFY COLUMN `created_at` datetime(3) NOT NULL COMMENT '创建时间';
ALTER TABLE `moderation_review_email_task` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE `moderation_review_email_task` MODIFY COLUMN `item_id` bigint unsigned NOT NULL COMMENT '待审核内容对象ID';
ALTER TABLE `moderation_review_email_task` MODIFY COLUMN `next_attempt_at` datetime(3) NOT NULL COMMENT '下次尝试时间';
ALTER TABLE `moderation_review_email_task` MODIFY COLUMN `revision_id` bigint unsigned NOT NULL COMMENT '待审核内容修订ID';
ALTER TABLE `moderation_review_email_task` MODIFY COLUMN `status` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '任务状态';
ALTER TABLE `moderation_review_email_task` MODIFY COLUMN `updated_at` datetime(3) NOT NULL COMMENT '更新时间';
ALTER TABLE `moderation_revision` COMMENT = '内容审核修订表';
ALTER TABLE `moderation_revision` MODIFY COLUMN `created_at` datetime(3) NOT NULL COMMENT '创建时间';
ALTER TABLE `moderation_revision` MODIFY COLUMN `decision_reason` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '审核决定原因';
ALTER TABLE `moderation_revision` MODIFY COLUMN `decision_type` varchar(24) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '审核决定类型';
ALTER TABLE `moderation_revision` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE `moderation_revision` MODIFY COLUMN `idempotency_key` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '提交幂等键';
ALTER TABLE `moderation_revision` MODIFY COLUMN `item_id` bigint unsigned NOT NULL COMMENT '审核对象ID';
ALTER TABLE `moderation_revision` MODIFY COLUMN `moment_comment_status` tinyint NULL DEFAULT NULL COMMENT '碎语提交时评论开关';
ALTER TABLE `moderation_revision` MODIFY COLUMN `moment_status` tinyint NULL DEFAULT NULL COMMENT '碎语提交时公开开关';
ALTER TABLE `moderation_revision` MODIFY COLUMN `policy_action` varchar(24) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '策略动作';
ALTER TABLE `moderation_revision` MODIFY COLUMN `published_content` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '发布正文';
ALTER TABLE `moderation_revision` MODIFY COLUMN `review_status` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '审核状态';
ALTER TABLE `moderation_revision` MODIFY COLUMN `reviewed_at` datetime(3) NULL DEFAULT NULL COMMENT '审核时间';
ALTER TABLE `moderation_revision` MODIFY COLUMN `reviewer_id` bigint unsigned NULL DEFAULT NULL COMMENT '审核人用户ID';
ALTER TABLE `moderation_revision` MODIFY COLUMN `risk_level` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '风险等级';
ALTER TABLE `moderation_revision` MODIFY COLUMN `rule_match_ids` json NOT NULL COMMENT '命中规则ID列表';
ALTER TABLE `moderation_revision` MODIFY COLUMN `rule_matches_truncated` tinyint(1) NOT NULL DEFAULT 0 COMMENT '命中规则列表是否被截断';
ALTER TABLE `moderation_revision` MODIFY COLUMN `ruleset_version` bigint unsigned NOT NULL COMMENT '规则集版本';
ALTER TABLE `moderation_revision` MODIFY COLUMN `submitted_content` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '提交原文';
ALTER TABLE `moderation_revision` MODIFY COLUMN `submitter_id` bigint unsigned NOT NULL COMMENT '提交者用户ID';
ALTER TABLE `moderation_revision` MODIFY COLUMN `updated_at` datetime(3) NOT NULL COMMENT '更新时间';
ALTER TABLE `moderation_revision` MODIFY COLUMN `version` bigint unsigned NOT NULL COMMENT '修订版本号';
ALTER TABLE `moderation_revision_image` COMMENT = '审核修订图片表';
ALTER TABLE `moderation_revision_image` MODIFY COLUMN `created_at` datetime(3) NOT NULL COMMENT '创建时间';
ALTER TABLE `moderation_revision_image` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE `moderation_revision_image` MODIFY COLUMN `is_gif` tinyint(1) NOT NULL DEFAULT 0 COMMENT '是否GIF图片';
ALTER TABLE `moderation_revision_image` MODIFY COLUMN `md5` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '图片MD5';
ALTER TABLE `moderation_revision_image` MODIFY COLUMN `media_type` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '图片媒体类型';
ALTER TABLE `moderation_revision_image` MODIFY COLUMN `object_key` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '图片对象键';
ALTER TABLE `moderation_revision_image` MODIFY COLUMN `revision_id` bigint unsigned NOT NULL COMMENT '审核修订ID';
ALTER TABLE `moderation_revision_image` MODIFY COLUMN `seq` bigint unsigned NOT NULL COMMENT '图片排序';
ALTER TABLE `moderation_revision_image` MODIFY COLUMN `sha256` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '图片SHA256';
ALTER TABLE `moderation_revision_image` MODIFY COLUMN `size` bigint unsigned NOT NULL COMMENT '图片大小字节数';
ALTER TABLE `moderation_revision_image` MODIFY COLUMN `updated_at` datetime(3) NOT NULL COMMENT '更新时间';
ALTER TABLE `moderation_rule` COMMENT = '审核规则表';
ALTER TABLE `moderation_rule` MODIFY COLUMN `activated_ruleset_id` bigint unsigned NOT NULL COMMENT '启用规则集ID';
ALTER TABLE `moderation_rule` MODIFY COLUMN `category` varchar(24) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '规则分类';
ALTER TABLE `moderation_rule` MODIFY COLUMN `created_at` datetime(3) NOT NULL COMMENT '创建时间';
ALTER TABLE `moderation_rule` MODIFY COLUMN `deactivated_ruleset_id` bigint unsigned NULL DEFAULT NULL COMMENT '停用规则集ID';
ALTER TABLE `moderation_rule` MODIFY COLUMN `dedupe_hash` binary(32) NOT NULL COMMENT '去重哈希';
ALTER TABLE `moderation_rule` MODIFY COLUMN `effect` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '规则效果';
ALTER TABLE `moderation_rule` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE `moderation_rule` MODIFY COLUMN `name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '规则名称';
ALTER TABLE `moderation_rule` MODIFY COLUMN `pattern` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '规则匹配模式';
ALTER TABLE `moderation_rule` MODIFY COLUMN `priority` int NOT NULL DEFAULT 100 COMMENT '匹配优先级';
ALTER TABLE `moderation_rule` MODIFY COLUMN `replaces_rule_id` bigint unsigned NULL DEFAULT NULL COMMENT '替代规则ID';
ALTER TABLE `moderation_rule` MODIFY COLUMN `risk_level` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '风险等级';
ALTER TABLE `moderation_rule` MODIFY COLUMN `rule_type` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '规则类型';
ALTER TABLE `moderation_rule` MODIFY COLUMN `source_id` bigint unsigned NOT NULL COMMENT '规则来源ID';
ALTER TABLE `moderation_rule` MODIFY COLUMN `updated_at` datetime(3) NOT NULL COMMENT '更新时间';
ALTER TABLE `moderation_rule_import` COMMENT = '审核规则导入任务表';
ALTER TABLE `moderation_rule_import` MODIFY COLUMN `created_at` datetime(3) NOT NULL COMMENT '创建时间';
ALTER TABLE `moderation_rule_import` MODIFY COLUMN `default_category` varchar(24) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '默认规则分类';
ALTER TABLE `moderation_rule_import` MODIFY COLUMN `default_effect` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '默认规则效果';
ALTER TABLE `moderation_rule_import` MODIFY COLUMN `default_priority` int NOT NULL COMMENT '默认优先级';
ALTER TABLE `moderation_rule_import` MODIFY COLUMN `default_risk_level` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '默认风险等级';
ALTER TABLE `moderation_rule_import` MODIFY COLUMN `duplicate_rows` bigint unsigned NOT NULL DEFAULT 0 COMMENT '重复行数';
ALTER TABLE `moderation_rule_import` MODIFY COLUMN `error_object_key` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '错误明细对象键';
ALTER TABLE `moderation_rule_import` MODIFY COLUMN `error_rows` bigint unsigned NOT NULL DEFAULT 0 COMMENT '错误行数';
ALTER TABLE `moderation_rule_import` MODIFY COLUMN `file_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '导入文件名';
ALTER TABLE `moderation_rule_import` MODIFY COLUMN `file_size` bigint unsigned NOT NULL COMMENT '导入文件大小';
ALTER TABLE `moderation_rule_import` MODIFY COLUMN `format` varchar(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '导入文件格式';
ALTER TABLE `moderation_rule_import` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE `moderation_rule_import` MODIFY COLUMN `object_key` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '导入文件对象键';
ALTER TABLE `moderation_rule_import` MODIFY COLUMN `operator_id` bigint unsigned NOT NULL COMMENT '操作人用户ID';
ALTER TABLE `moderation_rule_import` MODIFY COLUMN `ruleset_id` bigint unsigned NULL DEFAULT NULL COMMENT '生成规则集ID';
ALTER TABLE `moderation_rule_import` MODIFY COLUMN `source_id` bigint unsigned NOT NULL COMMENT '规则来源ID';
ALTER TABLE `moderation_rule_import` MODIFY COLUMN `total_rows` bigint unsigned NOT NULL DEFAULT 0 COMMENT '总行数';
ALTER TABLE `moderation_rule_import` MODIFY COLUMN `updated_at` datetime(3) NOT NULL COMMENT '更新时间';
ALTER TABLE `moderation_rule_import` MODIFY COLUMN `valid_rows` bigint unsigned NOT NULL DEFAULT 0 COMMENT '有效行数';
ALTER TABLE `moderation_rule_import` MODIFY COLUMN `validation_status` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '校验状态';
ALTER TABLE `moderation_rule_source` COMMENT = '审核规则来源表';
ALTER TABLE `moderation_rule_source` MODIFY COLUMN `created_at` datetime(3) NOT NULL COMMENT '创建时间';
ALTER TABLE `moderation_rule_source` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE `moderation_rule_source` MODIFY COLUMN `name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '规则来源名称';
ALTER TABLE `moderation_rule_source` MODIFY COLUMN `updated_at` datetime(3) NOT NULL COMMENT '更新时间';
ALTER TABLE `moderation_ruleset` COMMENT = '审核规则集表';
ALTER TABLE `moderation_ruleset` MODIFY COLUMN `base_ruleset_id` bigint unsigned NULL DEFAULT NULL COMMENT '基础规则集ID';
ALTER TABLE `moderation_ruleset` MODIFY COLUMN `build_duration_ms` bigint unsigned NOT NULL DEFAULT 0 COMMENT '构建耗时毫秒数';
ALTER TABLE `moderation_ruleset` MODIFY COLUMN `build_peak_bytes` bigint unsigned NOT NULL DEFAULT 0 COMMENT '构建峰值内存字节数';
ALTER TABLE `moderation_ruleset` MODIFY COLUMN `composite_count` bigint unsigned NOT NULL DEFAULT 0 COMMENT '组合规则数';
ALTER TABLE `moderation_ruleset` MODIFY COLUMN `created_at` datetime(3) NOT NULL COMMENT '创建时间';
ALTER TABLE `moderation_ruleset` MODIFY COLUMN `failure_code` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '失败代码';
ALTER TABLE `moderation_ruleset` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE `moderation_ruleset` MODIFY COLUMN `index_bytes` bigint unsigned NOT NULL DEFAULT 0 COMMENT '索引字节数';
ALTER TABLE `moderation_ruleset` MODIFY COLUMN `index_format_version` int unsigned NOT NULL DEFAULT 1 COMMENT '索引格式版本';
ALTER TABLE `moderation_ruleset` MODIFY COLUMN `index_object_key` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '索引对象键';
ALTER TABLE `moderation_ruleset` MODIFY COLUMN `index_sha256` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '索引SHA256';
ALTER TABLE `moderation_ruleset` MODIFY COLUMN `keyword_count` bigint unsigned NOT NULL DEFAULT 0 COMMENT '关键词规则数';
ALTER TABLE `moderation_ruleset` MODIFY COLUMN `operator_id` bigint unsigned NULL DEFAULT NULL COMMENT '操作人用户ID';
ALTER TABLE `moderation_ruleset` MODIFY COLUMN `regexp_count` bigint unsigned NOT NULL DEFAULT 0 COMMENT '正则规则数';
ALTER TABLE `moderation_ruleset` MODIFY COLUMN `rule_count` bigint unsigned NOT NULL DEFAULT 0 COMMENT '规则总数';
ALTER TABLE `moderation_ruleset` MODIFY COLUMN `status` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '规则集状态';
ALTER TABLE `moderation_ruleset` MODIFY COLUMN `updated_at` datetime(3) NOT NULL COMMENT '更新时间';
ALTER TABLE `moderation_ruleset_removal` COMMENT = '审核规则集移除记录表';
ALTER TABLE `moderation_ruleset_removal` MODIFY COLUMN `created_at` datetime(3) NOT NULL COMMENT '创建时间';
ALTER TABLE `moderation_ruleset_removal` MODIFY COLUMN `rule_id` bigint unsigned NOT NULL COMMENT '规则ID';
ALTER TABLE `moderation_ruleset_removal` MODIFY COLUMN `ruleset_id` bigint unsigned NOT NULL COMMENT '规则集ID';
ALTER TABLE `moderation_visible_image` COMMENT = '审核可见图片表';
ALTER TABLE `moderation_visible_image` MODIFY COLUMN `created_at` datetime(3) NOT NULL COMMENT '创建时间';
ALTER TABLE `moderation_visible_image` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE `moderation_visible_image` MODIFY COLUMN `item_id` bigint unsigned NOT NULL COMMENT '审核对象ID';
ALTER TABLE `moderation_visible_image` MODIFY COLUMN `object_key` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '图片对象键';
ALTER TABLE `moderation_visible_image` MODIFY COLUMN `revision_id` bigint unsigned NOT NULL COMMENT '审核修订ID';
ALTER TABLE `moderation_visible_image` MODIFY COLUMN `seq` bigint unsigned NOT NULL COMMENT '图片排序';
ALTER TABLE `moderation_visible_image` MODIFY COLUMN `updated_at` datetime(3) NOT NULL COMMENT '更新时间';
ALTER TABLE `moment` COMMENT = '碎语表';
ALTER TABLE `moment` MODIFY COLUMN `comment_status` tinyint NULL DEFAULT 1 COMMENT '评论开关状态';
ALTER TABLE `moment` MODIFY COLUMN `content` varchar(800) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '碎语正文';
ALTER TABLE `moment` MODIFY COLUMN `created_at` datetime(3) NULL DEFAULT NULL COMMENT '创建时间';
ALTER TABLE `moment` MODIFY COLUMN `deleted_at` datetime(3) NULL DEFAULT NULL COMMENT '软删除时间';
ALTER TABLE `moment` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE `moment` MODIFY COLUMN `is_top` tinyint NULL DEFAULT 0 COMMENT '是否置顶';
ALTER TABLE `moment` MODIFY COLUMN `read_count` bigint NULL DEFAULT 0 COMMENT '阅读次数';
ALTER TABLE `moment` MODIFY COLUMN `status` tinyint NULL DEFAULT 1 COMMENT '公开状态';
ALTER TABLE `moment` MODIFY COLUMN `updated_at` datetime(3) NULL DEFAULT NULL COMMENT '更新时间';
ALTER TABLE `moment` MODIFY COLUMN `user_id` bigint unsigned NOT NULL COMMENT '作者用户ID';
ALTER TABLE `moment_comment` COMMENT = '碎语评论表';
ALTER TABLE `moment_comment` MODIFY COLUMN `content` varchar(2000) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '评论内容';
ALTER TABLE `moment_comment` MODIFY COLUMN `created_at` datetime(3) NULL DEFAULT NULL COMMENT '创建时间';
ALTER TABLE `moment_comment` MODIFY COLUMN `deleted_at` datetime(3) NULL DEFAULT NULL COMMENT '软删除时间';
ALTER TABLE `moment_comment` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE `moment_comment` MODIFY COLUMN `moment_id` bigint unsigned NOT NULL COMMENT '碎语ID';
ALTER TABLE `moment_comment` MODIFY COLUMN `updated_at` datetime(3) NULL DEFAULT NULL COMMENT '更新时间';
ALTER TABLE `moment_comment` MODIFY COLUMN `user_id` bigint unsigned NOT NULL COMMENT '评论者用户ID';
ALTER TABLE `moment_comment_reply` COMMENT = '碎语评论回复表';
ALTER TABLE `moment_comment_reply` MODIFY COLUMN `comment_id` bigint unsigned NOT NULL COMMENT '所属碎语评论ID';
ALTER TABLE `moment_comment_reply` MODIFY COLUMN `content` varchar(2000) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '回复内容';
ALTER TABLE `moment_comment_reply` MODIFY COLUMN `created_at` datetime(3) NULL DEFAULT NULL COMMENT '创建时间';
ALTER TABLE `moment_comment_reply` MODIFY COLUMN `deleted_at` datetime(3) NULL DEFAULT NULL COMMENT '软删除时间';
ALTER TABLE `moment_comment_reply` MODIFY COLUMN `from_user_id` bigint unsigned NOT NULL COMMENT '回复者用户ID';
ALTER TABLE `moment_comment_reply` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE `moment_comment_reply` MODIFY COLUMN `parent_reply_id` bigint unsigned NULL DEFAULT 0 COMMENT '上级回复ID';
ALTER TABLE `moment_comment_reply` MODIFY COLUMN `to_user_id` bigint unsigned NOT NULL COMMENT '被回复者用户ID';
ALTER TABLE `moment_comment_reply` MODIFY COLUMN `updated_at` datetime(3) NULL DEFAULT NULL COMMENT '更新时间';
ALTER TABLE `moment_media` COMMENT = '碎语媒体表';
ALTER TABLE `moment_media` MODIFY COLUMN `created_at` datetime(3) NULL DEFAULT NULL COMMENT '创建时间';
ALTER TABLE `moment_media` MODIFY COLUMN `deleted_at` datetime(3) NULL DEFAULT NULL COMMENT '软删除时间';
ALTER TABLE `moment_media` MODIFY COLUMN `file_type` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '文件扩展名';
ALTER TABLE `moment_media` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE `moment_media` MODIFY COLUMN `moment_id` bigint unsigned NOT NULL COMMENT '碎语ID';
ALTER TABLE `moment_media` MODIFY COLUMN `name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '原始文件名';
ALTER TABLE `moment_media` MODIFY COLUMN `read_count` bigint NULL DEFAULT 0 COMMENT '查看次数';
ALTER TABLE `moment_media` MODIFY COLUMN `seq` bigint NULL DEFAULT 0 COMMENT '展示排序';
ALTER TABLE `moment_media` MODIFY COLUMN `size` bigint unsigned NULL DEFAULT NULL COMMENT '文件大小字节数';
ALTER TABLE `moment_media` MODIFY COLUMN `status` tinyint NULL DEFAULT 1 COMMENT '媒体状态';
ALTER TABLE `moment_media` MODIFY COLUMN `type` tinyint NULL DEFAULT 0 COMMENT '媒体类型';
ALTER TABLE `moment_media` MODIFY COLUMN `updated_at` datetime(3) NULL DEFAULT NULL COMMENT '更新时间';
ALTER TABLE `moment_media` MODIFY COLUMN `uploader_id` bigint unsigned NULL DEFAULT NULL COMMENT '上传者用户ID';
ALTER TABLE `moment_media` MODIFY COLUMN `url` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '访问URL';
ALTER TABLE `music` COMMENT = '音乐表';
ALTER TABLE `music` MODIFY COLUMN `album` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '专辑文本';
ALTER TABLE `music` MODIFY COLUMN `album_id` bigint unsigned NULL DEFAULT NULL COMMENT '专辑ID';
ALTER TABLE `music` MODIFY COLUMN `album_track_no` smallint unsigned NULL DEFAULT 0 COMMENT '专辑曲目编号';
ALTER TABLE `music` MODIFY COLUMN `artist_display_name` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '展示艺术家名称';
ALTER TABLE `music` MODIFY COLUMN `audio_hash` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '音频哈希';
ALTER TABLE `music` MODIFY COLUMN `audio_key` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '音频对象键';
ALTER TABLE `music` MODIFY COLUMN `audio_mime` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '音频MIME类型';
ALTER TABLE `music` MODIFY COLUMN `audio_size` bigint unsigned NULL DEFAULT 0 COMMENT '音频文件大小';
ALTER TABLE `music` MODIFY COLUMN `cover_img_url` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '封面图URL';
ALTER TABLE `music` MODIFY COLUMN `created_at` datetime(3) NULL DEFAULT NULL COMMENT '创建时间';
ALTER TABLE `music` MODIFY COLUMN `deleted_at` datetime(3) NULL DEFAULT NULL COMMENT '软删除时间';
ALTER TABLE `music` MODIFY COLUMN `description` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '歌曲描述';
ALTER TABLE `music` MODIFY COLUMN `duration` smallint unsigned NULL DEFAULT 0 COMMENT '时长秒数';
ALTER TABLE `music` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE `music` MODIFY COLUMN `is_public` tinyint(1) NULL DEFAULT 1 COMMENT '是否公开展示';
ALTER TABLE `music` MODIFY COLUMN `lyric` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '歌词';
ALTER TABLE `music` MODIFY COLUMN `name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '歌曲名称';
ALTER TABLE `music` MODIFY COLUMN `seq` bigint NULL DEFAULT 0 COMMENT '展示排序';
ALTER TABLE `music` MODIFY COLUMN `singer` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '歌手文本';
ALTER TABLE `music` MODIFY COLUMN `song_date` date NULL DEFAULT NULL COMMENT '歌曲日期';
ALTER TABLE `music` MODIFY COLUMN `updated_at` datetime(3) NULL DEFAULT NULL COMMENT '更新时间';
ALTER TABLE `music_album` COMMENT = '音乐专辑表';
ALTER TABLE `music_album` MODIFY COLUMN `artist_id` bigint unsigned NULL DEFAULT NULL COMMENT '专辑艺术家ID';
ALTER TABLE `music_album` MODIFY COLUMN `cover_key` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '专辑封面对象键';
ALTER TABLE `music_album` MODIFY COLUMN `created_at` datetime(3) NULL DEFAULT NULL COMMENT '创建时间';
ALTER TABLE `music_album` MODIFY COLUMN `deleted_at` datetime(3) NULL DEFAULT NULL COMMENT '软删除时间';
ALTER TABLE `music_album` MODIFY COLUMN `description` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '专辑描述';
ALTER TABLE `music_album` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE `music_album` MODIFY COLUMN `name` varchar(150) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '专辑名称';
ALTER TABLE `music_album` MODIFY COLUMN `release_date` date NULL DEFAULT NULL COMMENT '发行日期';
ALTER TABLE `music_album` MODIFY COLUMN `updated_at` datetime(3) NULL DEFAULT NULL COMMENT '更新时间';
ALTER TABLE `music_artist` COMMENT = '音乐艺术家表';
ALTER TABLE `music_artist` MODIFY COLUMN `avatar_key` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '艺术家头像对象键';
ALTER TABLE `music_artist` MODIFY COLUMN `created_at` datetime(3) NULL DEFAULT NULL COMMENT '创建时间';
ALTER TABLE `music_artist` MODIFY COLUMN `deleted_at` datetime(3) NULL DEFAULT NULL COMMENT '软删除时间';
ALTER TABLE `music_artist` MODIFY COLUMN `description` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '艺术家描述';
ALTER TABLE `music_artist` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE `music_artist` MODIFY COLUMN `name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '艺术家名称';
ALTER TABLE `music_artist` MODIFY COLUMN `name_zh` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '艺术家中文名称';
ALTER TABLE `music_artist` MODIFY COLUMN `updated_at` datetime(3) NULL DEFAULT NULL COMMENT '更新时间';
ALTER TABLE `music_artist_relation` COMMENT = '音乐艺术家关系表';
ALTER TABLE `music_artist_relation` MODIFY COLUMN `artist_id` bigint unsigned NOT NULL COMMENT '艺术家ID';
ALTER TABLE `music_artist_relation` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE `music_artist_relation` MODIFY COLUMN `music_id` bigint unsigned NOT NULL COMMENT '音乐ID';
ALTER TABLE `music_artist_relation` MODIFY COLUMN `role` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT 'primary' COMMENT '艺术家角色';
ALTER TABLE `music_artist_relation` MODIFY COLUMN `seq` bigint NULL DEFAULT 0 COMMENT '展示排序';
ALTER TABLE `notification_email_batch` COMMENT = '通知邮件批次表';
ALTER TABLE `notification_email_batch` MODIFY COLUMN `attempts` bigint NOT NULL DEFAULT 0 COMMENT '尝试次数';
ALTER TABLE `notification_email_batch` MODIFY COLUMN `created_at` datetime(3) NULL DEFAULT NULL COMMENT '创建时间';
ALTER TABLE `notification_email_batch` MODIFY COLUMN `deleted_at` datetime(3) NULL DEFAULT NULL COMMENT '软删除时间';
ALTER TABLE `notification_email_batch` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE `notification_email_batch` MODIFY COLUMN `item_count` bigint NOT NULL DEFAULT 0 COMMENT '包含任务数';
ALTER TABLE `notification_email_batch` MODIFY COLUMN `last_error` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '最近一次发送错误';
ALTER TABLE `notification_email_batch` MODIFY COLUMN `lease_until` datetime(6) NULL DEFAULT NULL COMMENT 'worker租约到期时间';
ALTER TABLE `notification_email_batch` MODIFY COLUMN `locked_by` varchar(80) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '领取批次的worker标识';
ALTER TABLE `notification_email_batch` MODIFY COLUMN `message_id` varchar(120) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '邮件Message-ID或内部幂等ID';
ALTER TABLE `notification_email_batch` MODIFY COLUMN `purpose` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '邮件用途';
ALTER TABLE `notification_email_batch` MODIFY COLUMN `recipient_user_id` bigint unsigned NOT NULL COMMENT '接收人用户ID';
ALTER TABLE `notification_email_batch` MODIFY COLUMN `scheduled_at` datetime(3) NULL DEFAULT NULL COMMENT '计划发送时间';
ALTER TABLE `notification_email_batch` MODIFY COLUMN `sent_at` datetime(3) NULL DEFAULT NULL COMMENT '实际发送时间';
ALTER TABLE `notification_email_batch` MODIFY COLUMN `status` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT 'pending' COMMENT '批次状态';
ALTER TABLE `notification_email_batch` MODIFY COLUMN `subject` varchar(180) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '邮件标题';
ALTER TABLE `notification_email_batch` MODIFY COLUMN `to_email` varchar(155) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '收件邮箱快照';
ALTER TABLE `notification_email_batch` MODIFY COLUMN `updated_at` datetime(3) NULL DEFAULT NULL COMMENT '更新时间';
ALTER TABLE `notification_email_batch_item` COMMENT = '通知邮件批次任务关联表';
ALTER TABLE `notification_email_batch_item` MODIFY COLUMN `batch_id` bigint unsigned NOT NULL COMMENT '邮件批次ID';
ALTER TABLE `notification_email_batch_item` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE `notification_email_batch_item` MODIFY COLUMN `task_id` bigint unsigned NOT NULL COMMENT '邮件任务ID';
ALTER TABLE `notification_email_task` COMMENT = '通知邮件任务表';
ALTER TABLE `notification_email_task` MODIFY COLUMN `actor_user_id` bigint unsigned NULL DEFAULT NULL COMMENT '操作人用户ID';
ALTER TABLE `notification_email_task` MODIFY COLUMN `attempts` bigint NOT NULL DEFAULT 0 COMMENT '尝试次数';
ALTER TABLE `notification_email_task` MODIFY COLUMN `available_at` datetime(3) NULL DEFAULT NULL COMMENT '最早可聚合时间';
ALTER TABLE `notification_email_task` MODIFY COLUMN `batch_id` bigint unsigned NULL DEFAULT NULL COMMENT '归属邮件批次ID';
ALTER TABLE `notification_email_task` MODIFY COLUMN `created_at` datetime(3) NULL DEFAULT NULL COMMENT '创建时间';
ALTER TABLE `notification_email_task` MODIFY COLUMN `deleted_at` datetime(3) NULL DEFAULT NULL COMMENT '软删除时间';
ALTER TABLE `notification_email_task` MODIFY COLUMN `event_id` bigint unsigned NOT NULL COMMENT '通知事件ID';
ALTER TABLE `notification_email_task` MODIFY COLUMN `event_type` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '事件类型快照';
ALTER TABLE `notification_email_task` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE `notification_email_task` MODIFY COLUMN `idempotency_key` varchar(120) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '任务幂等键';
ALTER TABLE `notification_email_task` MODIFY COLUMN `last_error` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '最近一次处理错误';
ALTER TABLE `notification_email_task` MODIFY COLUMN `lease_until` datetime(6) NULL DEFAULT NULL COMMENT 'worker租约到期时间';
ALTER TABLE `notification_email_task` MODIFY COLUMN `locked_by` varchar(80) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '领取任务的worker标识';
ALTER TABLE `notification_email_task` MODIFY COLUMN `next_attempt_at` datetime(3) NULL DEFAULT NULL COMMENT '下次处理时间';
ALTER TABLE `notification_email_task` MODIFY COLUMN `priority` bigint NOT NULL DEFAULT 0 COMMENT '处理优先级';
ALTER TABLE `notification_email_task` MODIFY COLUMN `purpose` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '邮件用途';
ALTER TABLE `notification_email_task` MODIFY COLUMN `recipient_user_id` bigint unsigned NOT NULL COMMENT '接收人用户ID';
ALTER TABLE `notification_email_task` MODIFY COLUMN `status` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT 'pending' COMMENT '任务状态';
ALTER TABLE `notification_email_task` MODIFY COLUMN `to_email` varchar(155) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '发送目标邮箱快照';
ALTER TABLE `notification_email_task` MODIFY COLUMN `updated_at` datetime(3) NULL DEFAULT NULL COMMENT '更新时间';
ALTER TABLE `notification_event` COMMENT = '通知事件表';
ALTER TABLE `notification_event` MODIFY COLUMN `actor_user_id` bigint unsigned NULL DEFAULT NULL COMMENT '操作人用户ID';
ALTER TABLE `notification_event` MODIFY COLUMN `attempts` bigint NOT NULL DEFAULT 0 COMMENT '分发尝试次数';
ALTER TABLE `notification_event` MODIFY COLUMN `content_excerpt` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '内容摘要快照';
ALTER TABLE `notification_event` MODIFY COLUMN `created_at` datetime(3) NULL DEFAULT NULL COMMENT '创建时间';
ALTER TABLE `notification_event` MODIFY COLUMN `deleted_at` datetime(3) NULL DEFAULT NULL COMMENT '软删除时间';
ALTER TABLE `notification_event` MODIFY COLUMN `dispatch_status` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT 'pending' COMMENT '分发状态';
ALTER TABLE `notification_event` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE `notification_event` MODIFY COLUMN `last_error` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '最近一次分发错误';
ALTER TABLE `notification_event` MODIFY COLUMN `lease_until` datetime(6) NULL DEFAULT NULL COMMENT 'worker租约到期时间';
ALTER TABLE `notification_event` MODIFY COLUMN `locked_by` varchar(80) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '领取事件的worker标识';
ALTER TABLE `notification_event` MODIFY COLUMN `metadata_json` json NULL DEFAULT NULL COMMENT '事件扩展信息JSON';
ALTER TABLE `notification_event` MODIFY COLUMN `next_process_at` datetime(3) NULL DEFAULT NULL COMMENT '下次可处理时间';
ALTER TABLE `notification_event` MODIFY COLUMN `root_id` bigint unsigned NULL DEFAULT NULL COMMENT '根对象ID';
ALTER TABLE `notification_event` MODIFY COLUMN `root_type` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '根对象类型';
ALTER TABLE `notification_event` MODIFY COLUMN `source_id` bigint unsigned NULL DEFAULT NULL COMMENT '直接对象ID';
ALTER TABLE `notification_event` MODIFY COLUMN `source_type` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '直接对象类型';
ALTER TABLE `notification_event` MODIFY COLUMN `title` varchar(120) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '事件标题快照';
ALTER TABLE `notification_event` MODIFY COLUMN `type` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '通知事件类型';
ALTER TABLE `notification_event` MODIFY COLUMN `updated_at` datetime(3) NULL DEFAULT NULL COMMENT '更新时间';
ALTER TABLE `notification_inbox` COMMENT = '站内通知收件箱表';
ALTER TABLE `notification_inbox` MODIFY COLUMN `created_at` datetime(3) NULL DEFAULT NULL COMMENT '创建时间';
ALTER TABLE `notification_inbox` MODIFY COLUMN `deleted_at` datetime(3) NULL DEFAULT NULL COMMENT '软删除时间';
ALTER TABLE `notification_inbox` MODIFY COLUMN `delivered_at` datetime(3) NULL DEFAULT NULL COMMENT '投递时间';
ALTER TABLE `notification_inbox` MODIFY COLUMN `event_id` bigint unsigned NOT NULL COMMENT '通知事件ID';
ALTER TABLE `notification_inbox` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE `notification_inbox` MODIFY COLUMN `is_read` tinyint NOT NULL DEFAULT 0 COMMENT '是否已读';
ALTER TABLE `notification_inbox` MODIFY COLUMN `read_at` datetime(3) NULL DEFAULT NULL COMMENT '已读时间';
ALTER TABLE `notification_inbox` MODIFY COLUMN `recipient_user_id` bigint unsigned NOT NULL COMMENT '接收人用户ID';
ALTER TABLE `notification_inbox` MODIFY COLUMN `updated_at` datetime(3) NULL DEFAULT NULL COMMENT '更新时间';
ALTER TABLE `notification_preference` COMMENT = '通知偏好表';
ALTER TABLE `notification_preference` MODIFY COLUMN `email_digest_mode` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT 'digest' COMMENT '邮件摘要模式';
ALTER TABLE `notification_preference` MODIFY COLUMN `email_enabled` tinyint NOT NULL DEFAULT 1 COMMENT '是否接收邮件通知';
ALTER TABLE `notification_preference` MODIFY COLUMN `event_type` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '*' COMMENT '通知事件类型';
ALTER TABLE `notification_preference` MODIFY COLUMN `in_app_enabled` tinyint NOT NULL DEFAULT 1 COMMENT '是否接收站内通知';
ALTER TABLE `notification_preference` MODIFY COLUMN `quiet_end` varchar(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '静默时段结束时间';
ALTER TABLE `notification_preference` MODIFY COLUMN `quiet_start` varchar(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '静默时段开始时间';
ALTER TABLE `notification_preference` MODIFY COLUMN `user_id` bigint unsigned NOT NULL COMMENT '用户ID';
ALTER TABLE `role` COMMENT = '角色表';
ALTER TABLE `role` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE `role` MODIFY COLUMN `name` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '角色名称';
ALTER TABLE `social_user` COMMENT = '第三方用户身份表';
ALTER TABLE `social_user` MODIFY COLUMN `access_token` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '第三方授权令牌';
ALTER TABLE `social_user` MODIFY COLUMN `created_at` datetime(3) NULL DEFAULT NULL COMMENT '创建时间';
ALTER TABLE `social_user` MODIFY COLUMN `deleted_at` datetime(3) NULL DEFAULT NULL COMMENT '软删除时间';
ALTER TABLE `social_user` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE `social_user` MODIFY COLUMN `is_active` tinyint NULL DEFAULT 1 COMMENT '第三方身份是否有效';
ALTER TABLE `social_user` MODIFY COLUMN `open_id` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '第三方OpenID';
ALTER TABLE `social_user` MODIFY COLUMN `refresh_token` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '第三方刷新令牌';
ALTER TABLE `social_user` MODIFY COLUMN `source` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '第三方来源平台';
ALTER TABLE `social_user` MODIFY COLUMN `updated_at` datetime(3) NULL DEFAULT NULL COMMENT '更新时间';
ALTER TABLE `social_user` MODIFY COLUMN `uuid` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '第三方系统唯一ID';
ALTER TABLE `social_user_auth` COMMENT = '用户第三方身份绑定表';
ALTER TABLE `social_user_auth` MODIFY COLUMN `created_at` datetime(3) NULL DEFAULT NULL COMMENT '创建时间';
ALTER TABLE `social_user_auth` MODIFY COLUMN `deleted_at` datetime(3) NULL DEFAULT NULL COMMENT '软删除时间';
ALTER TABLE `social_user_auth` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE `social_user_auth` MODIFY COLUMN `social_user_id` bigint unsigned NOT NULL COMMENT '第三方用户身份ID';
ALTER TABLE `social_user_auth` MODIFY COLUMN `updated_at` datetime(3) NULL DEFAULT NULL COMMENT '更新时间';
ALTER TABLE `social_user_auth` MODIFY COLUMN `user_id` bigint unsigned NOT NULL COMMENT '系统用户ID';
ALTER TABLE `tag` COMMENT = '标签表';
ALTER TABLE `tag` MODIFY COLUMN `cover_img_url` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '标签封面图URL';
ALTER TABLE `tag` MODIFY COLUMN `created_at` datetime(3) NULL DEFAULT NULL COMMENT '创建时间';
ALTER TABLE `tag` MODIFY COLUMN `deleted_at` datetime(3) NULL DEFAULT NULL COMMENT '软删除时间';
ALTER TABLE `tag` MODIFY COLUMN `description` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '标签描述';
ALTER TABLE `tag` MODIFY COLUMN `icon` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '标签图标URL';
ALTER TABLE `tag` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE `tag` MODIFY COLUMN `name` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '标签名称';
ALTER TABLE `tag` MODIFY COLUMN `seq` bigint NULL DEFAULT 0 COMMENT '展示排序';
ALTER TABLE `tag` MODIFY COLUMN `updated_at` datetime(3) NULL DEFAULT NULL COMMENT '更新时间';
ALTER TABLE `tag` MODIFY COLUMN `url` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '标签路由别名';
ALTER TABLE `user` COMMENT = '用户账号表';
ALTER TABLE `user` MODIFY COLUMN `avatar_url` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '头像URL';
ALTER TABLE `user` MODIFY COLUMN `created_at` datetime(3) NULL DEFAULT NULL COMMENT '创建时间';
ALTER TABLE `user` MODIFY COLUMN `deleted_at` datetime(3) NULL DEFAULT NULL COMMENT '软删除时间';
ALTER TABLE `user` MODIFY COLUMN `email` varchar(155) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '绑定邮箱';
ALTER TABLE `user` MODIFY COLUMN `email_verified_at` datetime(3) NULL DEFAULT NULL COMMENT '主邮箱验证时间';
ALTER TABLE `user` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE `user` MODIFY COLUMN `last_active_at` datetime(3) NULL DEFAULT NULL COMMENT '最后活跃时间';
ALTER TABLE `user` MODIFY COLUMN `last_login_at` datetime(3) NULL DEFAULT NULL COMMENT '最后登录时间';
ALTER TABLE `user` MODIFY COLUMN `mark` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT '注册会员' COMMENT '身份标签';
ALTER TABLE `user` MODIFY COLUMN `nickname` varchar(150) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '用户昵称';
ALTER TABLE `user` MODIFY COLUMN `password` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '密码哈希';
ALTER TABLE `user` MODIFY COLUMN `password_set` tinyint NOT NULL DEFAULT 1 COMMENT '是否已设置登录密码';
ALTER TABLE `user` MODIFY COLUMN `phone` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '绑定手机号';
ALTER TABLE `user` MODIFY COLUMN `site` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '个人站点地址';
ALTER TABLE `user` MODIFY COLUMN `status` tinyint NULL DEFAULT 1 COMMENT '账号状态';
ALTER TABLE `user` MODIFY COLUMN `updated_at` datetime(3) NULL DEFAULT NULL COMMENT '更新时间';
ALTER TABLE `user` MODIFY COLUMN `username` varchar(155) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '登录账号';
ALTER TABLE `user_like` COMMENT = '用户点赞记录表';
ALTER TABLE `user_like` MODIFY COLUMN `created_at` datetime(3) NULL DEFAULT NULL COMMENT '创建时间';
ALTER TABLE `user_like` MODIFY COLUMN `deleted_at` datetime(3) NULL DEFAULT NULL COMMENT '软删除时间';
ALTER TABLE `user_like` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE `user_like` MODIFY COLUMN `target_id` bigint unsigned NOT NULL COMMENT '被点赞目标ID';
ALTER TABLE `user_like` MODIFY COLUMN `type` tinyint NOT NULL COMMENT '被点赞目标类型';
ALTER TABLE `user_like` MODIFY COLUMN `updated_at` datetime(3) NULL DEFAULT NULL COMMENT '更新时间';
ALTER TABLE `user_like` MODIFY COLUMN `user_id` bigint unsigned NOT NULL COMMENT '用户ID';
ALTER TABLE `user_meta` COMMENT = '用户扩展资料表';
ALTER TABLE `user_meta` MODIFY COLUMN `address` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '详细地址';
ALTER TABLE `user_meta` MODIFY COLUMN `birthday` date NULL DEFAULT NULL COMMENT '生日';
ALTER TABLE `user_meta` MODIFY COLUMN `city` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '城市';
ALTER TABLE `user_meta` MODIFY COLUMN `country` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT '中国' COMMENT '国家';
ALTER TABLE `user_meta` MODIFY COLUMN `created_at` datetime(3) NULL DEFAULT NULL COMMENT '创建时间';
ALTER TABLE `user_meta` MODIFY COLUMN `description` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '个人简介';
ALTER TABLE `user_meta` MODIFY COLUMN `gender` tinyint NULL DEFAULT NULL COMMENT '性别';
ALTER TABLE `user_meta` MODIFY COLUMN `id_card` varchar(60) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '身份证号';
ALTER TABLE `user_meta` MODIFY COLUMN `name` varchar(155) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '真实姓名';
ALTER TABLE `user_meta` MODIFY COLUMN `province` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '省份';
ALTER TABLE `user_meta` MODIFY COLUMN `sub_email` varchar(155) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '副邮箱';
ALTER TABLE `user_meta` MODIFY COLUMN `sub_email_verified_at` datetime(3) NULL DEFAULT NULL COMMENT '副邮箱验证时间';
ALTER TABLE `user_meta` MODIFY COLUMN `updated_at` datetime(3) NULL DEFAULT NULL COMMENT '更新时间';
ALTER TABLE `user_meta` MODIFY COLUMN `user_id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '用户ID';
ALTER TABLE `user_moderation_profile` COMMENT = '用户审核画像表';
ALTER TABLE `user_moderation_profile` MODIFY COLUMN `clean_approval_streak` bigint unsigned NOT NULL DEFAULT 0 COMMENT '连续干净通过次数';
ALTER TABLE `user_moderation_profile` MODIFY COLUMN `corrected_count` bigint unsigned NOT NULL DEFAULT 0 COMMENT '被修正次数';
ALTER TABLE `user_moderation_profile` MODIFY COLUMN `created_at` datetime(3) NOT NULL COMMENT '创建时间';
ALTER TABLE `user_moderation_profile` MODIFY COLUMN `high_risk_count` bigint unsigned NOT NULL DEFAULT 0 COMMENT '高风险次数';
ALTER TABLE `user_moderation_profile` MODIFY COLUMN `last_violation_at` datetime(3) NULL DEFAULT NULL COMMENT '最后违规时间';
ALTER TABLE `user_moderation_profile` MODIFY COLUMN `manual_trust_locked` tinyint(1) NOT NULL DEFAULT 0 COMMENT '是否手动锁定信任';
ALTER TABLE `user_moderation_profile` MODIFY COLUMN `rejected_count` bigint unsigned NOT NULL DEFAULT 0 COMMENT '被拒绝次数';
ALTER TABLE `user_moderation_profile` MODIFY COLUMN `restricted_until` datetime(3) NULL DEFAULT NULL COMMENT '限制截止时间';
ALTER TABLE `user_moderation_profile` MODIFY COLUMN `sanction_reason` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '处置原因';
ALTER TABLE `user_moderation_profile` MODIFY COLUMN `sanction_state` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'active' COMMENT '处置状态';
ALTER TABLE `user_moderation_profile` MODIFY COLUMN `sanction_until` datetime(3) NULL DEFAULT NULL COMMENT '处置截止时间';
ALTER TABLE `user_moderation_profile` MODIFY COLUMN `trust_level` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'new' COMMENT '信任等级';
ALTER TABLE `user_moderation_profile` MODIFY COLUMN `trust_source` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'auto' COMMENT '信任来源';
ALTER TABLE `user_moderation_profile` MODIFY COLUMN `updated_at` datetime(3) NOT NULL COMMENT '更新时间';
ALTER TABLE `user_moderation_profile` MODIFY COLUMN `user_id` bigint unsigned NOT NULL COMMENT '用户ID';
ALTER TABLE `user_moderation_profile` MODIFY COLUMN `violation_score` bigint NOT NULL DEFAULT 0 COMMENT '违规分数';
ALTER TABLE `user_role` COMMENT = '用户角色关联表';
ALTER TABLE `user_role` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE `user_role` MODIFY COLUMN `role_id` bigint unsigned NOT NULL COMMENT '角色ID';
ALTER TABLE `user_role` MODIFY COLUMN `user_id` bigint unsigned NOT NULL COMMENT '用户ID';
ALTER TABLE `user_setting` COMMENT = '用户偏好设置表';
ALTER TABLE `user_setting` MODIFY COLUMN `created_at` datetime(3) NULL DEFAULT NULL COMMENT '创建时间';
ALTER TABLE `user_setting` MODIFY COLUMN `dark_mode` tinyint NULL DEFAULT 0 COMMENT '暗黑模式偏好';
ALTER TABLE `user_setting` MODIFY COLUMN `mail_receive` tinyint NULL DEFAULT 1 COMMENT '接收邮件邮箱来源';
ALTER TABLE `user_setting` MODIFY COLUMN `mail_show` tinyint NULL DEFAULT 1 COMMENT '对外显示邮箱来源';
ALTER TABLE `user_setting` MODIFY COLUMN `receive_mail` tinyint NULL DEFAULT 1 COMMENT '是否接收邮件';
ALTER TABLE `user_setting` MODIFY COLUMN `show_age` tinyint NULL DEFAULT 1 COMMENT '是否展示年龄';
ALTER TABLE `user_setting` MODIFY COLUMN `show_bili` tinyint NULL DEFAULT 0 COMMENT '是否展示B站';
ALTER TABLE `user_setting` MODIFY COLUMN `show_name` tinyint NULL DEFAULT 0 COMMENT '是否展示真实姓名';
ALTER TABLE `user_setting` MODIFY COLUMN `show_phone` tinyint NULL DEFAULT 0 COMMENT '是否展示手机号';
ALTER TABLE `user_setting` MODIFY COLUMN `show_position` tinyint NULL DEFAULT 1 COMMENT '是否展示所在位置';
ALTER TABLE `user_setting` MODIFY COLUMN `show_qq` tinyint NULL DEFAULT 0 COMMENT '是否展示QQ';
ALTER TABLE `user_setting` MODIFY COLUMN `show_sina` tinyint NULL DEFAULT 0 COMMENT '是否展示微博';
ALTER TABLE `user_setting` MODIFY COLUMN `show_wechat` tinyint NULL DEFAULT 0 COMMENT '是否展示微信';
ALTER TABLE `user_setting` MODIFY COLUMN `show_zhihu` tinyint NULL DEFAULT 0 COMMENT '是否展示知乎';
ALTER TABLE `user_setting` MODIFY COLUMN `updated_at` datetime(3) NULL DEFAULT NULL COMMENT '更新时间';
ALTER TABLE `user_setting` MODIFY COLUMN `user_id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '用户ID';
ALTER TABLE `user_social_link` COMMENT = '用户社交链接表';
ALTER TABLE `user_social_link` MODIFY COLUMN `created_at` datetime(3) NULL DEFAULT NULL COMMENT '创建时间';
ALTER TABLE `user_social_link` MODIFY COLUMN `deleted_at` datetime(3) NULL DEFAULT NULL COMMENT '软删除时间';
ALTER TABLE `user_social_link` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE `user_social_link` MODIFY COLUMN `platform` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '社交平台标识';
ALTER TABLE `user_social_link` MODIFY COLUMN `updated_at` datetime(3) NULL DEFAULT NULL COMMENT '更新时间';
ALTER TABLE `user_social_link` MODIFY COLUMN `url` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '社交账号链接或账号值';
ALTER TABLE `user_social_link` MODIFY COLUMN `user_id` bigint unsigned NOT NULL COMMENT '用户ID';
