// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vpt/blog-backend/internal/repository/category (interfaces: CategoryRepository)
//
// Generated by this command:
//
//	mockgen -destination=internal/repository/category/mock/mock_category_repository.go -package=mock github.com/vpt/blog-backend/internal/repository/category CategoryRepository
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	model "github.com/vpt/blog-backend/internal/model"
	category "github.com/vpt/blog-backend/internal/repository/category"
	gomock "go.uber.org/mock/gomock"
)

// MockCategoryRepository is a mock of CategoryRepository interface.
type MockCategoryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCategoryRepositoryMockRecorder
	isgomock struct{}
}

// MockCategoryRepositoryMockRecorder is the mock recorder for MockCategoryRepository.
type MockCategoryRepositoryMockRecorder struct {
	mock *MockCategoryRepository
}

// NewMockCategoryRepository creates a new mock instance.
func NewMockCategoryRepository(ctrl *gomock.Controller) *MockCategoryRepository {
	mock := &MockCategoryRepository{ctrl: ctrl}
	mock.recorder = &MockCategoryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCategoryRepository) EXPECT() *MockCategoryRepositoryMockRecorder {
	return m.recorder
}

// AddArticles mocks base method.
func (m *MockCategoryRepository) AddArticles(categoryID uint, articleIDs []uint) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddArticles", categoryID, articleIDs)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddArticles indicates an expected call of AddArticles.
func (mr *MockCategoryRepositoryMockRecorder) AddArticles(categoryID, articleIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddArticles", reflect.TypeOf((*MockCategoryRepository)(nil).AddArticles), categoryID, articleIDs)
}

// Create mocks base method.
func (m *MockCategoryRepository) Create(arg0 model.Category) (*category.CategoryWithCount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0)
	ret0, _ := ret[0].(*category.CategoryWithCount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockCategoryRepositoryMockRecorder) Create(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCategoryRepository)(nil).Create), arg0)
}

// Delete mocks base method.
func (m *MockCategoryRepository) Delete(id uint) (*model.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(*model.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockCategoryRepositoryMockRecorder) Delete(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCategoryRepository)(nil).Delete), id)
}

// ListWithArticleCount mocks base method.
func (m *MockCategoryRepository) ListWithArticleCount() ([]category.CategoryWithCount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListWithArticleCount")
	ret0, _ := ret[0].([]category.CategoryWithCount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListWithArticleCount indicates an expected call of ListWithArticleCount.
func (mr *MockCategoryRepositoryMockRecorder) ListWithArticleCount() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListWithArticleCount", reflect.TypeOf((*MockCategoryRepository)(nil).ListWithArticleCount))
}

// RemoveArticles mocks base method.
func (m *MockCategoryRepository) RemoveArticles(categoryID uint, articleIDs []uint) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveArticles", categoryID, articleIDs)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveArticles indicates an expected call of RemoveArticles.
func (mr *MockCategoryRepositoryMockRecorder) RemoveArticles(categoryID, articleIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveArticles", reflect.TypeOf((*MockCategoryRepository)(nil).RemoveArticles), categoryID, articleIDs)
}

// Update mocks base method.
func (m *MockCategoryRepository) Update(id uint, data category.CategoryUpdateData) (*category.CategoryWithCount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", id, data)
	ret0, _ := ret[0].(*category.CategoryWithCount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockCategoryRepositoryMockRecorder) Update(id, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCategoryRepository)(nil).Update), id, data)
}
