// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/moderation/service.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/moderation/service.go -destination=internal/service/moderation/mock/mock_service.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	moderation "github.com/vpt/blog-backend/internal/service/moderation"
	gomock "go.uber.org/mock/gomock"
)

// MockPolicyDecider is a mock of PolicyDecider interface.
type MockPolicyDecider struct {
	ctrl     *gomock.Controller
	recorder *MockPolicyDeciderMockRecorder
	isgomock struct{}
}

// MockPolicyDeciderMockRecorder is the mock recorder for MockPolicyDecider.
type MockPolicyDeciderMockRecorder struct {
	mock *MockPolicyDecider
}

// NewMockPolicyDecider creates a new mock instance.
func NewMockPolicyDecider(ctrl *gomock.Controller) *MockPolicyDecider {
	mock := &MockPolicyDecider{ctrl: ctrl}
	mock.recorder = &MockPolicyDeciderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPolicyDecider) EXPECT() *MockPolicyDeciderMockRecorder {
	return m.recorder
}

// Decide mocks base method.
func (m *MockPolicyDecider) Decide(input moderation.PolicyInput) (moderation.PolicyAction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Decide", input)
	ret0, _ := ret[0].(moderation.PolicyAction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Decide indicates an expected call of Decide.
func (mr *MockPolicyDeciderMockRecorder) Decide(input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Decide", reflect.TypeOf((*MockPolicyDecider)(nil).Decide), input)
}

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// AssertCanInteract mocks base method.
func (m *MockService) AssertCanInteract(ctx context.Context, ref moderation.SubjectRef) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssertCanInteract", ctx, ref)
	ret0, _ := ret[0].(error)
	return ret0
}

// AssertCanInteract indicates an expected call of AssertCanInteract.
func (mr *MockServiceMockRecorder) AssertCanInteract(ctx, ref any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssertCanInteract", reflect.TypeOf((*MockService)(nil).AssertCanInteract), ctx, ref)
}

// Delete mocks base method.
func (m *MockService) Delete(ctx context.Context, cmd moderation.DeleteCommand) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, cmd)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockServiceMockRecorder) Delete(ctx, cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockService)(nil).Delete), ctx, cmd)
}

// Edit mocks base method.
func (m *MockService) Edit(ctx context.Context, cmd moderation.EditCommand) (moderation.SubmitResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Edit", ctx, cmd)
	ret0, _ := ret[0].(moderation.SubmitResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Edit indicates an expected call of Edit.
func (mr *MockServiceMockRecorder) Edit(ctx, cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Edit", reflect.TypeOf((*MockService)(nil).Edit), ctx, cmd)
}

// LoadViews mocks base method.
func (m *MockService) LoadViews(ctx context.Context, refs []moderation.SubjectRef, viewer moderation.Viewer) (map[moderation.SubjectKey]moderation.View, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadViews", ctx, refs, viewer)
	ret0, _ := ret[0].(map[moderation.SubjectKey]moderation.View)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadViews indicates an expected call of LoadViews.
func (mr *MockServiceMockRecorder) LoadViews(ctx, refs, viewer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadViews", reflect.TypeOf((*MockService)(nil).LoadViews), ctx, refs, viewer)
}

// Submit mocks base method.
func (m *MockService) Submit(ctx context.Context, cmd moderation.SubmitCommand) (moderation.SubmitResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Submit", ctx, cmd)
	ret0, _ := ret[0].(moderation.SubmitResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Submit indicates an expected call of Submit.
func (mr *MockServiceMockRecorder) Submit(ctx, cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Submit", reflect.TypeOf((*MockService)(nil).Submit), ctx, cmd)
}
