// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vpt/blog-backend/internal/repository/tag (interfaces: TagRepository)
//
// Generated by this command:
//
//	mockgen -destination=internal/repository/tag/mock/mock_tag_repository.go -package=mock github.com/vpt/blog-backend/internal/repository/tag TagRepository
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	model "github.com/vpt/blog-backend/internal/model"
	tag "github.com/vpt/blog-backend/internal/repository/tag"
	gomock "go.uber.org/mock/gomock"
)

// MockTagRepository is a mock of TagRepository interface.
type MockTagRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTagRepositoryMockRecorder
	isgomock struct{}
}

// MockTagRepositoryMockRecorder is the mock recorder for MockTagRepository.
type MockTagRepositoryMockRecorder struct {
	mock *MockTagRepository
}

// NewMockTagRepository creates a new mock instance.
func NewMockTagRepository(ctrl *gomock.Controller) *MockTagRepository {
	mock := &MockTagRepository{ctrl: ctrl}
	mock.recorder = &MockTagRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTagRepository) EXPECT() *MockTagRepositoryMockRecorder {
	return m.recorder
}

// AddArticles mocks base method.
func (m *MockTagRepository) AddArticles(tagID uint, articleIDs []uint) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddArticles", tagID, articleIDs)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddArticles indicates an expected call of AddArticles.
func (mr *MockTagRepositoryMockRecorder) AddArticles(tagID, articleIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddArticles", reflect.TypeOf((*MockTagRepository)(nil).AddArticles), tagID, articleIDs)
}

// Create mocks base method.
func (m *MockTagRepository) Create(arg0 model.Tag) (*tag.TagWithCount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0)
	ret0, _ := ret[0].(*tag.TagWithCount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockTagRepositoryMockRecorder) Create(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTagRepository)(nil).Create), arg0)
}

// Delete mocks base method.
func (m *MockTagRepository) Delete(id uint) (*model.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(*model.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockTagRepositoryMockRecorder) Delete(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTagRepository)(nil).Delete), id)
}

// FindWithArticleCount mocks base method.
func (m *MockTagRepository) FindWithArticleCount(id uint) (*tag.TagWithCount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindWithArticleCount", id)
	ret0, _ := ret[0].(*tag.TagWithCount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindWithArticleCount indicates an expected call of FindWithArticleCount.
func (mr *MockTagRepositoryMockRecorder) FindWithArticleCount(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindWithArticleCount", reflect.TypeOf((*MockTagRepository)(nil).FindWithArticleCount), id)
}

// ListWithArticleCount mocks base method.
func (m *MockTagRepository) ListWithArticleCount() ([]tag.TagWithCount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListWithArticleCount")
	ret0, _ := ret[0].([]tag.TagWithCount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListWithArticleCount indicates an expected call of ListWithArticleCount.
func (mr *MockTagRepositoryMockRecorder) ListWithArticleCount() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListWithArticleCount", reflect.TypeOf((*MockTagRepository)(nil).ListWithArticleCount))
}

// RemoveArticles mocks base method.
func (m *MockTagRepository) RemoveArticles(tagID uint, articleIDs []uint) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveArticles", tagID, articleIDs)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveArticles indicates an expected call of RemoveArticles.
func (mr *MockTagRepositoryMockRecorder) RemoveArticles(tagID, articleIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveArticles", reflect.TypeOf((*MockTagRepository)(nil).RemoveArticles), tagID, articleIDs)
}

// Update mocks base method.
func (m *MockTagRepository) Update(id uint, data tag.TagUpdateData) (*tag.TagWithCount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", id, data)
	ret0, _ := ret[0].(*tag.TagWithCount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockTagRepositoryMockRecorder) Update(id, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTagRepository)(nil).Update), id, data)
}
