// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vpt/blog-backend/internal/repository (interfaces: ArticleRepository)

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	model "github.com/vpt/blog-backend/internal/model"
	repository "github.com/vpt/blog-backend/internal/repository"
	gomock "go.uber.org/mock/gomock"
)

// MockArticleRepository is a mock of ArticleRepository interface.
type MockArticleRepository struct {
	ctrl     *gomock.Controller
	recorder *MockArticleRepositoryMockRecorder
	isgomock struct{}
}

// MockArticleRepositoryMockRecorder is the mock recorder for MockArticleRepository.
type MockArticleRepositoryMockRecorder struct {
	mock *MockArticleRepository
}

// NewMockArticleRepository creates a new mock instance.
func NewMockArticleRepository(ctrl *gomock.Controller) *MockArticleRepository {
	mock := &MockArticleRepository{ctrl: ctrl}
	mock.recorder = &MockArticleRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockArticleRepository) EXPECT() *MockArticleRepositoryMockRecorder {
	return m.recorder
}

func (m *MockArticleRepository) ListPublic(filter repository.ArticleListFilter) (*repository.ArticlePageResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPublic", filter)
	ret0, _ := ret[0].(*repository.ArticlePageResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockArticleRepositoryMockRecorder) ListPublic(filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPublic", reflect.TypeOf((*MockArticleRepository)(nil).ListPublic), filter)
}

func (m *MockArticleRepository) ListPublicIDs() ([]uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPublicIDs")
	ret0, _ := ret[0].([]uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockArticleRepositoryMockRecorder) ListPublicIDs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPublicIDs", reflect.TypeOf((*MockArticleRepository)(nil).ListPublicIDs))
}

func (m *MockArticleRepository) FindPublicDetail(id uint, viewerID *uint) (*repository.ArticleAggregate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPublicDetail", id, viewerID)
	ret0, _ := ret[0].(*repository.ArticleAggregate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockArticleRepositoryMockRecorder) FindPublicDetail(id, viewerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPublicDetail", reflect.TypeOf((*MockArticleRepository)(nil).FindPublicDetail), id, viewerID)
}

func (m *MockArticleRepository) FindAdminDetail(id uint, viewerID *uint) (*repository.ArticleAggregate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAdminDetail", id, viewerID)
	ret0, _ := ret[0].(*repository.ArticleAggregate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockArticleRepositoryMockRecorder) FindAdminDetail(id, viewerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAdminDetail", reflect.TypeOf((*MockArticleRepository)(nil).FindAdminDetail), id, viewerID)
}

func (m *MockArticleRepository) Save(data repository.ArticleSaveData) (*repository.ArticleAggregate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", data)
	ret0, _ := ret[0].(*repository.ArticleAggregate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockArticleRepositoryMockRecorder) Save(data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockArticleRepository)(nil).Save), data)
}

func (m *MockArticleRepository) SoftDelete(id uint) (*model.Article, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDelete", id)
	ret0, _ := ret[0].(*model.Article)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockArticleRepositoryMockRecorder) SoftDelete(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDelete", reflect.TypeOf((*MockArticleRepository)(nil).SoftDelete), id)
}

func (m *MockArticleRepository) IncrementReadCount(id uint) (*model.Article, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementReadCount", id)
	ret0, _ := ret[0].(*model.Article)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockArticleRepositoryMockRecorder) IncrementReadCount(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementReadCount", reflect.TypeOf((*MockArticleRepository)(nil).IncrementReadCount), id)
}

func (m *MockArticleRepository) IsLiked(articleID uint, userID uint) (bool, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsLiked", articleID, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

func (mr *MockArticleRepositoryMockRecorder) IsLiked(articleID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsLiked", reflect.TypeOf((*MockArticleRepository)(nil).IsLiked), articleID, userID)
}

func (m *MockArticleRepository) ToggleLike(articleID uint, userID uint) (*repository.ArticleAggregate, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToggleLike", articleID, userID)
	ret0, _ := ret[0].(*repository.ArticleAggregate)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

func (mr *MockArticleRepositoryMockRecorder) ToggleLike(articleID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToggleLike", reflect.TypeOf((*MockArticleRepository)(nil).ToggleLike), articleID, userID)
}
