// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vpt/blog-backend/internal/repository (interfaces: UserRepository)
//
// Generated by this command:
//
//	mockgen -destination=internal/repository/mock/mock_user_repository.go -package=mock github.com/vpt/blog-backend/internal/repository UserRepository
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	model "github.com/vpt/blog-backend/internal/model"
	repository "github.com/vpt/blog-backend/internal/repository"
	gomock "go.uber.org/mock/gomock"
)

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
	isgomock struct{}
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockUserRepository) Create(user *model.User, roleID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", user, roleID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockUserRepositoryMockRecorder) Create(user, roleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserRepository)(nil).Create), user, roleID)
}

// ExistsByEmail mocks base method.
func (m *MockUserRepository) ExistsByEmail(email string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsByEmail", email)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsByEmail indicates an expected call of ExistsByEmail.
func (mr *MockUserRepositoryMockRecorder) ExistsByEmail(email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsByEmail", reflect.TypeOf((*MockUserRepository)(nil).ExistsByEmail), email)
}

// ExistsByNickname mocks base method.
func (m *MockUserRepository) ExistsByNickname(nickname string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsByNickname", nickname)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsByNickname indicates an expected call of ExistsByNickname.
func (mr *MockUserRepositoryMockRecorder) ExistsByNickname(nickname any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsByNickname", reflect.TypeOf((*MockUserRepository)(nil).ExistsByNickname), nickname)
}

// FindByID mocks base method.
func (m *MockUserRepository) FindByID(id uint) (*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", id)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockUserRepositoryMockRecorder) FindByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockUserRepository)(nil).FindByID), id)
}

// FindDetailByID mocks base method.
func (m *MockUserRepository) FindDetailByID(id uint) (*repository.UserDetailAggregate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindDetailByID", id)
	ret0, _ := ret[0].(*repository.UserDetailAggregate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindDetailByID indicates an expected call of FindDetailByID.
func (mr *MockUserRepositoryMockRecorder) FindDetailByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindDetailByID", reflect.TypeOf((*MockUserRepository)(nil).FindDetailByID), id)
}

// FindByIdentifier mocks base method.
func (m *MockUserRepository) FindByIdentifier(identifier string) (*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByIdentifier", identifier)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByIdentifier indicates an expected call of FindByIdentifier.
func (mr *MockUserRepositoryMockRecorder) FindByIdentifier(identifier any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByIdentifier", reflect.TypeOf((*MockUserRepository)(nil).FindByIdentifier), identifier)
}

// FindRolesByUserID mocks base method.
func (m *MockUserRepository) FindRolesByUserID(userID uint) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindRolesByUserID", userID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindRolesByUserID indicates an expected call of FindRolesByUserID.
func (mr *MockUserRepositoryMockRecorder) FindRolesByUserID(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindRolesByUserID", reflect.TypeOf((*MockUserRepository)(nil).FindRolesByUserID), userID)
}

// FindRolesByUserIDs mocks base method.
func (m *MockUserRepository) FindRolesByUserIDs(userIDs []uint) (map[uint][]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindRolesByUserIDs", userIDs)
	ret0, _ := ret[0].(map[uint][]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindRolesByUserIDs indicates an expected call of FindRolesByUserIDs.
func (mr *MockUserRepositoryMockRecorder) FindRolesByUserIDs(userIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindRolesByUserIDs", reflect.TypeOf((*MockUserRepository)(nil).FindRolesByUserIDs), userIDs)
}

// ListAll mocks base method.
func (m *MockUserRepository) ListAll(offset, limit int) ([]model.User, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAll", offset, limit)
	ret0, _ := ret[0].([]model.User)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListAll indicates an expected call of ListAll.
func (mr *MockUserRepositoryMockRecorder) ListAll(offset, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAll", reflect.TypeOf((*MockUserRepository)(nil).ListAll), offset, limit)
}

// ListRecent mocks base method.
func (m *MockUserRepository) ListRecent(offset, limit int) ([]model.User, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRecent", offset, limit)
	ret0, _ := ret[0].([]model.User)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListRecent indicates an expected call of ListRecent.
func (mr *MockUserRepositoryMockRecorder) ListRecent(offset, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRecent", reflect.TypeOf((*MockUserRepository)(nil).ListRecent), offset, limit)
}

// UpdateLastLoginAt mocks base method.
func (m *MockUserRepository) UpdateLastLoginAt(userID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLastLoginAt", userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLastLoginAt indicates an expected call of UpdateLastLoginAt.
func (mr *MockUserRepositoryMockRecorder) UpdateLastLoginAt(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLastLoginAt", reflect.TypeOf((*MockUserRepository)(nil).UpdateLastLoginAt), userID)
}

// Update mocks base method.
func (m *MockUserRepository) Update(id uint, updates map[string]interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", id, updates)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockUserRepositoryMockRecorder) Update(id, updates any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUserRepository)(nil).Update), id, updates)
}
