// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vpt/blog-backend/internal/repository (interfaces: CategoryRepository)

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	repository "github.com/vpt/blog-backend/internal/repository"
	gomock "go.uber.org/mock/gomock"
)

// MockCategoryRepository is a mock of CategoryRepository interface.
type MockCategoryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCategoryRepositoryMockRecorder
	isgomock struct{}
}

// MockCategoryRepositoryMockRecorder is the mock recorder for MockCategoryRepository.
type MockCategoryRepositoryMockRecorder struct {
	mock *MockCategoryRepository
}

// NewMockCategoryRepository creates a new mock instance.
func NewMockCategoryRepository(ctrl *gomock.Controller) *MockCategoryRepository {
	mock := &MockCategoryRepository{ctrl: ctrl}
	mock.recorder = &MockCategoryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCategoryRepository) EXPECT() *MockCategoryRepositoryMockRecorder {
	return m.recorder
}

// ListWithArticleCount mocks base method.
func (m *MockCategoryRepository) ListWithArticleCount() ([]repository.CategoryWithCount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListWithArticleCount")
	ret0, _ := ret[0].([]repository.CategoryWithCount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListWithArticleCount indicates an expected call of ListWithArticleCount.
func (mr *MockCategoryRepositoryMockRecorder) ListWithArticleCount() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListWithArticleCount", reflect.TypeOf((*MockCategoryRepository)(nil).ListWithArticleCount))
}
