// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vpt/blog-backend/internal/repository/user (interfaces: UserRepository)
//
// Generated by this command:
//
//	mockgen -destination=internal/repository/user/mock/mock_user_repository.go -package=mock github.com/vpt/blog-backend/internal/repository/user UserRepository
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	model "github.com/vpt/blog-backend/internal/model"
	user "github.com/vpt/blog-backend/internal/repository/user"
	gomock "go.uber.org/mock/gomock"
)

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
	isgomock struct{}
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// BatchFetchActiveLogin mocks base method.
func (m *MockUserRepository) BatchFetchActiveLogin(ids []uint) (map[uint]*user.ActiveLogin, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchFetchActiveLogin", ids)
	ret0, _ := ret[0].(map[uint]*user.ActiveLogin)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchFetchActiveLogin indicates an expected call of BatchFetchActiveLogin.
func (mr *MockUserRepositoryMockRecorder) BatchFetchActiveLogin(ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchFetchActiveLogin", reflect.TypeOf((*MockUserRepository)(nil).BatchFetchActiveLogin), ids)
}

// CountByAvatarURL mocks base method.
func (m *MockUserRepository) CountByAvatarURL(avatarURL string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByAvatarURL", avatarURL)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByAvatarURL indicates an expected call of CountByAvatarURL.
func (mr *MockUserRepositoryMockRecorder) CountByAvatarURL(avatarURL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByAvatarURL", reflect.TypeOf((*MockUserRepository)(nil).CountByAvatarURL), avatarURL)
}

// CountLikedContent mocks base method.
func (m *MockUserRepository) CountLikedContent(userID uint) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountLikedContent", userID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountLikedContent indicates an expected call of CountLikedContent.
func (mr *MockUserRepositoryMockRecorder) CountLikedContent(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountLikedContent", reflect.TypeOf((*MockUserRepository)(nil).CountLikedContent), userID)
}

// Create mocks base method.
func (m *MockUserRepository) Create(arg0 *model.User, roleID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, roleID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockUserRepositoryMockRecorder) Create(arg0, roleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserRepository)(nil).Create), arg0, roleID)
}

// DeleteSocialLink mocks base method.
func (m *MockUserRepository) DeleteSocialLink(userID uint, platform string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSocialLink", userID, platform)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSocialLink indicates an expected call of DeleteSocialLink.
func (mr *MockUserRepositoryMockRecorder) DeleteSocialLink(userID, platform any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSocialLink", reflect.TypeOf((*MockUserRepository)(nil).DeleteSocialLink), userID, platform)
}

// EmailInUseByOther mocks base method.
func (m *MockUserRepository) EmailInUseByOther(email string, excludeID uint) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EmailInUseByOther", email, excludeID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EmailInUseByOther indicates an expected call of EmailInUseByOther.
func (mr *MockUserRepositoryMockRecorder) EmailInUseByOther(email, excludeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EmailInUseByOther", reflect.TypeOf((*MockUserRepository)(nil).EmailInUseByOther), email, excludeID)
}

// ExistsByEmail mocks base method.
func (m *MockUserRepository) ExistsByEmail(email string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsByEmail", email)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsByEmail indicates an expected call of ExistsByEmail.
func (mr *MockUserRepositoryMockRecorder) ExistsByEmail(email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsByEmail", reflect.TypeOf((*MockUserRepository)(nil).ExistsByEmail), email)
}

// ExistsByNickname mocks base method.
func (m *MockUserRepository) ExistsByNickname(nickname string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsByNickname", nickname)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsByNickname indicates an expected call of ExistsByNickname.
func (mr *MockUserRepositoryMockRecorder) ExistsByNickname(nickname any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsByNickname", reflect.TypeOf((*MockUserRepository)(nil).ExistsByNickname), nickname)
}

// ExistsByUsername mocks base method.
func (m *MockUserRepository) ExistsByUsername(username string, excludeID uint) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsByUsername", username, excludeID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsByUsername indicates an expected call of ExistsByUsername.
func (mr *MockUserRepositoryMockRecorder) ExistsByUsername(username, excludeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsByUsername", reflect.TypeOf((*MockUserRepository)(nil).ExistsByUsername), username, excludeID)
}

// FindByEmail mocks base method.
func (m *MockUserRepository) FindByEmail(email string) (*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByEmail", email)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByEmail indicates an expected call of FindByEmail.
func (mr *MockUserRepositoryMockRecorder) FindByEmail(email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByEmail", reflect.TypeOf((*MockUserRepository)(nil).FindByEmail), email)
}

// FindByID mocks base method.
func (m *MockUserRepository) FindByID(id uint) (*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", id)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockUserRepositoryMockRecorder) FindByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockUserRepository)(nil).FindByID), id)
}

// FindByIdentifier mocks base method.
func (m *MockUserRepository) FindByIdentifier(identifier string) (*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByIdentifier", identifier)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByIdentifier indicates an expected call of FindByIdentifier.
func (mr *MockUserRepositoryMockRecorder) FindByIdentifier(identifier any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByIdentifier", reflect.TypeOf((*MockUserRepository)(nil).FindByIdentifier), identifier)
}

// FindByUsername mocks base method.
func (m *MockUserRepository) FindByUsername(username string) (*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUsername", username)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUsername indicates an expected call of FindByUsername.
func (mr *MockUserRepositoryMockRecorder) FindByUsername(username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUsername", reflect.TypeOf((*MockUserRepository)(nil).FindByUsername), username)
}

// FindDetailByID mocks base method.
func (m *MockUserRepository) FindDetailByID(id uint) (*user.UserDetailAggregate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindDetailByID", id)
	ret0, _ := ret[0].(*user.UserDetailAggregate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindDetailByID indicates an expected call of FindDetailByID.
func (mr *MockUserRepositoryMockRecorder) FindDetailByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindDetailByID", reflect.TypeOf((*MockUserRepository)(nil).FindDetailByID), id)
}

// FindRolesByUserID mocks base method.
func (m *MockUserRepository) FindRolesByUserID(userID uint) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindRolesByUserID", userID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindRolesByUserID indicates an expected call of FindRolesByUserID.
func (mr *MockUserRepositoryMockRecorder) FindRolesByUserID(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindRolesByUserID", reflect.TypeOf((*MockUserRepository)(nil).FindRolesByUserID), userID)
}

// FindRolesByUserIDs mocks base method.
func (m *MockUserRepository) FindRolesByUserIDs(userIDs []uint) (map[uint][]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindRolesByUserIDs", userIDs)
	ret0, _ := ret[0].(map[uint][]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindRolesByUserIDs indicates an expected call of FindRolesByUserIDs.
func (mr *MockUserRepositoryMockRecorder) FindRolesByUserIDs(userIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindRolesByUserIDs", reflect.TypeOf((*MockUserRepository)(nil).FindRolesByUserIDs), userIDs)
}

// GrantVipRole mocks base method.
func (m *MockUserRepository) GrantVipRole(userID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GrantVipRole", userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// GrantVipRole indicates an expected call of GrantVipRole.
func (mr *MockUserRepositoryMockRecorder) GrantVipRole(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GrantVipRole", reflect.TypeOf((*MockUserRepository)(nil).GrantVipRole), userID)
}

// ListAll mocks base method.
func (m *MockUserRepository) ListAll(offset, limit int) ([]model.User, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAll", offset, limit)
	ret0, _ := ret[0].([]model.User)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListAll indicates an expected call of ListAll.
func (mr *MockUserRepositoryMockRecorder) ListAll(offset, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAll", reflect.TypeOf((*MockUserRepository)(nil).ListAll), offset, limit)
}

// ListLikedContent mocks base method.
func (m *MockUserRepository) ListLikedContent(filter user.LikedContentFilter) (*user.LikedContentPageResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListLikedContent", filter)
	ret0, _ := ret[0].(*user.LikedContentPageResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListLikedContent indicates an expected call of ListLikedContent.
func (mr *MockUserRepositoryMockRecorder) ListLikedContent(filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListLikedContent", reflect.TypeOf((*MockUserRepository)(nil).ListLikedContent), filter)
}

// ListRecent mocks base method.
func (m *MockUserRepository) ListRecent(offset, limit int) ([]model.User, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRecent", offset, limit)
	ret0, _ := ret[0].([]model.User)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListRecent indicates an expected call of ListRecent.
func (mr *MockUserRepositoryMockRecorder) ListRecent(offset, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRecent", reflect.TypeOf((*MockUserRepository)(nil).ListRecent), offset, limit)
}

// RevokeVipRole mocks base method.
func (m *MockUserRepository) RevokeVipRole(userID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeVipRole", userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeVipRole indicates an expected call of RevokeVipRole.
func (mr *MockUserRepositoryMockRecorder) RevokeVipRole(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeVipRole", reflect.TypeOf((*MockUserRepository)(nil).RevokeVipRole), userID)
}

// TouchLoginPresence mocks base method.
func (m *MockUserRepository) TouchLoginPresence(userID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TouchLoginPresence", userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// TouchLoginPresence indicates an expected call of TouchLoginPresence.
func (mr *MockUserRepositoryMockRecorder) TouchLoginPresence(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TouchLoginPresence", reflect.TypeOf((*MockUserRepository)(nil).TouchLoginPresence), userID)
}

// Update mocks base method.
func (m *MockUserRepository) Update(id uint, updates map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", id, updates)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockUserRepositoryMockRecorder) Update(id, updates any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUserRepository)(nil).Update), id, updates)
}

// UpdateLastActiveAt mocks base method.
func (m *MockUserRepository) UpdateLastActiveAt(userID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLastActiveAt", userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLastActiveAt indicates an expected call of UpdateLastActiveAt.
func (mr *MockUserRepositoryMockRecorder) UpdateLastActiveAt(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLastActiveAt", reflect.TypeOf((*MockUserRepository)(nil).UpdateLastActiveAt), userID)
}

// UpdatePassword mocks base method.
func (m *MockUserRepository) UpdatePassword(userID uint, hashedPassword string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePassword", userID, hashedPassword)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePassword indicates an expected call of UpdatePassword.
func (mr *MockUserRepositoryMockRecorder) UpdatePassword(userID, hashedPassword any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePassword", reflect.TypeOf((*MockUserRepository)(nil).UpdatePassword), userID, hashedPassword)
}

// UpsertMeta mocks base method.
func (m *MockUserRepository) UpsertMeta(userID uint, updates map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertMeta", userID, updates)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertMeta indicates an expected call of UpsertMeta.
func (mr *MockUserRepositoryMockRecorder) UpsertMeta(userID, updates any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertMeta", reflect.TypeOf((*MockUserRepository)(nil).UpsertMeta), userID, updates)
}

// UpsertSocialLink mocks base method.
func (m *MockUserRepository) UpsertSocialLink(userID uint, platform, url string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertSocialLink", userID, platform, url)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertSocialLink indicates an expected call of UpsertSocialLink.
func (mr *MockUserRepositoryMockRecorder) UpsertSocialLink(userID, platform, url any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertSocialLink", reflect.TypeOf((*MockUserRepository)(nil).UpsertSocialLink), userID, platform, url)
}

// UpsertUserSetting mocks base method.
func (m *MockUserRepository) UpsertUserSetting(userID uint, updates map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertUserSetting", userID, updates)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertUserSetting indicates an expected call of UpsertUserSetting.
func (mr *MockUserRepositoryMockRecorder) UpsertUserSetting(userID, updates any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertUserSetting", reflect.TypeOf((*MockUserRepository)(nil).UpsertUserSetting), userID, updates)
}
