// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vpt/blog-backend/internal/repository/user (interfaces: AuthenticationRepository)
//
// Generated by this command:
//
//	mockgen -destination=internal/repository/user/mock/mock_authentication_repository.go -package=mock github.com/vpt/blog-backend/internal/repository/user AuthenticationRepository
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	model "github.com/vpt/blog-backend/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockAuthenticationRepository is a mock of AuthenticationRepository interface.
type MockAuthenticationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAuthenticationRepositoryMockRecorder
	isgomock struct{}
}

// MockAuthenticationRepositoryMockRecorder is the mock recorder for MockAuthenticationRepository.
type MockAuthenticationRepositoryMockRecorder struct {
	mock *MockAuthenticationRepository
}

// NewMockAuthenticationRepository creates a new mock instance.
func NewMockAuthenticationRepository(ctrl *gomock.Controller) *MockAuthenticationRepository {
	mock := &MockAuthenticationRepository{ctrl: ctrl}
	mock.recorder = &MockAuthenticationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthenticationRepository) EXPECT() *MockAuthenticationRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAuthenticationRepository) Create(ctx context.Context, user *model.User, roleID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, user, roleID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockAuthenticationRepositoryMockRecorder) Create(ctx, user, roleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAuthenticationRepository)(nil).Create), ctx, user, roleID)
}

// ExistsByEmail mocks base method.
func (m *MockAuthenticationRepository) ExistsByEmail(ctx context.Context, email string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsByEmail", ctx, email)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsByEmail indicates an expected call of ExistsByEmail.
func (mr *MockAuthenticationRepositoryMockRecorder) ExistsByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsByEmail", reflect.TypeOf((*MockAuthenticationRepository)(nil).ExistsByEmail), ctx, email)
}

// ExistsByNickname mocks base method.
func (m *MockAuthenticationRepository) ExistsByNickname(ctx context.Context, nickname string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsByNickname", ctx, nickname)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsByNickname indicates an expected call of ExistsByNickname.
func (mr *MockAuthenticationRepositoryMockRecorder) ExistsByNickname(ctx, nickname any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsByNickname", reflect.TypeOf((*MockAuthenticationRepository)(nil).ExistsByNickname), ctx, nickname)
}

// FindByEmail mocks base method.
func (m *MockAuthenticationRepository) FindByEmail(ctx context.Context, email string) (*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByEmail", ctx, email)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByEmail indicates an expected call of FindByEmail.
func (mr *MockAuthenticationRepositoryMockRecorder) FindByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByEmail", reflect.TypeOf((*MockAuthenticationRepository)(nil).FindByEmail), ctx, email)
}

// FindByIdentifier mocks base method.
func (m *MockAuthenticationRepository) FindByIdentifier(ctx context.Context, identifier string) (*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByIdentifier", ctx, identifier)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByIdentifier indicates an expected call of FindByIdentifier.
func (mr *MockAuthenticationRepositoryMockRecorder) FindByIdentifier(ctx, identifier any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByIdentifier", reflect.TypeOf((*MockAuthenticationRepository)(nil).FindByIdentifier), ctx, identifier)
}

// FindByUsername mocks base method.
func (m *MockAuthenticationRepository) FindByUsername(ctx context.Context, username string) (*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUsername", ctx, username)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUsername indicates an expected call of FindByUsername.
func (mr *MockAuthenticationRepositoryMockRecorder) FindByUsername(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUsername", reflect.TypeOf((*MockAuthenticationRepository)(nil).FindByUsername), ctx, username)
}

// FindRolesByUserID mocks base method.
func (m *MockAuthenticationRepository) FindRolesByUserID(ctx context.Context, userID uint) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindRolesByUserID", ctx, userID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindRolesByUserID indicates an expected call of FindRolesByUserID.
func (mr *MockAuthenticationRepositoryMockRecorder) FindRolesByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindRolesByUserID", reflect.TypeOf((*MockAuthenticationRepository)(nil).FindRolesByUserID), ctx, userID)
}

// TouchLoginPresence mocks base method.
func (m *MockAuthenticationRepository) TouchLoginPresence(ctx context.Context, userID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TouchLoginPresence", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// TouchLoginPresence indicates an expected call of TouchLoginPresence.
func (mr *MockAuthenticationRepositoryMockRecorder) TouchLoginPresence(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TouchLoginPresence", reflect.TypeOf((*MockAuthenticationRepository)(nil).TouchLoginPresence), ctx, userID)
}

// UpdatePassword mocks base method.
func (m *MockAuthenticationRepository) UpdatePassword(ctx context.Context, userID uint, hashedPassword string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePassword", ctx, userID, hashedPassword)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePassword indicates an expected call of UpdatePassword.
func (mr *MockAuthenticationRepositoryMockRecorder) UpdatePassword(ctx, userID, hashedPassword any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePassword", reflect.TypeOf((*MockAuthenticationRepository)(nil).UpdatePassword), ctx, userID, hashedPassword)
}
