// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vpt/blog-backend/internal/repository/adminlog (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -destination=internal/repository/adminlog/mock/mock_adminlog_repository.go -package=mock github.com/vpt/blog-backend/internal/repository/adminlog Repository
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	model "github.com/vpt/blog-backend/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRepository) Create(ctx context.Context, entry *model.AdminOperationLog) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, entry)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRepositoryMockRecorder) Create(ctx, entry any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepository)(nil).Create), ctx, entry)
}

// ListByTargetUser mocks base method.
func (m *MockRepository) ListByTargetUser(ctx context.Context, targetUserID uint, offset, limit int) ([]model.AdminOperationLog, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByTargetUser", ctx, targetUserID, offset, limit)
	ret0, _ := ret[0].([]model.AdminOperationLog)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListByTargetUser indicates an expected call of ListByTargetUser.
func (mr *MockRepositoryMockRecorder) ListByTargetUser(ctx, targetUserID, offset, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByTargetUser", reflect.TypeOf((*MockRepository)(nil).ListByTargetUser), ctx, targetUserID, offset, limit)
}
