package router

import (
	"github.com/gin-gonic/gin"
	"github.com/redis/go-redis/v9"

	"github.com/vpt/blog-backend/internal/middleware"
	"github.com/vpt/blog-backend/pkg/jwt"
	"github.com/vpt/blog-backend/pkg/roles"
)

func registerPublicRoutes(
	r *gin.Engine,
	handlers Handlers,
	jwtManager *jwt.Manager,
	redisClient *redis.Client,
) {
	r.GET("/health", middleware.RateLimitPublic(redisClient), handlers.Health.Check)
	r.GET("/test/public", middleware.RateLimitPublic(redisClient), handlers.Test.Public)
	r.POST("/test/token", handlers.Test.GenToken)

	r.POST("/captcha/register/challenge", handlers.Captcha.GenerateRegistrationChallenge)
	r.POST("/captcha/register/verify", handlers.Captcha.VerifyRegistrationChallenge)
	r.POST("/auth/send-code", middleware.RateLimitStrict(redisClient), handlers.Auth.SendCode)
	r.POST("/auth/password-reset/code", middleware.RateLimitStrict(redisClient), handlers.Auth.SendPasswordResetCode)
	r.POST("/auth/password-reset", middleware.RateLimitStrict(redisClient), handlers.Auth.ResetPassword)
	r.POST("/auth/register", middleware.RateLimitStrict(redisClient), handlers.Auth.Register)
	r.POST("/auth/login", middleware.RateLimitLoose(redisClient), handlers.Auth.Login)
	r.POST("/admin/auth/login", middleware.RateLimitLoose(redisClient), handlers.Auth.AdminLogin)
	r.POST("/auth/refresh", handlers.Auth.Refresh)
	r.GET("/oauth/providers", middleware.RateLimitPublic(redisClient), handlers.OAuth.Providers)
	r.GET("/oauth/:source/authorize", middleware.RateLimitLoose(redisClient), middleware.OptionalAuth(jwtManager), handlers.OAuth.Authorize)
	r.GET("/oauth/:source/callback", middleware.RateLimitLoose(redisClient), handlers.OAuth.Callback)
	r.GET("/categories", middleware.RateLimitPublic(redisClient), handlers.Category.ListTabs)
	r.GET("/tags", middleware.RateLimitPublic(redisClient), handlers.Tag.List)
	r.GET("/tags/:id", middleware.RateLimitPublic(redisClient), handlers.Tag.Get)
	r.GET("/tags/:id/articles", middleware.RateLimitPublic(redisClient), handlers.Tag.ListArticles)
	r.GET("/music", middleware.RateLimitPublic(redisClient), handlers.Music.List)
	r.GET("/music/artists", middleware.RateLimitPublic(redisClient), handlers.Music.ListArtists)
	r.GET("/music/artists/:id", middleware.RateLimitPublic(redisClient), handlers.Music.GetPublicArtist)
	r.GET("/music/albums", middleware.RateLimitPublic(redisClient), handlers.Music.ListAlbums)
	r.GET("/music/albums/:id", middleware.RateLimitPublic(redisClient), handlers.Music.GetPublicAlbum)
	r.GET("/music/:id", middleware.RateLimitPublic(redisClient), handlers.Music.GetPublicDetail)
	r.GET("/friend-links", middleware.RateLimitPublic(redisClient), handlers.FriendLink.ListPublic)
	r.GET("/friend-links/:id", middleware.RateLimitPublic(redisClient), handlers.FriendLink.GetPublic)
	r.GET("/users", middleware.RateLimitPublic(redisClient), handlers.User.ListAll)
	r.GET("/users/recent", middleware.RateLimitPublic(redisClient), handlers.User.ListRecent)
	r.GET("/users/presence", middleware.RateLimitPublic(redisClient), middleware.OptionalAuth(jwtManager), handlers.User.BatchPresence)
	r.GET("/users/:id/likes/count", middleware.RateLimitPublic(redisClient), handlers.User.CountLikedContent)
	r.GET("/users/:id/moments/count", middleware.RateLimitPublic(redisClient), handlers.User.CountMoments)
	r.GET("/users/:id/likes", middleware.RateLimitPublic(redisClient), handlers.User.ListLikedContent)
	r.GET("/users/:id", middleware.OptionalAuth(jwtManager), handlers.User.GetPublicProfile)
	r.GET("/articles/ids", middleware.RateLimitPublic(redisClient), handlers.Article.ListIDs)
	r.GET("/articles", middleware.OptionalAuth(jwtManager), handlers.Article.ListPublic)
	r.GET("/articles/:id", middleware.OptionalAuth(jwtManager), handlers.Article.GetPublicDetail)
	r.POST("/articles/:id/view", middleware.VisitorID(), handlers.Article.View)
	r.GET("/articles/:id/comments", middleware.OptionalAuth(jwtManager), handlers.Comment.ListArticle)
	r.GET("/guestbook", middleware.OptionalAuth(jwtManager), handlers.Guestbook.List)
	r.GET("/guestbook/comments/:id/replies", middleware.OptionalAuth(jwtManager), handlers.Comment.ListGuestbookReplies)
	r.GET("/moments", middleware.OptionalAuth(jwtManager), handlers.Moment.List)
	r.GET("/moments/feed", middleware.OptionalAuth(jwtManager), handlers.Moment.Feed)
	r.GET("/moments/:id", middleware.OptionalAuth(jwtManager), handlers.Moment.GetDetail)
	r.GET("/moments/:id/comments", middleware.OptionalAuth(jwtManager), handlers.Comment.ListMoment)
	r.GET("/moments/comments/:id/replies", middleware.OptionalAuth(jwtManager), handlers.Comment.ListMomentReplies)
	r.GET("/articles/comments/:id/replies", middleware.OptionalAuth(jwtManager), handlers.Comment.ListArticleReplies)
	r.POST("/moments/:id/view", middleware.VisitorID(), handlers.Moment.View)
	r.POST("/collect",
		middleware.VisitorID(),
		middleware.OptionalAuth(jwtManager),
		middleware.RateLimitPublic(redisClient),
		handlers.AnalyticsCollect.Collect,
	)
	r.GET("/analytics/public/summary", middleware.RateLimitPublic(redisClient), handlers.AnalyticsPublic.Summary)
	r.GET("/analytics/public/popular", middleware.RateLimitPublic(redisClient), handlers.AnalyticsPublic.Popular)
}

func registerAuthedRoutes(r *gin.Engine, handlers Handlers, jwtManager *jwt.Manager, redisClient *redis.Client) {
	authed := r.Group("/", middleware.Auth(jwtManager, handlers.UserCache))
	authed.GET("/test/authed", handlers.Test.Authed)
	authed.GET("/users/me", handlers.User.GetDetail)
	authed.PUT("/users/me", handlers.User.Update)
	authed.POST("/users/me/avatar", middleware.RateLimitAvatarUpload(redisClient), handlers.User.UploadAvatar)
	authed.PATCH("/users/me/profile", handlers.User.UpdateProfile)
	authed.PATCH("/users/me/meta", handlers.User.UpdateMeta)
	authed.PATCH("/users/me/social/:platform", handlers.User.UpdateSocialLink)
	authed.PATCH("/users/me/username", handlers.User.UpdateUsername)
	authed.PATCH("/users/me/password", handlers.User.UpdatePassword)
	authed.PATCH("/users/me/password/initial", handlers.User.SetInitialPassword)
	authed.POST("/users/me/email/code", middleware.RateLimitStrict(redisClient), handlers.User.SendEmailCode)
	authed.PATCH("/users/me/email", handlers.User.UpdateEmail)
	authed.PATCH("/users/me/email/display", handlers.User.UpdateEmailDisplay)
	authed.GET("/users/me/oauth-bindings", handlers.OAuth.ListBindings)
	authed.GET("/oauth/bindings", handlers.OAuth.ListBindings)
	authed.DELETE("/oauth/bindings/:source", handlers.OAuth.Unbind)
	authed.POST("/uploads/temp", middleware.RateLimitTempUpload(redisClient), handlers.Upload.TempImage)
	authed.GET("/articles/:id/like", handlers.Article.IsLiked)
	authed.POST("/articles/:id/like", handlers.Article.ToggleLike)

	publishLimit := middleware.RateLimitModerationWrite(redisClient, handlers.ModerationRateLimit.PublishPerMinute, "publish")
	editLimit := middleware.RateLimitModerationWrite(redisClient, handlers.ModerationRateLimit.EditPerMinute, "edit")
	authed.POST("/articles/:id/comments", publishLimit, handlers.Comment.CreateArticle)
	authed.POST("/articles/comments/:id/replies", publishLimit, handlers.Comment.ReplyArticle)
	authed.PATCH("/articles/comments/:id", editLimit, handlers.Comment.EditArticle)
	authed.PATCH("/articles/comment-replies/:id", editLimit, handlers.Comment.EditArticleReply)
	authed.POST("/articles/comments/:id/like", handlers.Comment.ToggleArticleLike)
	authed.POST("/articles/comments/:id/replies/:replyId/like", handlers.Comment.ToggleArticleReplyLike)
	authed.DELETE("/articles/comments/:id", handlers.Comment.DeleteArticle)
	authed.DELETE("/articles/comment-replies/:id", handlers.Comment.DeleteArticleReply)
	authed.POST("/guestbook", publishLimit, handlers.Guestbook.Create)
	authed.PATCH("/guestbook/:id", editLimit, handlers.Guestbook.Edit)
	authed.POST("/guestbook/:id/like", handlers.Guestbook.ToggleLike)
	authed.POST("/guestbook/comments/:id/replies", publishLimit, handlers.Comment.ReplyGuestbook)
	authed.PATCH("/guestbook/comment-replies/:id", editLimit, handlers.Comment.EditGuestbookReply)
	authed.POST("/guestbook/comments/:id/replies/:replyId/like", handlers.Comment.ToggleGuestbookReplyLike)
	authed.DELETE("/guestbook/comments/:id", handlers.Comment.DeleteGuestbook)
	authed.DELETE("/guestbook/comment-replies/:id", handlers.Comment.DeleteGuestbookReply)
	authed.DELETE("/guestbook/:id", handlers.Guestbook.Delete)
	authed.POST("/moments", middleware.RateLimitMomentUpload(redisClient), middleware.RateLimitModerationSave(
		redisClient, handlers.ModerationRateLimit.PublishPerMinute, handlers.ModerationRateLimit.EditPerMinute,
	), handlers.Moment.Save)
	authed.POST("/moments/:id/comments", publishLimit, handlers.Comment.CreateMoment)
	authed.POST("/moments/comments/:id/replies", publishLimit, handlers.Comment.ReplyMoment)
	authed.PATCH("/moments/comments/:id", editLimit, handlers.Comment.EditMoment)
	authed.PATCH("/moments/comment-replies/:id", editLimit, handlers.Comment.EditMomentReply)
	authed.POST("/moments/comments/:id/like", handlers.Comment.ToggleMomentLike)
	authed.POST("/moments/comments/:id/replies/:replyId/like", handlers.Comment.ToggleMomentReplyLike)
	authed.DELETE("/moments/comments/:id", handlers.Comment.DeleteMoment)
	authed.DELETE("/moments/comment-replies/:id", handlers.Comment.DeleteMomentReply)
	authed.DELETE("/moments/:id", handlers.Moment.Delete)
	authed.POST("/moments/:id/top", handlers.Moment.SetTop)
	authed.DELETE("/moments/:id/top", handlers.Moment.RemoveTop)
	authed.GET("/moments/:id/like", handlers.Moment.IsLiked)
	authed.POST("/moments/:id/like", handlers.Moment.ToggleLike)
	authed.GET("/notifications", handlers.Notification.List)
	authed.GET("/notifications/unread-count", handlers.Notification.UnreadCount)
	authed.PATCH("/notifications/read", handlers.Notification.MarkAllRead)
	authed.PATCH("/notifications/:id/read", handlers.Notification.MarkRead)
	authed.DELETE("/notifications/:id", handlers.Notification.Delete)
}

func registerVIPRoutes(r *gin.Engine, handlers Handlers, jwtManager *jwt.Manager) {
	vip := r.Group("/", middleware.Auth(jwtManager, handlers.UserCache), middleware.RequireRole(roles.VipRole))
	vip.GET("/test/vip", handlers.Test.Vip)
}

func registerAdminRoutes(r *gin.Engine, handlers Handlers, jwtManager *jwt.Manager, redisClient *redis.Client) {
	admin := r.Group("/admin", middleware.Auth(jwtManager, handlers.UserCache), middleware.RequireRole(roles.AdminRole))
	admin.GET("/test", handlers.Test.Admin)
	admin.GET("/articles", handlers.Article.ListAdmin)
	admin.GET("/articles/recommendations", handlers.Article.ListRecommendedAdmin)
	admin.PUT("/articles/recommendations/order", handlers.Article.ReorderRecommendedAdmin)
	admin.GET("/articles/:id", handlers.Article.GetAdminDetail)
	admin.POST("/articles", handlers.Article.Save)
	admin.DELETE("/articles/:id", handlers.Article.Delete)
	admin.DELETE("/articles/:id/permanent", handlers.Article.PermanentDelete)
	admin.GET("/comments", handlers.Comment.ListAdmin)
	admin.GET("/guestbook", handlers.Guestbook.ListAdmin)
	admin.GET("/moments", handlers.Moment.ListAdmin)
	admin.POST("/categories/uploads/icon", handlers.Category.UploadIcon)
	admin.POST("/categories/uploads/cover", handlers.Category.UploadCover)
	admin.POST("/categories", handlers.Category.Create)
	admin.PUT("/categories/:id", handlers.Category.Update)
	admin.DELETE("/categories/:id", handlers.Category.Delete)
	admin.POST("/categories/:id/articles", handlers.Category.AddArticles)
	admin.DELETE("/categories/:id/articles", handlers.Category.RemoveArticles)
	admin.POST("/tags", handlers.Tag.Create)
	admin.PUT("/tags/:id", handlers.Tag.Update)
	admin.DELETE("/tags/:id", handlers.Tag.Delete)
	admin.POST("/tags/:id/articles", handlers.Tag.AddArticles)
	admin.DELETE("/tags/:id/articles", handlers.Tag.RemoveArticles)
	admin.GET("/music/artists", handlers.Music.ListAdminArtists)
	admin.POST("/music/artists", handlers.Music.SaveArtist)
	admin.PUT("/music/artists/:id", handlers.Music.SaveArtist)
	admin.DELETE("/music/artists/:id", handlers.Music.DeleteArtist)
	admin.GET("/music/albums", handlers.Music.ListAdminAlbums)
	admin.POST("/music/albums", handlers.Music.SaveAlbum)
	admin.PUT("/music/albums/:id", handlers.Music.SaveAlbum)
	admin.DELETE("/music/albums/:id", handlers.Music.DeleteAlbum)
	admin.GET("/music", handlers.Music.ListAdmin)
	admin.POST("/music", handlers.Music.SaveMusic)
	admin.PUT("/music/:id", handlers.Music.SaveMusic)
	admin.DELETE("/music/:id", handlers.Music.DeleteMusic)
	admin.POST("/music/uploads/audio", handlers.Music.UploadAudio)
	admin.POST("/music/uploads/album-cover", handlers.Music.UploadAlbumCover)
	admin.POST("/music/uploads/artist-avatar", handlers.Music.UploadArtistAvatar)
	admin.GET("/friend-links", handlers.FriendLink.ListAdmin)
	admin.POST("/friend-links", middleware.RateLimitTempUpload(redisClient), handlers.FriendLink.Create)
	admin.PUT("/friend-links/:id", middleware.RateLimitTempUpload(redisClient), handlers.FriendLink.Update)
	admin.DELETE("/friend-links/:id", handlers.FriendLink.Delete)
	admin.GET("/notifications/email-tasks", handlers.NotificationAdmin.ListEmailTasks)
	admin.GET("/notifications/email-batches", handlers.NotificationAdmin.ListEmailBatches)
	admin.GET("/notifications/email-quotas", handlers.NotificationAdmin.ListQuotas)
	admin.PUT("/notifications/email-quotas/:id", handlers.NotificationAdmin.UpdateQuota)
	admin.PUT("/notifications/role-quotas/:id", handlers.NotificationAdmin.UpdateRoleQuota)
	admin.POST("/notifications/email-batches/:id/retry", handlers.NotificationAdmin.RetryBatch)

	registerModerationAdminRoutes(admin, handlers, redisClient)

	admin.POST("/users/:id/roles/vip", handlers.UserAdmin.GrantVip)
	admin.DELETE("/users/:id/roles/vip", handlers.UserAdmin.RevokeVip)
	admin.POST("/users/avatars/normalize", middleware.RateLimitNormal(redisClient), handlers.UserAdmin.NormalizeAvatars)
	admin.POST("/users/:id/avatar/clear", handlers.UserAdmin.ClearUserAvatar)
	admin.POST("/users/:id/disable", handlers.UserAdmin.DisableAccount)
	admin.POST("/users/:id/enable", handlers.UserAdmin.EnableAccount)
	admin.GET("/users", handlers.UserAdmin.ListAdmin)
	admin.GET("/users/:id", handlers.UserAdmin.GetDetail)
	admin.GET("/users/:id/operation-logs", handlers.UserAdmin.GetOperationLogs)
	admin.GET("/overview/summary", handlers.Dashboard.Overview)
	admin.GET("/analytics/overview", handlers.AnalyticsAdmin.Overview)
	admin.GET("/analytics/trend", handlers.AnalyticsAdmin.Trend)
	admin.GET("/analytics/pages", handlers.AnalyticsAdmin.Pages)
	admin.GET("/analytics/dimensions", handlers.AnalyticsAdmin.Dimensions)
	admin.GET("/analytics/friend-links", handlers.AnalyticsAdmin.FriendLinks)
	admin.GET("/analytics/paths", handlers.AnalyticsAdmin.Paths)
	admin.GET("/analytics/funnel", handlers.AnalyticsAdmin.Funnel)
	admin.GET("/analytics/realtime", handlers.AnalyticsAdmin.Realtime)
	admin.POST("/analytics/backfill", middleware.RateLimitNormal(redisClient), handlers.AnalyticsAdmin.Backfill)
}

func registerModerationAdminRoutes(admin *gin.RouterGroup, handlers Handlers, redisClient *redis.Client) {
	if handlers.ModerationAdmin == nil {
		return
	}
	admin.GET("/moderation/items", handlers.ModerationAdmin.List)
	admin.GET("/moderation/items/:id", handlers.ModerationAdmin.Get)
	admin.GET("/moderation/items/:id/history", handlers.ModerationAdmin.History)
	admin.POST("/moderation/items/:id/approve", middleware.RateLimitNormal(redisClient), handlers.ModerationAdmin.Approve)
	admin.POST("/moderation/items/:id/correct", middleware.RateLimitNormal(redisClient), handlers.ModerationAdmin.Correct)
	admin.POST("/moderation/items/:id/reject", middleware.RateLimitNormal(redisClient), handlers.ModerationAdmin.Reject)
	if handlers.ModerationAdmin.OperationsEnabled() {
		admin.GET("/moderation/control", handlers.ModerationAdmin.GetControl)
		admin.PATCH("/moderation/control", middleware.RateLimitNormal(redisClient), handlers.ModerationAdmin.UpdateControl)
		admin.GET("/moderation/users/:id", handlers.ModerationAdmin.GetUserProfile)
		admin.PATCH("/moderation/users/:id/profile", middleware.RateLimitNormal(redisClient), handlers.ModerationAdmin.UpdateUserProfile)
		admin.POST("/moderation/users/:id/mute", middleware.RateLimitNormal(redisClient), handlers.ModerationAdmin.MuteUser)
		admin.POST("/moderation/users/:id/ban", middleware.RateLimitNormal(redisClient), handlers.ModerationAdmin.BanUser)
		admin.POST("/moderation/users/:id/release", middleware.RateLimitNormal(redisClient), handlers.ModerationAdmin.ReleaseUser)
		admin.POST("/moderation/items/:id/hide", middleware.RateLimitNormal(redisClient), handlers.ModerationAdmin.HideItem)
		admin.POST("/moderation/items/:id/restore", middleware.RateLimitNormal(redisClient), handlers.ModerationAdmin.RestoreItem)
		admin.POST("/moderation/users/:id/hide-content", middleware.RateLimitNormal(redisClient), handlers.ModerationAdmin.HideUserContent)
		admin.POST("/moderation/users/:id/restore-content", middleware.RateLimitNormal(redisClient), handlers.ModerationAdmin.RestoreUserContent)
	}
	if handlers.ModerationAdmin.RulesEnabled() {
		admin.GET("/moderation/rules", handlers.ModerationAdmin.ListRules)
		admin.POST("/moderation/rules", middleware.RateLimitNormal(redisClient), handlers.ModerationAdmin.CreateRule)
		admin.PATCH("/moderation/rules/:id", middleware.RateLimitNormal(redisClient), handlers.ModerationAdmin.ReplaceRule)
		admin.POST("/moderation/rules/batch-status", middleware.RateLimitNormal(redisClient), handlers.ModerationAdmin.BatchStatus)
		admin.POST("/moderation/rules/test", handlers.ModerationAdmin.TestRuleText)
		admin.GET("/moderation/rules/export", handlers.ModerationAdmin.ExportRules)
		admin.GET("/moderation/rules/status", handlers.ModerationAdmin.GetRuleStatus)
		admin.GET("/moderation/rules/metadata", handlers.ModerationAdmin.GetRuleMetadata)
		admin.GET("/moderation/rule-imports/template", handlers.ModerationAdmin.DownloadTemplate)
		admin.POST("/moderation/rule-imports", middleware.RateLimitTempUpload(redisClient), handlers.ModerationAdmin.CreateImport)
		admin.GET("/moderation/rule-imports", handlers.ModerationAdmin.ListImports)
		admin.GET("/moderation/rule-imports/:id", handlers.ModerationAdmin.GetImport)
		admin.GET("/moderation/rule-imports/:id/errors", handlers.ModerationAdmin.DownloadImportErrors)
		admin.POST("/moderation/rule-imports/:id/publish", middleware.RateLimitNormal(redisClient), handlers.ModerationAdmin.PublishImport)
		admin.DELETE("/moderation/rule-imports/:id", handlers.ModerationAdmin.CancelImport)
	}
}
