package router

import (
	"github.com/gin-gonic/gin"
	"github.com/redis/go-redis/v9"

	"github.com/vpt/blog-backend/internal/middleware"
	"github.com/vpt/blog-backend/pkg/jwt"
	"github.com/vpt/blog-backend/pkg/roles"
)

func registerPublicRoutes(
	r *gin.Engine,
	handlers routeHandlers,
	jwtManager *jwt.Manager,
	redisClient *redis.Client,
) {
	r.GET("/health", middleware.RateLimitPublic(redisClient), handlers.health.Check)
	r.GET("/test/public", middleware.RateLimitPublic(redisClient), handlers.test.Public)
	r.POST("/test/token", handlers.test.GenToken)

	r.POST("/captcha/register/challenge", handlers.captcha.GenerateRegistrationChallenge)
	r.POST("/captcha/register/verify", handlers.captcha.VerifyRegistrationChallenge)
	r.POST("/auth/send-code", middleware.RateLimitStrict(redisClient), handlers.auth.SendCode)
	r.POST("/auth/password-reset/code", middleware.RateLimitStrict(redisClient), handlers.auth.SendPasswordResetCode)
	r.POST("/auth/password-reset", middleware.RateLimitStrict(redisClient), handlers.auth.ResetPassword)
	r.POST("/auth/register", middleware.RateLimitStrict(redisClient), handlers.auth.Register)
	r.POST("/auth/login", middleware.RateLimitLoose(redisClient), handlers.auth.Login)
	r.POST("/admin/auth/login", middleware.RateLimitLoose(redisClient), handlers.auth.AdminLogin)
	r.POST("/auth/refresh", handlers.auth.Refresh)
	r.GET("/oauth/providers", middleware.RateLimitPublic(redisClient), handlers.oauth.Providers)
	r.GET("/oauth/:source/authorize", middleware.RateLimitLoose(redisClient), middleware.OptionalAuth(jwtManager), handlers.oauth.Authorize)
	r.GET("/oauth/:source/callback", middleware.RateLimitLoose(redisClient), handlers.oauth.Callback)
	r.GET("/categories", middleware.RateLimitPublic(redisClient), handlers.category.ListTabs)
	r.GET("/tags", middleware.RateLimitPublic(redisClient), handlers.tag.List)
	r.GET("/tags/:id", middleware.RateLimitPublic(redisClient), handlers.tag.Get)
	r.GET("/tags/:id/articles", middleware.RateLimitPublic(redisClient), handlers.tag.ListArticles)
	r.GET("/music", middleware.RateLimitPublic(redisClient), handlers.music.List)
	r.GET("/music/artists", middleware.RateLimitPublic(redisClient), handlers.music.ListArtists)
	r.GET("/music/artists/:id", middleware.RateLimitPublic(redisClient), handlers.music.GetPublicArtist)
	r.GET("/music/albums", middleware.RateLimitPublic(redisClient), handlers.music.ListAlbums)
	r.GET("/music/albums/:id", middleware.RateLimitPublic(redisClient), handlers.music.GetPublicAlbum)
	r.GET("/music/:id", middleware.RateLimitPublic(redisClient), handlers.music.GetPublicDetail)
	r.GET("/friend-links", middleware.RateLimitPublic(redisClient), handlers.friendLink.ListPublic)
	r.GET("/friend-links/:id", middleware.RateLimitPublic(redisClient), handlers.friendLink.GetPublic)
	r.GET("/users", middleware.RateLimitPublic(redisClient), handlers.user.ListAll)
	r.GET("/users/recent", middleware.RateLimitPublic(redisClient), handlers.user.ListRecent)
	r.GET("/users/presence", middleware.RateLimitPublic(redisClient), middleware.OptionalAuth(jwtManager), handlers.user.BatchPresence)
	r.GET("/users/:id/likes/count", middleware.RateLimitPublic(redisClient), handlers.user.CountLikedContent)
	r.GET("/users/:id/moments/count", middleware.RateLimitPublic(redisClient), handlers.user.CountMoments)
	r.GET("/users/:id/likes", middleware.RateLimitPublic(redisClient), handlers.user.ListLikedContent)
	r.GET("/users/:id", middleware.OptionalAuth(jwtManager), handlers.user.GetPublicProfile)
	r.GET("/articles/ids", middleware.RateLimitPublic(redisClient), handlers.article.ListIDs)
	r.GET("/articles", middleware.OptionalAuth(jwtManager), handlers.article.ListPublic)
	r.GET("/articles/:id", middleware.OptionalAuth(jwtManager), handlers.article.GetPublicDetail)
	r.POST("/articles/:id/view", middleware.VisitorID(), handlers.article.View)
	r.GET("/articles/:id/comments", middleware.OptionalAuth(jwtManager), handlers.comment.ListArticle)
	r.GET("/guestbook", middleware.OptionalAuth(jwtManager), handlers.guestbook.List)
	r.GET("/guestbook/comments/:id/replies", middleware.OptionalAuth(jwtManager), handlers.comment.ListGuestbookReplies)
	r.GET("/moments", middleware.OptionalAuth(jwtManager), handlers.moment.List)
	r.GET("/moments/feed", middleware.OptionalAuth(jwtManager), handlers.moment.Feed)
	r.GET("/moments/:id", middleware.OptionalAuth(jwtManager), handlers.moment.GetDetail)
	r.GET("/moments/:id/comments", middleware.OptionalAuth(jwtManager), handlers.comment.ListMoment)
	r.GET("/moments/comments/:id/replies", middleware.OptionalAuth(jwtManager), handlers.comment.ListMomentReplies)
	r.GET("/articles/comments/:id/replies", middleware.OptionalAuth(jwtManager), handlers.comment.ListArticleReplies)
	r.POST("/moments/:id/view", middleware.VisitorID(), handlers.moment.View)
	r.POST("/collect",
		middleware.VisitorID(),
		middleware.OptionalAuth(jwtManager),
		middleware.RateLimitPublic(redisClient),
		handlers.analyticsCollect.Collect,
	)
	r.GET("/analytics/public/summary", middleware.RateLimitPublic(redisClient), handlers.analyticsPublic.Summary)
	r.GET("/analytics/public/popular", middleware.RateLimitPublic(redisClient), handlers.analyticsPublic.Popular)
}

func registerAuthedRoutes(r *gin.Engine, handlers routeHandlers, jwtManager *jwt.Manager, redisClient *redis.Client) {
	authed := r.Group("/", middleware.Auth(jwtManager, handlers.userCache))
	authed.GET("/test/authed", handlers.test.Authed)
	authed.GET("/users/me", handlers.user.GetDetail)
	authed.PUT("/users/me", handlers.user.Update)
	authed.POST("/users/me/avatar", middleware.RateLimitAvatarUpload(redisClient), handlers.user.UploadAvatar)
	authed.PATCH("/users/me/profile", handlers.user.UpdateProfile)
	authed.PATCH("/users/me/meta", handlers.user.UpdateMeta)
	authed.PATCH("/users/me/social/:platform", handlers.user.UpdateSocialLink)
	authed.PATCH("/users/me/username", handlers.user.UpdateUsername)
	authed.PATCH("/users/me/password", handlers.user.UpdatePassword)
	authed.PATCH("/users/me/password/initial", handlers.user.SetInitialPassword)
	authed.POST("/users/me/email/code", middleware.RateLimitStrict(redisClient), handlers.user.SendEmailCode)
	authed.PATCH("/users/me/email", handlers.user.UpdateEmail)
	authed.PATCH("/users/me/email/display", handlers.user.UpdateEmailDisplay)
	authed.GET("/users/me/oauth-bindings", handlers.oauth.ListBindings)
	authed.GET("/oauth/bindings", handlers.oauth.ListBindings)
	authed.DELETE("/oauth/bindings/:source", handlers.oauth.Unbind)
	authed.POST("/uploads/temp", middleware.RateLimitTempUpload(redisClient), handlers.upload.TempImage)
	authed.GET("/articles/:id/like", handlers.article.IsLiked)
	authed.POST("/articles/:id/like", handlers.article.ToggleLike)

	publishLimit := middleware.RateLimitModerationWrite(redisClient, handlers.moderationRateLimit.PublishPerMinute, "publish")
	editLimit := middleware.RateLimitModerationWrite(redisClient, handlers.moderationRateLimit.EditPerMinute, "edit")
	authed.POST("/articles/:id/comments", publishLimit, handlers.comment.CreateArticle)
	authed.POST("/articles/comments/:id/replies", publishLimit, handlers.comment.ReplyArticle)
	authed.PATCH("/articles/comments/:id", editLimit, handlers.comment.EditArticle)
	authed.PATCH("/articles/comment-replies/:id", editLimit, handlers.comment.EditArticleReply)
	authed.POST("/articles/comments/:id/like", handlers.comment.ToggleArticleLike)
	authed.POST("/articles/comments/:id/replies/:replyId/like", handlers.comment.ToggleArticleReplyLike)
	authed.DELETE("/articles/comments/:id", handlers.comment.DeleteArticle)
	authed.DELETE("/articles/comment-replies/:id", handlers.comment.DeleteArticleReply)
	authed.POST("/guestbook", publishLimit, handlers.guestbook.Create)
	authed.PATCH("/guestbook/:id", editLimit, handlers.guestbook.Edit)
	authed.POST("/guestbook/:id/like", handlers.guestbook.ToggleLike)
	authed.POST("/guestbook/comments/:id/replies", publishLimit, handlers.comment.ReplyGuestbook)
	authed.PATCH("/guestbook/comment-replies/:id", editLimit, handlers.comment.EditGuestbookReply)
	authed.POST("/guestbook/comments/:id/replies/:replyId/like", handlers.comment.ToggleGuestbookReplyLike)
	authed.DELETE("/guestbook/comments/:id", handlers.comment.DeleteGuestbook)
	authed.DELETE("/guestbook/comment-replies/:id", handlers.comment.DeleteGuestbookReply)
	authed.DELETE("/guestbook/:id", handlers.guestbook.Delete)
	authed.POST("/moments", middleware.RateLimitMomentUpload(redisClient), middleware.RateLimitModerationSave(
		redisClient, handlers.moderationRateLimit.PublishPerMinute, handlers.moderationRateLimit.EditPerMinute,
	), handlers.moment.Save)
	authed.POST("/moments/:id/comments", publishLimit, handlers.comment.CreateMoment)
	authed.POST("/moments/comments/:id/replies", publishLimit, handlers.comment.ReplyMoment)
	authed.PATCH("/moments/comments/:id", editLimit, handlers.comment.EditMoment)
	authed.PATCH("/moments/comment-replies/:id", editLimit, handlers.comment.EditMomentReply)
	authed.POST("/moments/comments/:id/like", handlers.comment.ToggleMomentLike)
	authed.POST("/moments/comments/:id/replies/:replyId/like", handlers.comment.ToggleMomentReplyLike)
	authed.DELETE("/moments/comments/:id", handlers.comment.DeleteMoment)
	authed.DELETE("/moments/comment-replies/:id", handlers.comment.DeleteMomentReply)
	authed.DELETE("/moments/:id", handlers.moment.Delete)
	authed.POST("/moments/:id/top", handlers.moment.SetTop)
	authed.DELETE("/moments/:id/top", handlers.moment.RemoveTop)
	authed.GET("/moments/:id/like", handlers.moment.IsLiked)
	authed.POST("/moments/:id/like", handlers.moment.ToggleLike)
	authed.GET("/notifications", handlers.notification.List)
	authed.GET("/notifications/unread-count", handlers.notification.UnreadCount)
	authed.PATCH("/notifications/read", handlers.notification.MarkAllRead)
	authed.PATCH("/notifications/:id/read", handlers.notification.MarkRead)
	authed.DELETE("/notifications/:id", handlers.notification.Delete)
}

func registerVIPRoutes(r *gin.Engine, handlers routeHandlers, jwtManager *jwt.Manager) {
	vip := r.Group("/", middleware.Auth(jwtManager, handlers.userCache), middleware.RequireRole(roles.VipRole))
	vip.GET("/test/vip", handlers.test.Vip)
}

func registerAdminRoutes(r *gin.Engine, handlers routeHandlers, jwtManager *jwt.Manager, redisClient *redis.Client) {
	admin := r.Group("/admin", middleware.Auth(jwtManager, handlers.userCache), middleware.RequireRole(roles.AdminRole))
	admin.GET("/test", handlers.test.Admin)
	admin.GET("/articles", handlers.article.ListAdmin)
	admin.GET("/articles/recommendations", handlers.article.ListRecommendedAdmin)
	admin.PUT("/articles/recommendations/order", handlers.article.ReorderRecommendedAdmin)
	admin.GET("/articles/:id", handlers.article.GetAdminDetail)
	admin.POST("/articles", handlers.article.Save)
	admin.DELETE("/articles/:id", handlers.article.Delete)
	admin.DELETE("/articles/:id/permanent", handlers.article.PermanentDelete)
	admin.GET("/comments", handlers.comment.ListAdmin)
	admin.GET("/guestbook", handlers.guestbook.ListAdmin)
	admin.GET("/moments", handlers.moment.ListAdmin)
	admin.POST("/categories/uploads/icon", handlers.category.UploadIcon)
	admin.POST("/categories/uploads/cover", handlers.category.UploadCover)
	admin.POST("/categories", handlers.category.Create)
	admin.PUT("/categories/:id", handlers.category.Update)
	admin.DELETE("/categories/:id", handlers.category.Delete)
	admin.POST("/categories/:id/articles", handlers.category.AddArticles)
	admin.DELETE("/categories/:id/articles", handlers.category.RemoveArticles)
	admin.POST("/tags", handlers.tag.Create)
	admin.PUT("/tags/:id", handlers.tag.Update)
	admin.DELETE("/tags/:id", handlers.tag.Delete)
	admin.POST("/tags/:id/articles", handlers.tag.AddArticles)
	admin.DELETE("/tags/:id/articles", handlers.tag.RemoveArticles)
	admin.GET("/music/artists", handlers.music.ListAdminArtists)
	admin.POST("/music/artists", handlers.music.SaveArtist)
	admin.PUT("/music/artists/:id", handlers.music.SaveArtist)
	admin.DELETE("/music/artists/:id", handlers.music.DeleteArtist)
	admin.GET("/music/albums", handlers.music.ListAdminAlbums)
	admin.POST("/music/albums", handlers.music.SaveAlbum)
	admin.PUT("/music/albums/:id", handlers.music.SaveAlbum)
	admin.DELETE("/music/albums/:id", handlers.music.DeleteAlbum)
	admin.GET("/music", handlers.music.ListAdmin)
	admin.POST("/music", handlers.music.SaveMusic)
	admin.PUT("/music/:id", handlers.music.SaveMusic)
	admin.DELETE("/music/:id", handlers.music.DeleteMusic)
	admin.POST("/music/uploads/audio", handlers.music.UploadAudio)
	admin.POST("/music/uploads/album-cover", handlers.music.UploadAlbumCover)
	admin.POST("/music/uploads/artist-avatar", handlers.music.UploadArtistAvatar)
	admin.GET("/friend-links", handlers.friendLink.ListAdmin)
	admin.POST("/friend-links", middleware.RateLimitTempUpload(redisClient), handlers.friendLink.Create)
	admin.PUT("/friend-links/:id", middleware.RateLimitTempUpload(redisClient), handlers.friendLink.Update)
	admin.DELETE("/friend-links/:id", handlers.friendLink.Delete)
	admin.GET("/notifications/email-tasks", handlers.notificationAdmin.ListEmailTasks)
	admin.GET("/notifications/email-batches", handlers.notificationAdmin.ListEmailBatches)
	admin.GET("/notifications/email-quotas", handlers.notificationAdmin.ListQuotas)
	admin.PUT("/notifications/email-quotas/:id", handlers.notificationAdmin.UpdateQuota)
	admin.PUT("/notifications/role-quotas/:id", handlers.notificationAdmin.UpdateRoleQuota)
	admin.POST("/notifications/email-batches/:id/retry", handlers.notificationAdmin.RetryBatch)

	registerModerationAdminRoutes(admin, handlers, redisClient)

	admin.POST("/users/:id/roles/vip", handlers.userAdmin.GrantVip)
	admin.DELETE("/users/:id/roles/vip", handlers.userAdmin.RevokeVip)
	admin.POST("/users/avatars/normalize", middleware.RateLimitNormal(redisClient), handlers.userAdmin.NormalizeAvatars)
	admin.POST("/users/:id/avatar/clear", handlers.userAdmin.ClearUserAvatar)
	admin.POST("/users/:id/disable", handlers.userAdmin.DisableAccount)
	admin.POST("/users/:id/enable", handlers.userAdmin.EnableAccount)
	admin.GET("/users", handlers.userAdmin.ListAdmin)
	admin.GET("/users/:id", handlers.userAdmin.GetDetail)
	admin.GET("/users/:id/operation-logs", handlers.userAdmin.GetOperationLogs)
	admin.GET("/overview/summary", handlers.dashboard.Overview)
	admin.GET("/analytics/overview", handlers.analyticsAdmin.Overview)
	admin.GET("/analytics/trend", handlers.analyticsAdmin.Trend)
	admin.GET("/analytics/pages", handlers.analyticsAdmin.Pages)
	admin.GET("/analytics/dimensions", handlers.analyticsAdmin.Dimensions)
	admin.GET("/analytics/friend-links", handlers.analyticsAdmin.FriendLinks)
	admin.GET("/analytics/paths", handlers.analyticsAdmin.Paths)
	admin.GET("/analytics/funnel", handlers.analyticsAdmin.Funnel)
	admin.GET("/analytics/realtime", handlers.analyticsAdmin.Realtime)
	admin.POST("/analytics/backfill", middleware.RateLimitNormal(redisClient), handlers.analyticsAdmin.Backfill)
}

func registerModerationAdminRoutes(admin *gin.RouterGroup, handlers routeHandlers, redisClient *redis.Client) {
	if handlers.moderationAdmin == nil {
		return
	}
	admin.GET("/moderation/items", handlers.moderationAdmin.List)
	admin.GET("/moderation/items/:id", handlers.moderationAdmin.Get)
	admin.GET("/moderation/items/:id/history", handlers.moderationAdmin.History)
	admin.POST("/moderation/items/:id/approve", middleware.RateLimitNormal(redisClient), handlers.moderationAdmin.Approve)
	admin.POST("/moderation/items/:id/correct", middleware.RateLimitNormal(redisClient), handlers.moderationAdmin.Correct)
	admin.POST("/moderation/items/:id/reject", middleware.RateLimitNormal(redisClient), handlers.moderationAdmin.Reject)
	if handlers.moderationAdmin.OperationsEnabled() {
		admin.GET("/moderation/control", handlers.moderationAdmin.GetControl)
		admin.PATCH("/moderation/control", middleware.RateLimitNormal(redisClient), handlers.moderationAdmin.UpdateControl)
		admin.GET("/moderation/users/:id", handlers.moderationAdmin.GetUserProfile)
		admin.PATCH("/moderation/users/:id/profile", middleware.RateLimitNormal(redisClient), handlers.moderationAdmin.UpdateUserProfile)
		admin.POST("/moderation/users/:id/mute", middleware.RateLimitNormal(redisClient), handlers.moderationAdmin.MuteUser)
		admin.POST("/moderation/users/:id/ban", middleware.RateLimitNormal(redisClient), handlers.moderationAdmin.BanUser)
		admin.POST("/moderation/users/:id/release", middleware.RateLimitNormal(redisClient), handlers.moderationAdmin.ReleaseUser)
		admin.POST("/moderation/items/:id/hide", middleware.RateLimitNormal(redisClient), handlers.moderationAdmin.HideItem)
		admin.POST("/moderation/items/:id/restore", middleware.RateLimitNormal(redisClient), handlers.moderationAdmin.RestoreItem)
		admin.POST("/moderation/users/:id/hide-content", middleware.RateLimitNormal(redisClient), handlers.moderationAdmin.HideUserContent)
		admin.POST("/moderation/users/:id/restore-content", middleware.RateLimitNormal(redisClient), handlers.moderationAdmin.RestoreUserContent)
	}
	if handlers.moderationAdmin.RulesEnabled() {
		admin.GET("/moderation/rules", handlers.moderationAdmin.ListRules)
		admin.POST("/moderation/rules", middleware.RateLimitNormal(redisClient), handlers.moderationAdmin.CreateRule)
		admin.PATCH("/moderation/rules/:id", middleware.RateLimitNormal(redisClient), handlers.moderationAdmin.ReplaceRule)
		admin.POST("/moderation/rules/batch-status", middleware.RateLimitNormal(redisClient), handlers.moderationAdmin.BatchStatus)
		admin.POST("/moderation/rules/test", handlers.moderationAdmin.TestRuleText)
		admin.GET("/moderation/rules/export", handlers.moderationAdmin.ExportRules)
		admin.GET("/moderation/rules/status", handlers.moderationAdmin.GetRuleStatus)
		admin.GET("/moderation/rules/metadata", handlers.moderationAdmin.GetRuleMetadata)
		admin.GET("/moderation/rule-imports/template", handlers.moderationAdmin.DownloadTemplate)
		admin.POST("/moderation/rule-imports", middleware.RateLimitTempUpload(redisClient), handlers.moderationAdmin.CreateImport)
		admin.GET("/moderation/rule-imports", handlers.moderationAdmin.ListImports)
		admin.GET("/moderation/rule-imports/:id", handlers.moderationAdmin.GetImport)
		admin.GET("/moderation/rule-imports/:id/errors", handlers.moderationAdmin.DownloadImportErrors)
		admin.POST("/moderation/rule-imports/:id/publish", middleware.RateLimitNormal(redisClient), handlers.moderationAdmin.PublishImport)
		admin.DELETE("/moderation/rule-imports/:id", handlers.moderationAdmin.CancelImport)
	}
}
