// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vpt/blog-backend/internal/service/user (interfaces: OnlineChecker)
//
// Generated by this command:
//
//	mockgen -destination=internal/service/user/mock/mock_online_checker.go -package=mock github.com/vpt/blog-backend/internal/service/user OnlineChecker
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockOnlineChecker is a mock of OnlineChecker interface.
type MockOnlineChecker struct {
	ctrl     *gomock.Controller
	recorder *MockOnlineCheckerMockRecorder
	isgomock struct{}
}

// MockOnlineCheckerMockRecorder is the mock recorder for MockOnlineChecker.
type MockOnlineCheckerMockRecorder struct {
	mock *MockOnlineChecker
}

// NewMockOnlineChecker creates a new mock instance.
func NewMockOnlineChecker(ctrl *gomock.Controller) *MockOnlineChecker {
	mock := &MockOnlineChecker{ctrl: ctrl}
	mock.recorder = &MockOnlineCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOnlineChecker) EXPECT() *MockOnlineCheckerMockRecorder {
	return m.recorder
}

// BatchIsUserOnline mocks base method.
func (m *MockOnlineChecker) BatchIsUserOnline(ctx context.Context, userIDs []uint) (map[uint]bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchIsUserOnline", ctx, userIDs)
	ret0, _ := ret[0].(map[uint]bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchIsUserOnline indicates an expected call of BatchIsUserOnline.
func (mr *MockOnlineCheckerMockRecorder) BatchIsUserOnline(ctx, userIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchIsUserOnline", reflect.TypeOf((*MockOnlineChecker)(nil).BatchIsUserOnline), ctx, userIDs)
}

// IsUserOnline mocks base method.
func (m *MockOnlineChecker) IsUserOnline(ctx context.Context, userID uint) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsUserOnline", ctx, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsUserOnline indicates an expected call of IsUserOnline.
func (mr *MockOnlineCheckerMockRecorder) IsUserOnline(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsUserOnline", reflect.TypeOf((*MockOnlineChecker)(nil).IsUserOnline), ctx, userID)
}
