// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vpt/blog-backend/internal/repository/moderation (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -destination=internal/repository/moderation/mock/mock_repository.go -package=mock github.com/vpt/blog-backend/internal/repository/moderation Repository
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	moderation "github.com/vpt/blog-backend/internal/repository/moderation"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// ApplyTransition mocks base method.
func (m *MockRepository) ApplyTransition(ctx context.Context, cmd moderation.ApplyTransitionCommand) (moderation.AppliedTransition, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyTransition", ctx, cmd)
	ret0, _ := ret[0].(moderation.AppliedTransition)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ApplyTransition indicates an expected call of ApplyTransition.
func (mr *MockRepositoryMockRecorder) ApplyTransition(ctx, cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyTransition", reflect.TypeOf((*MockRepository)(nil).ApplyTransition), ctx, cmd)
}

// FindResultByIdempotencyKey mocks base method.
func (m *MockRepository) FindResultByIdempotencyKey(ctx context.Context, userID uint64, key string) (*moderation.StoredResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindResultByIdempotencyKey", ctx, userID, key)
	ret0, _ := ret[0].(*moderation.StoredResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindResultByIdempotencyKey indicates an expected call of FindResultByIdempotencyKey.
func (mr *MockRepositoryMockRecorder) FindResultByIdempotencyKey(ctx, userID, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindResultByIdempotencyKey", reflect.TypeOf((*MockRepository)(nil).FindResultByIdempotencyKey), ctx, userID, key)
}

// LoadEnabledRules mocks base method.
func (m *MockRepository) LoadEnabledRules(ctx context.Context) ([]moderation.RuleRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadEnabledRules", ctx)
	ret0, _ := ret[0].([]moderation.RuleRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadEnabledRules indicates an expected call of LoadEnabledRules.
func (mr *MockRepositoryMockRecorder) LoadEnabledRules(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadEnabledRules", reflect.TypeOf((*MockRepository)(nil).LoadEnabledRules), ctx)
}

// LoadItemState mocks base method.
func (m *MockRepository) LoadItemState(ctx context.Context, ref moderation.SubjectRef) (moderation.ItemStateRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadItemState", ctx, ref)
	ret0, _ := ret[0].(moderation.ItemStateRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadItemState indicates an expected call of LoadItemState.
func (mr *MockRepositoryMockRecorder) LoadItemState(ctx, ref any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadItemState", reflect.TypeOf((*MockRepository)(nil).LoadItemState), ctx, ref)
}

// LoadModerationView mocks base method.
func (m *MockRepository) LoadModerationView(ctx context.Context, refs []moderation.SubjectRef, viewer moderation.Viewer) (map[moderation.SubjectKey]moderation.View, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadModerationView", ctx, refs, viewer)
	ret0, _ := ret[0].(map[moderation.SubjectKey]moderation.View)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadModerationView indicates an expected call of LoadModerationView.
func (mr *MockRepositoryMockRecorder) LoadModerationView(ctx, refs, viewer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadModerationView", reflect.TypeOf((*MockRepository)(nil).LoadModerationView), ctx, refs, viewer)
}

// LoadPolicyContext mocks base method.
func (m *MockRepository) LoadPolicyContext(ctx context.Context, userID uint64) (moderation.PolicyContext, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadPolicyContext", ctx, userID)
	ret0, _ := ret[0].(moderation.PolicyContext)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadPolicyContext indicates an expected call of LoadPolicyContext.
func (mr *MockRepositoryMockRecorder) LoadPolicyContext(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadPolicyContext", reflect.TypeOf((*MockRepository)(nil).LoadPolicyContext), ctx, userID)
}

// LoadSubject mocks base method.
func (m *MockRepository) LoadSubject(ctx context.Context, ref moderation.SubjectRef) (moderation.SubjectSnapshot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadSubject", ctx, ref)
	ret0, _ := ret[0].(moderation.SubjectSnapshot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadSubject indicates an expected call of LoadSubject.
func (mr *MockRepositoryMockRecorder) LoadSubject(ctx, ref any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadSubject", reflect.TypeOf((*MockRepository)(nil).LoadSubject), ctx, ref)
}

// RecordBlockedAttempt mocks base method.
func (m *MockRepository) RecordBlockedAttempt(ctx context.Context, attempt moderation.BlockedAttempt) (moderation.StoredResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordBlockedAttempt", ctx, attempt)
	ret0, _ := ret[0].(moderation.StoredResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RecordBlockedAttempt indicates an expected call of RecordBlockedAttempt.
func (mr *MockRepositoryMockRecorder) RecordBlockedAttempt(ctx, attempt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordBlockedAttempt", reflect.TypeOf((*MockRepository)(nil).RecordBlockedAttempt), ctx, attempt)
}
