// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vpt/blog-backend/internal/repository/moderation (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -destination=internal/repository/moderation/mock/mock_repository.go -package=mock github.com/vpt/blog-backend/internal/repository/moderation Repository
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"
	time "time"

	moderation "github.com/vpt/blog-backend/internal/repository/moderation"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// ApplyTransition mocks base method.
func (m *MockRepository) ApplyTransition(ctx context.Context, cmd moderation.ApplyTransitionCommand) (moderation.AppliedTransition, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyTransition", ctx, cmd)
	ret0, _ := ret[0].(moderation.AppliedTransition)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ApplyTransition indicates an expected call of ApplyTransition.
func (mr *MockRepositoryMockRecorder) ApplyTransition(ctx, cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyTransition", reflect.TypeOf((*MockRepository)(nil).ApplyTransition), ctx, cmd)
}

// EnsureNewProfile mocks base method.
func (m *MockRepository) EnsureNewProfile(ctx context.Context, userID uint64, now time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureNewProfile", ctx, userID, now)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnsureNewProfile indicates an expected call of EnsureNewProfile.
func (mr *MockRepositoryMockRecorder) EnsureNewProfile(ctx, userID, now any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureNewProfile", reflect.TypeOf((*MockRepository)(nil).EnsureNewProfile), ctx, userID, now)
}

// FindResultByIdempotencyKey mocks base method.
func (m *MockRepository) FindResultByIdempotencyKey(ctx context.Context, userID uint64, key string) (*moderation.StoredResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindResultByIdempotencyKey", ctx, userID, key)
	ret0, _ := ret[0].(*moderation.StoredResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindResultByIdempotencyKey indicates an expected call of FindResultByIdempotencyKey.
func (mr *MockRepositoryMockRecorder) FindResultByIdempotencyKey(ctx, userID, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindResultByIdempotencyKey", reflect.TypeOf((*MockRepository)(nil).FindResultByIdempotencyKey), ctx, userID, key)
}

// ListReviewRecords mocks base method.
func (m *MockRepository) ListReviewRecords(ctx context.Context, filter moderation.ReviewFilter) (moderation.ReviewPage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListReviewRecords", ctx, filter)
	ret0, _ := ret[0].(moderation.ReviewPage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListReviewRecords indicates an expected call of ListReviewRecords.
func (mr *MockRepositoryMockRecorder) ListReviewRecords(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListReviewRecords", reflect.TypeOf((*MockRepository)(nil).ListReviewRecords), ctx, filter)
}

// LoadCurrentReviewRecord mocks base method.
func (m *MockRepository) LoadCurrentReviewRecord(ctx context.Context, itemID uint64) (moderation.ReviewRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadCurrentReviewRecord", ctx, itemID)
	ret0, _ := ret[0].(moderation.ReviewRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadCurrentReviewRecord indicates an expected call of LoadCurrentReviewRecord.
func (mr *MockRepositoryMockRecorder) LoadCurrentReviewRecord(ctx, itemID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadCurrentReviewRecord", reflect.TypeOf((*MockRepository)(nil).LoadCurrentReviewRecord), ctx, itemID)
}

// LoadEnabledRules mocks base method.
func (m *MockRepository) LoadEnabledRules(ctx context.Context) ([]moderation.RuleRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadEnabledRules", ctx)
	ret0, _ := ret[0].([]moderation.RuleRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadEnabledRules indicates an expected call of LoadEnabledRules.
func (mr *MockRepositoryMockRecorder) LoadEnabledRules(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadEnabledRules", reflect.TypeOf((*MockRepository)(nil).LoadEnabledRules), ctx)
}

// LoadItemState mocks base method.
func (m *MockRepository) LoadItemState(ctx context.Context, ref moderation.SubjectRef) (moderation.ItemStateRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadItemState", ctx, ref)
	ret0, _ := ret[0].(moderation.ItemStateRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadItemState indicates an expected call of LoadItemState.
func (mr *MockRepositoryMockRecorder) LoadItemState(ctx, ref any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadItemState", reflect.TypeOf((*MockRepository)(nil).LoadItemState), ctx, ref)
}

// LoadModerationProfile mocks base method.
func (m *MockRepository) LoadModerationProfile(ctx context.Context, userID uint64, now time.Time) (moderation.ModerationProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadModerationProfile", ctx, userID, now)
	ret0, _ := ret[0].(moderation.ModerationProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadModerationProfile indicates an expected call of LoadModerationProfile.
func (mr *MockRepositoryMockRecorder) LoadModerationProfile(ctx, userID, now any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadModerationProfile", reflect.TypeOf((*MockRepository)(nil).LoadModerationProfile), ctx, userID, now)
}

// LoadModerationView mocks base method.
func (m *MockRepository) LoadModerationView(ctx context.Context, refs []moderation.SubjectRef, viewer moderation.Viewer) (map[moderation.SubjectKey]moderation.View, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadModerationView", ctx, refs, viewer)
	ret0, _ := ret[0].(map[moderation.SubjectKey]moderation.View)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadModerationView indicates an expected call of LoadModerationView.
func (mr *MockRepositoryMockRecorder) LoadModerationView(ctx, refs, viewer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadModerationView", reflect.TypeOf((*MockRepository)(nil).LoadModerationView), ctx, refs, viewer)
}

// LoadPolicyContext mocks base method.
func (m *MockRepository) LoadPolicyContext(ctx context.Context, userID uint64) (moderation.PolicyContext, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadPolicyContext", ctx, userID)
	ret0, _ := ret[0].(moderation.PolicyContext)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadPolicyContext indicates an expected call of LoadPolicyContext.
func (mr *MockRepositoryMockRecorder) LoadPolicyContext(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadPolicyContext", reflect.TypeOf((*MockRepository)(nil).LoadPolicyContext), ctx, userID)
}

// LoadReviewRecord mocks base method.
func (m *MockRepository) LoadReviewRecord(ctx context.Context, itemID, revisionID uint64) (moderation.ReviewRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadReviewRecord", ctx, itemID, revisionID)
	ret0, _ := ret[0].(moderation.ReviewRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadReviewRecord indicates an expected call of LoadReviewRecord.
func (mr *MockRepositoryMockRecorder) LoadReviewRecord(ctx, itemID, revisionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadReviewRecord", reflect.TypeOf((*MockRepository)(nil).LoadReviewRecord), ctx, itemID, revisionID)
}

// LoadRevisionImages mocks base method.
func (m *MockRepository) LoadRevisionImages(ctx context.Context, revisionID uint64) ([]moderation.RevisionImageRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadRevisionImages", ctx, revisionID)
	ret0, _ := ret[0].([]moderation.RevisionImageRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadRevisionImages indicates an expected call of LoadRevisionImages.
func (mr *MockRepositoryMockRecorder) LoadRevisionImages(ctx, revisionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadRevisionImages", reflect.TypeOf((*MockRepository)(nil).LoadRevisionImages), ctx, revisionID)
}

// LoadRevisionPreviewKeys mocks base method.
func (m *MockRepository) LoadRevisionPreviewKeys(ctx context.Context, revisionID uint64) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadRevisionPreviewKeys", ctx, revisionID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadRevisionPreviewKeys indicates an expected call of LoadRevisionPreviewKeys.
func (mr *MockRepositoryMockRecorder) LoadRevisionPreviewKeys(ctx, revisionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadRevisionPreviewKeys", reflect.TypeOf((*MockRepository)(nil).LoadRevisionPreviewKeys), ctx, revisionID)
}

// LoadSubject mocks base method.
func (m *MockRepository) LoadSubject(ctx context.Context, ref moderation.SubjectRef) (moderation.SubjectSnapshot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadSubject", ctx, ref)
	ret0, _ := ret[0].(moderation.SubjectSnapshot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadSubject indicates an expected call of LoadSubject.
func (mr *MockRepositoryMockRecorder) LoadSubject(ctx, ref any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadSubject", reflect.TypeOf((*MockRepository)(nil).LoadSubject), ctx, ref)
}

// RecordBlockedAttempt mocks base method.
func (m *MockRepository) RecordBlockedAttempt(ctx context.Context, attempt moderation.BlockedAttempt) (moderation.StoredResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordBlockedAttempt", ctx, attempt)
	ret0, _ := ret[0].(moderation.StoredResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RecordBlockedAttempt indicates an expected call of RecordBlockedAttempt.
func (mr *MockRepositoryMockRecorder) RecordBlockedAttempt(ctx, attempt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordBlockedAttempt", reflect.TypeOf((*MockRepository)(nil).RecordBlockedAttempt), ctx, attempt)
}

// ReleaseSanction mocks base method.
func (m *MockRepository) ReleaseSanction(ctx context.Context, userID uint64, now time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReleaseSanction", ctx, userID, now)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReleaseSanction indicates an expected call of ReleaseSanction.
func (mr *MockRepositoryMockRecorder) ReleaseSanction(ctx, userID, now any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReleaseSanction", reflect.TypeOf((*MockRepository)(nil).ReleaseSanction), ctx, userID, now)
}

// SetAutomaticTrust mocks base method.
func (m *MockRepository) SetAutomaticTrust(ctx context.Context, cmd moderation.AutomaticTrustCommand) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetAutomaticTrust", ctx, cmd)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetAutomaticTrust indicates an expected call of SetAutomaticTrust.
func (mr *MockRepositoryMockRecorder) SetAutomaticTrust(ctx, cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetAutomaticTrust", reflect.TypeOf((*MockRepository)(nil).SetAutomaticTrust), ctx, cmd)
}

// SetSanction mocks base method.
func (m *MockRepository) SetSanction(ctx context.Context, cmd moderation.SetSanctionCommand) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetSanction", ctx, cmd)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetSanction indicates an expected call of SetSanction.
func (mr *MockRepositoryMockRecorder) SetSanction(ctx, cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSanction", reflect.TypeOf((*MockRepository)(nil).SetSanction), ctx, cmd)
}

// SetTrust mocks base method.
func (m *MockRepository) SetTrust(ctx context.Context, cmd moderation.SetTrustCommand) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetTrust", ctx, cmd)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetTrust indicates an expected call of SetTrust.
func (mr *MockRepositoryMockRecorder) SetTrust(ctx, cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTrust", reflect.TypeOf((*MockRepository)(nil).SetTrust), ctx, cmd)
}

// UpsertPendingImage mocks base method.
func (m *MockRepository) UpsertPendingImage(ctx context.Context, image moderation.PendingImage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertPendingImage", ctx, image)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertPendingImage indicates an expected call of UpsertPendingImage.
func (mr *MockRepositoryMockRecorder) UpsertPendingImage(ctx, image any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertPendingImage", reflect.TypeOf((*MockRepository)(nil).UpsertPendingImage), ctx, image)
}

// UseApprovedImage mocks base method.
func (m *MockRepository) UseApprovedImage(ctx context.Context, fingerprint moderation.ImageFingerprint, usedAt time.Time) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UseApprovedImage", ctx, fingerprint, usedAt)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UseApprovedImage indicates an expected call of UseApprovedImage.
func (mr *MockRepositoryMockRecorder) UseApprovedImage(ctx, fingerprint, usedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UseApprovedImage", reflect.TypeOf((*MockRepository)(nil).UseApprovedImage), ctx, fingerprint, usedAt)
}
